    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 44/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 45/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 46/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 47/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 48/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 49/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 5/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 50/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 51/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 52/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 53/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 54/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 55/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 56/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 57/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 58/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 59/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 6/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 60/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 7/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 8/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: SYGMA LABORATORIO OPTICO LTDA > Parcela 9/60 > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 1/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 10/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 11/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 12/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 13/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 14/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 15/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 16/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 17/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 18/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 19/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 2/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 20/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 21/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 22/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 23/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 24/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 25/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 26/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 27/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 28/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 29/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 3/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 30/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 31/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 32/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 33/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 34/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 35/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 36/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 37/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 38/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 39/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 4/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 40/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 41/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 42/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 43/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 44/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 45/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 46/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 47/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 48/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 49/49 > PIX: 47.392.457/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 5/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 6/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 7/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 8/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO: VISION PRIME - Parcela 9/49 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADAPTADOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADEGA DO BAIANO: Pó de café > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADELIA EMI KOMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Ariani Dias Fernandes Líbano (ref. ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Bruno Henrique Simão (ref. 03/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Felipe Roger Miranda (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Felipe Roger Miranda (ref. ) > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Felipe Roger Miranda (ref. ) > PIX: (11) 9 5805-6343 (celular) - Banco Itaú (Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Felipe Roger Miranda (ref. ) > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Kayllaine Pereira Alves de Araújo (ref. ) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Luana Cristina Martins Campos (ref. ) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Maria Elizabeth Pereira do Nascimento (ref. ) > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Nicolas Coutinho da Silva (ref. ) > PIX: (11) 9 5328- 7646 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO SALARIAL: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Alessandra Santana (divulgação, ref. dias trabalhados)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Cleberson Ribeiro de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADIANTAMENTO: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ADVOGADA: BRUNA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO - TÉCNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO - TÉCNICO (conserto de computador para o escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO - TÉCNICO: Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO - TÉCNICO: Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO - TÉCNICO: Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular) ~ (manutenção notebook- Taty)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO ANJOS - LOST INFORMÁTICA > Parcela 1/2 > PIX: 11) 9 7468-1969 (celular) ~ (manutenção PC - administrativo)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO ANJOS - LOST INFORMÁTICA > Parcela 1/3 > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO ANJOS - LOST INFORMÁTICA > Parcela 2/2 > PIX: 11) 9 7468-1969 (celular) ~ (manutenção PC - administrativo)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AGUINALDO ANJOS - LOST INFORMÁTICA > Parcela 3/3 > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AIHARA E CIA LTDA: Madeirite > Cleberson Ribeiro de Jesus (ref. 1 dia trabalhado > ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALBANO EMBALAGENS ES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALBANO: Papel de seda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALBERTO AKIO ICHI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALBERTO AKIO ICHIKAWA: ALMOÇO - TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALCON: Lentes de contato - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALCON: Lentes de contato - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALCON: Lentes de contato - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALCOOL EM GEL E LÍQUIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALINE CRISTINA: SUPERMERCADO SHIBATA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 02/09 22:36 ESPETINHOS FERNANDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 03/01 14:55 LANCHONETE E REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 03/02 17:15 FILIAL BK DRIVE S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 04/02 11:01 MEGA MAIS CONVENIENC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 04/02 16:57 MEGA SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 05/11 14:25 LANC REST RIO MIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 08/10 20:30 ESPETINHO DO GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 14/09 18:22 BURGER KING ALPHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 17/09 14:23 TEMPERO MANERO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 18/02 18:12 DDU DUTRA DRIVE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 19/11 15:33 LANCHONETE E REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 21/12 11:28 PAG*CONVENIENCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 21/12 20:13 LOJA DE CONVENIENCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 27/10 20:43 BURGER KING ALPHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 27/11 14:22 LANCHONETE E REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 28/09 15:05 APOLLO GRILL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 29/01 15:48 BOIZAO EVENTOS EI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 29/01 23:27 BURGER KING MARGI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 29/12 14:16 MEGA SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 29/12 14:24 LANCHONETE E REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - 30/10 18:04 HABIBS RIBEIRAO P', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA: ALDENIR E ALINE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA: ALMOÇO - ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA: ALMOÇO - ALINE CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA: ALMOÇO - ALINE HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA: ALMOÇO - ANNE KELLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALBERTO AKIO ICHIKAWA: ALMOÇO - ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO DA TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO DE FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO DIVULGAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO DOS FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO EQUIPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO EQUIPE: TAMIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: ALINE CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: ANDREIA LEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: FRANCINEIDE E TAMIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - ALMOÇO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - BIZON SALGADOS SAO PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - BURG KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - BURGER KING: CHICKENN ALC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - BURGER KING: WHOPPER Q', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - CASA DE CARNES ANGE SUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - CASA DE SALGADOS DEUS É FIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - CASA DE SALGADOS DEUS É FIEL (DIEGO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - CASA DE SALGADOS DEUS É FIEL (EVELINE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - EQUIPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - F D I BAZAR LTDA ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - FILIAL BK DRIVE SUZANO S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - GASTOS PARA PAGTO FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - GILBERTO JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - HABIBS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - HABIBS RIBEIRAO P', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - LANCHONETE E RESTAURANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - LETÍCIA ARCENCIO DA C.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - LOJA DE CONVENIENCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - MC DONALDS SUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - MC DONALDS SZD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - MC DONALDS SZD SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - MC DONALDS: BIG MAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - MEGA MAIS CONVENIENC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - P M S YOGUI - RESTAURANTE: ALMOÇO ALESSANDRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG* ADRIANA PRESTES DE MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG* ADRIANA PRESTES DE MORAIS: ANDREIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG* JOSUE BATISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG* VIVIANI DOS SANTOS DIAS (WEVILLY)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG*ADRIANAPRESTESDE SAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG*JOSEBATISTADE SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PAG*JOSUEBATISTADEAND SU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PASTELARIA ERENITO SUZAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTE MORAIS FOOD: ALMOÇO - ALINE, ANDREIA E ZAINE', 'juridica', NULL, True, NOW(), NOW());
INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
