INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), '(ESTORNO, ref. a depósito errado) - BRASCOR > PIX: 19.344.768/0001-00 (CNPJ) - ref. OS''s 10705 e 10706', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '(ESTORNO, ref. a depósito errado) - ENEL 0049320513 - LOJA RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '(ESTORNO, ref. ao desconto dado na loja Armarinhos Fernando) - MIKE RODRIGUES GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '- AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '- BRASLAB PRODUTOS OTICOS EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '- BRASLAB PRODUTOS OTICOS EIRELI >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '- VALE ALIMENTAÇÃO/REFEIÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1 cartaz para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1 cartolina para cartaz loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/2 - Pagamento Cadeiras e mesas festa Nautika -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/2 - Pagamento da festa Ana Paula', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/2 Pagamento Decoração Josie -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Aline Cristina Moreira da Cunha (ref. 11/09 - ) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Aline Cristina Moreira da Cunha (ref. 15/04 - ) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 1/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 2/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 3/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 4/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 5/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Jocicreide Macedo Barbosa Santos - Parcela 1/2 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Jocicreide Macedo Barbosa Santos - Parcela 2/2 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 1/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 2/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 3/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 DAS FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 4/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1/3 FÉRIAS - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1029/1030: JAQUELINE DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1151: SIRLANDIA NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1177: ROSELI APARECIDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1189: ESTER ALVES MACHADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1189: ESTER ALVES MACHADO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1191: SIDNEY DO CARMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1192: JURACY PAULO LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1195: JOSÉ NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1204: ELISABETE BUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1214: RAQUEL GONÇALVES DE MELLO SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1215: BIANCA GONÇALVES DE MELLO SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1221: JOSENIEDO DA SILVA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Ana Cristina Rodrigues Amâcio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Ana Paula Aparecida Moreira da Silva Yuki (ref. jul - dez/2024) > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Anna Beatriz de Camargo Lorena (11) 9 4079-5920', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Eliana Savoia (ref. jun~set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Eliana Savoia (ref. out~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Emerson William da Silva Santos (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Felipe Roger Miranda (ref. fev - jun/2024) > PIX: 11958056343 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Felipe Roger Miranda (ref. jul- dez/2024) > PIX: 11958056343 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Giovanna Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Joana D''arc Elvira Jesus Alves Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Kathleen dos Santos Campos (ref. set - dez/2024) > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Kayllaine Pereira Alves de Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Kayllaine Pereira Alves de Araújo (ref. jan - jun/2024) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Kayllaine Pereira Alves de Araújo (ref. jul - dez/2024) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Kethelyn Miranda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Larissa Dias Fernandes Cardozo (ref. fev~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Larissa Dias Fernandes Cardozo (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Letícia Morais Domingos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Luana Cristina Martins Campos (ref. jan - jun/2024) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Luana Cristina Martins Campos (ref. jul - dez/2024) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Maria Elizabeth Pereira do Nascimento (ref. fev~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Maria Elizabeth Pereira do Nascimento (ref. fev~dez/2023) ~ (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Maria Elizabeth Pereira do Nascimento (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Maria da Conceição Ramos de Moura (ref. abr~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Maria da Conceição Ramos de Moura (ref. fev~mar/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Nicolas Coutinho da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Nicolas Coutinho da Silva (ref. jan - dez/2024) > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rogério Aparecido de Morais (ref. jan~set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rogério Aparecido de Morais (ref. jan~set/2023) ~ (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rogério Aparecido de Morais (ref. out~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rosangela Aparecida Dejane Ribeiro (ref. ago~set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Rosangela Aparecida Dejane Ribeiro (ref. out~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Vanessa Mendes da Silva (ref. fev - jun/2024) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Vanessa Mendes da Silva (ref. jul - dez/2024) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Wevilly de Souza Fernandes Líbano (ref. fev~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Wevilly de Souza Fernandes Líbano (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Érika de Oliveira Gomes (ref. abr~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 1/2: Érika de Oliveira Gomes (ref. fev~mar/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Ana Cristina Rodrigues Amâncio (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Ana Paula Aparecida Moreira da Silva Yuki (ref. jul - dez/2024) > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Anna Beatriz de Camargo Lorena', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Eliana Savoia (ref. jun~set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Eliana Savoia (ref. out~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Felipe Roger Miranda (ref. jul- dez/2024) > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Giovanna Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Joana D''arc Elvira Jesus Alves Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Joana D''arc Elvira Jesus Alves Araújo (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Joana D''arc Elvira Jesus Alves Araújo (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Joana D''arc Elvira Jesus Alves Araújo (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Kathleen dos Santos Campos (ref. set - dez/2024) > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Kayllaine Pereira Alves de Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Kayllaine Pereira Alves de Araújo (ref. jan - jun/2024) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Kayllaine Pereira Alves de Araújo (ref. jul - dez/2024) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Kethelyn Miranda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Larissa Dias Fernandes Cardozo (ref. fev~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Larissa Dias Fernandes Cardozo (ref. fev~dez/2023) ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Larissa Dias Fernandes Cardozo (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Luana Cristina Martins Campos (ref. jan - jun/2024) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Luana Cristina Martins Campos (ref. jul - dez/2024) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Maria Elizabeth Pereira do Nascimento (ref. fev~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Maria Elizabeth Pereira do Nascimento (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Maria da Conceição Ramos de Moura (ref. abr~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Maria da Conceição Ramos de Moura (ref. fev~mar/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Mike Rodrigues Gomes (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Nicolas Coutinho da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Nicolas Coutinho da Silva (ref. jan - dez/2024) > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Rogério Aparecido de Morais (ref. jan~set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Rogério Aparecido de Morais (ref. out~dez/2023) ~ (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Rosangela Aparecida Dejane Ribeiro (ref. ago~set/2023) ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Rosangela Aparecida Dejane Ribeiro (ref. out~dez/2023) ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Vanessa Mendes da Silva (ref. fev - jun/2024) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Vanessa Mendes da Silva (ref. jul - dez/2024) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Wevilly de Souza Fernandes Líbano (ref. fev~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Wevilly de Souza Fernandes Líbano (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Érika de Oliveira Gomes (ref. abr~dez/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO - Parcela 2/2: Érika de Oliveira Gomes (ref. fev~mar/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. ago~ dez/2022): Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jan~ dez/2022): Cleberson Ribeiro de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jan~ dez/2022): Giovanna Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jan~ maio/2022): Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jul~ ago/2022): Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jul~ dez/2022): Diego Francisco dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jul~ dez/2022): Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. jun ~ dez/2022): Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. mar~ jun/2022): Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. nov~ dez/2022): Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. nov~ dez/2022): Mirian Ferreira Sanches', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. out~ dez/2022): Yasmin da Silva Costa dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2 (ref. set ~ dez/2022): Thayssa Roberta Lima da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13° SALÁRIO 2/2: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13º SALÁRIO - 13° SALÁRIO: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13º SALÁRIO - 13° SALÁRIO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13º SALÁRIO - 13° SALÁRIO: ARIANI DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13º SALÁRIO - 13° SALÁRIO: NATHALIA CAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '13º SALÁRIO - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 1/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 10/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 11/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 12/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 13/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 14/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 15/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 16/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 17/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 18/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 19/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 2/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 20/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 21/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 22/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 23/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 24/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 25/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 26/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 27/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 28/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 29/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 3/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 30/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 31/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 32/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 4/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 5/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 6/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 7/32', 'juridica', NULL, True, NOW(), NOW());
