INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'ICMS: Simples Nacional 01/2023 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 01/2023 - Parcela 7/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 01/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 01/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 01/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 02/2023 - Parcela 10/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 02/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 02/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 02/2023 - Parcela 9/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 02/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 03/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 03/2023 - Parcela 12/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 03/2023 - Parcela 13/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 03/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 03/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 04/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 04/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 10/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 11/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 2/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 25/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 26/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 27/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 28/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 29/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 3/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 30/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 31/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 32/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 33/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 34/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 35/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 37/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 38/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 39/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 4/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 40/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 41/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 42/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 43/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 44/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 45/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 46/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 47/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 48/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 49/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 5/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 50/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 51/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 52/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 53/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 54/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 55/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 56/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 57/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 58/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 59/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 6/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 60/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 7/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 8/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2021 - Parcela 9/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 05/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 06/2021 - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 06/2021 - Parcela 11/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 06/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 06/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 14/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 15/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 16/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 17/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 18/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 2/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 3/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2022 - Parcela 5/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 07/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 13/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 14/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2021 - Parcela 15/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 08/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 09/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 09/2022 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 09/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 09/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 10/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 11/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 11/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 12/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 12/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPERIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPERIO DO BOLO: Bolo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - AUTENTICAÇÃO DO DOCUMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - BOLETO ALVARA E VIGILANGIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 01/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 04/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 05/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 07/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 08/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 09/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 11/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 11/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 1/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 1/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 2/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 2/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 3/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 4/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 5/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 6/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 7/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - COFINS: SIMPLES NACIONAL - PARCELA 8/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CONTRIBUIÇÃO ASSISTENCIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 01/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 04/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 05/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 06/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 07/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 08/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 11/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 11/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 1/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 1/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 2/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 2/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 3/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 4/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 5/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 6/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 7/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - CSLL: SIMPLES NACIONAL - PARCELA 8/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DAMSP - DOCUMENTO DE ARRECADAÇÃO DO MUNICÍPIO DE SÃO PAULO (RECEITA TFE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARE-SP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF IR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF IR: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF MÁRCIA TAKIUTTU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF MÁRCIA TAKIUTTU: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF PEDRA MIECA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF PEDRA MIECA: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF SICALC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF VINÍCIUS TAKIUTTU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - DARF VINÍCIUS TAKIUTTU: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - FGTS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - FGTS ARRECADACAO GRF', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - FISCALIZAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - GARE ICMS - GUIA DE ARRECADAÇÃO ESTADUAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - GPS: GUIA DA PREVIDÊNCIA SOCIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS 11/2020', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: IMPLES NACIONAL - PARCELA 1/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: IMPLES NACIONAL - PARCELA 2/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 01/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 04/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 05/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 06/2022', 'juridica', NULL, True, NOW(), NOW());
