INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMPRA DE ARMAÇÃO: OS 1012', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMPRA DE ESTOJOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMÉRCIO DE DOCES IMPERIAL GOLD EIR: PACOTE DE BALAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COPO DESCARTÁVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COPOS E INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DATACITY SERVICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DESENTUPIDOR SANITÁRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DIVERSOS PARA LOJA - LOJAS KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DOCES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DUPARI COMERCIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DUPARI COMERCIAL EIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DUPARI COMERCIAL EIREL S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - DUPARI COMERCIAL EIRELI: CALCULADORA E PILHA AA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ELETRICA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - EMBALAGENS PRIMULLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - EMPREENDIMENTOS PAGUE MENOS S.A FARMÁCIAS PAGUE MENOS: ÁGUA BORICADA DAUF FARMA 100ML E COMPR. GAZE PAGUE MENOS 11F C/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - EMPÓRIO DO REAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - EXTENSÃO E ADAPTADOR ELÉTRICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - F D I BAZAR LTDA ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - F D I BAZAR LTDA: COPO DESCARTÁVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - F D I BAZAR LTDA: SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FANTASIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FESTIPEL EMBALAGENS LTDA: BALÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FESTIPEL EMBALAGENS LTDA: BALÃO E TERMOCOLANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FESTIPEL EMBALAGENS LTDA: BALÃO E TNT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FESTIPEL EMBALAGENS LTDA: BLOCO DE RECIBO 50F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FESTIPEL EMBALAGENS LTDA: PAPEL INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FOLHAS DE SULFITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - FORLOVE PRESENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - HEADBAND', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - INTERFOLHA, PAPEL HIGIÊNICO E COPO 200ML', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - INTERFONE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ISQUEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - KALUNGA: BOBINA TÉRMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL COMÉRCIO DE EMBALAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL COMÉRCIO DE EMBALAGENS: DETERGENTE LÍQUIDO E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL EMBALAGENS: CANETA BIC PRETA E COPO 180ML C/100', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL EMBALAGENS: PAPEL HIGIÊNICO NESS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL EMBALAGENS: PAPEL INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL EMBALAGENS: SACO DE LIXO 100L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEL EMBALAGENS: ÁLCOOL LÍQUIDO 70% 1L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEZA DESCARTAVEIS E S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEZA DESCARTÁVEIS E PISCINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEZA DESCARTÁVEIS E PISCINA: INTERFOLHA PARA MÃOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEZA DESCARTÁVEIS E PISCINA: INTERFOLHA PARA MÃOS E SABONETE LÍQUIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEZA DESCARTÁVEIS E PISCINA: INTERFOLHA PARA MÃOS E ÁLCOOL ETÍLICO 70%', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIMPEZAS DESCARTÁVEIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LIXAS P/ PASSAGEM DE LENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJA KODAMA LTDA: DILUENTE ESM. REPOS. ÓLEO BANANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING SUZANO BRA, N', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: ALCOOL GEL 450G', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: ALCOOL GEL 450G E ALCOOL LÍQUIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: ALCOOL LÍQUIDO 70% 1L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: ALCOOL LÍQUIDO 70% 1L E ALCOOL GEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: BOMBOM SONHO DE VALSA E OURO BRANCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: CAIXAS ORGANIZADORA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: COPOS DESCARTÁVEIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: EXTENSÃO 3T 5MP BIPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: FOLHA SULFITE A4 100 FOLHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: ISQUEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: KIT MÁSCARA C/10 ADULTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: PAPE HIGIÊNICO NESS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: PAPEL SULFITE 500 FOLHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: PILHA ALCALINA AA2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: PILHA ALFACELL AA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: PILHA PANASONIC AA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LOJAS KING: ÁLCOOL LÍQUIDO 70% 1L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LUAN ENFEITES LTDA: ITENS PARA DECORAR A LOJA (ESPECIAL DIA DOS NAMORADOS <3)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - LUAN ENFEITES LTDA: VARETAS AZUL, CRISTAL E ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MAHO BOLOS E SALGADOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MATERIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MAUAMI BAZAR E PAPELARIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MERCADO PAGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MERCATO EXPRESS HOLDING DE PARCIPAÇÃO: COXINHA DE FRANGO CREMELY E COXINHA DE 04 QUEIJOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MERCEDES DA*MSN REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - MONITOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - NAZARET CAMILO GAMA 53 S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ND SERVICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PADARIA E CONFEITARIA PAINEIRA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PADARIA RENASCE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAG* ADRIANA PRESTES DE MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAG* TIAGO TESTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAG*DANIELLEFARIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAG*DONAALICE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAG*SERGIOSHIGUEOHIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PANO COPA E PANO DE CHÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAPEL CHAMEX A4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAPEL DE CEDA PARA EMBALAGEM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAPEL HIGIÊNICO E REMOVEDOR DE ESMALTE (CONSERTO DA LENTE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAPEL SULLE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PARAFUSOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PAYGO*CHAVEIRO E CARIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PERFUMARIA TAKARA: ÓLEO DE BANANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PILHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PILHAS RAYOVAC AAA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PONTO DO DOCE SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PRODUTO DE LIMPEZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PRODUTO PARA LIMPEZA: PASTA DE LIMÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - PRODUTOS DE LIMPEZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - R C P FARMACIA LTDA SAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - REFRIGERANTE PARA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - RODO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - RUBI UTILIDADES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SABONETE LÍQUIDO E INTERFOLHA BRANCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SACO DE LIXO E INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SACOS DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SAINT GOTAIN DISTRIBUIÇÃO BRASIL S.A.: TINTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SAKOPEL: PACOTES DE BALÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SANTA HELENA DOCES E P S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SASAKI COMPONENTES ELETRÔNICOS LTDA: FITA ISOLANTE 3M IMPERIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SEIJUN YAMAUCHI PAPELARIA - ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SHOP KIDS MAGAZINE LTDA: AMENDOIM, BALA, PIRULITO, SALGADINHO E SACOLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SINGO: JARRA CAFETEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SODIMAC DICICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SOFT PEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - STONE DOCE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SUPER BONDER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SUPER F. D. I. BAZAR LTDA: BEXIGAS E PIRULITOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SUZURAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SUZURAN BOMBONIERE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SUZURAN BOMBONIERE SUZAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - SUZURAN BOMBONIERI SUZAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TEKBOND', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - THINNER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - THINNER PARA LIMPEZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TIAGO TESTA: BOLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TONER COMPATÍVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: BIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: CAFÉ PILÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: MARGARINA 250G', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: MARSHMALLOW 250G', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: PÃO DE FORMA E DESINFETANTE CASA & PERFUME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: SACO DE LIXO E DESINFETANTE 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - TOP LAR: SACO PARA LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ULTRAFARMA: SORO FISIOLÓGICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - YAMA PRINT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - YAMA PRINT SUZANO BRA, N', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCEPT IMOVEIS - SUZANO (condomínio)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCEPT IMOVEIS LTDA - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCEPT IMOVEIS LTDA: Escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCEPT IMOVEIS LTDA: Escritório (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCEPT IMOVEIS LTDA: Escritório (multa por atraso - IPTU, ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCERTO MOTOR PORTÃO ESCRITÓRIO - PIX: 39482733835', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCERTO MOTOR PORTÃO ESCRITÓRIO - PIX: 39482733835 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONCERTO PORTA DE MAUÁ - PIX: 39482733835', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONDOMÍNIO RESIDENCIAL ELDORADO - ref. ago/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONDOMÍNIO RESIDENCIAL ELDORADO - ref. jul/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONDOMÍNIO RESIDENCIAL ELDORADO - ref. mai/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONDUÇÃO PARA FUNCIONÁRIOS - ATELIÊ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONDUÇÃO: Mike (entregas, ref. Mauá e São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONFECÇÃO DE FAIXA: Mudança de loja - GIGI COMERCIO VAREJISTA DE OTICA LTDA > PIX: 51.837.184/0001-80 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONJUNTO MARLAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - 1 CONSERTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - ACETONA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - CONSERTO ARMAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - CONSERTO DE ÓCULOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - CONSERTO ÓCULOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - ESMALTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - FIO DE NYLON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - HOSPITAL DO CELULAR: SMARTPHONE SAMSUNG G610 (LOJA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - LIXA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - LIXA UNHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - PAG*WILLIANSAIRESDO SUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - SERVIÇO DE ENCANADOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - STÚDIO 7: MONTAGEM & CONSERTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSERTO - ÓTICAS BELLARTE: CONSERTOS, MONTAGENS OU SOLDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSULTA: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSULTAS - ACIB BARUERI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSULTAS - ACIB BARUERI (NUBANK - Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONSULTAS - ACIB BARUERI: JUROS,/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - CAMBRAZ - CÂMARA DE ARBITRAGEM MEDIAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - E-CNPJ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - E-CPF: TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - GAINEN CERTIFICADORA DIGITAL E-CNPJ (CERTIFICADO DIGITAL A1)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - GÊNESIS O. C. E EMPRESARIAL LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE & CONSULTORIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE E CONSULTORIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE E CONSULTORIA LTDA: ABERTURA CNPJ (TMO) - PARCELA 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE E CONSULTORIA LTDA: ABERTURA CNPJ (TMO) - PARCELA 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE E CONSULTORIA LTDA: ALTERAÇÃO CONTRATO SOCIAL: T.M.O - PARCELA 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE E CONSULTORIA LTDA: ALTERAÇÃO CONTRATO SOCIAL: T.M.O - PARCELA 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - KONSEP CONTABILIDADE E CONSULTORIA LTDA: ALTERAÇÃO CONTRATO SOCIAL: T.M.O - PARCELA 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - PAGAMENTO PARA CERTIFICAÇÃO DIGITAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - PAGAMENTO PARA CONTABILIDADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTABILIDADE - PAGAMENTO PARA GÊNESIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTR PREV DESCONTA SEGURADO - AVULSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREV RISCO AMBIENTAL/APOSENT ESPECIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREV RISCO AMBIENTAL/APOSENT ESPECIAL - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO - 13° SALÁRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO - GIOVANNA COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/INDIVIDUAIS', 'juridica', NULL, True, NOW(), NOW());
