INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - CP :90400888-PEDRO CARVALHO DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-RENATA SOARES NASSUTTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-ROMEU ALVES DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-ROSELI VIEIRA RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-ZULEIDE GROSSO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-ZULEIKA ERICINA DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - D MORAES SERVICOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - DEPÓSITO RECEBIDO - CIELO S.A. * ANTECIPAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - DEPÓSITO RECEBIDO - CIELO S.A. * DÉBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - DEPำSITO ONLINE - 7978-09-SOP-CIDADE DAS FLORES SP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - DEVOLUÇÃO PIX RECEBIDA - LAUNCH PAD TECNOLOGIA, SERVIÇOS E PAGAMENTOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ECOPISTA FPAY ITAQUAQUECETU BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ECOPISTAS ITAQUAQUECETU BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - EST COMPRA CARTAO - ESTORNO NO ESTABELECIMENTO NÃO INFORMADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ESTORNO DE DЙBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - FABIANA MELLO ANTONIATE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - FABIANA PACINI PEREIRA FRANCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - FELIPE ALVES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - GABRIELA FERREIRA CONDINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - GIGI C V OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - GISELLE ENTLER HARTMANN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - IMPOSTOS - DAS - SIMPLES NACIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - IMPOSTOS - RFB-DARF CODIGO DE BARRAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - INT PRE PAGOXXXXX 1171', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - JOSE CARLOS DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - JULIA NIVEA DE MOURA TORRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - KELLORY CRISTINA AGUIAR SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - LARISSA NUNES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - LIRIS EDIRLE RANGEL ICHIE 26447621896', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - LUAN ENFEITES LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - LUANA KARINE IKARI SANTANA - almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - MAYARA DE LIMA TORQUATO.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - MAYARA REGINA XAVIER MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - MONIKE NAKAYAMA VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NABIS PIZZARIA & ESFIHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NATALIA RODRIGUES DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NAZIH TAHA GHUNEIM EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO ATACADO ESPERANCA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO GRAN SUZANO AUTO POSTO SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO KANPEK RESTAURANTE SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO MP *MERCEARIA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO NO PRECINHO SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO PADARIA RENASCER SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO PAG*IMPERIOPIZZARIA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO PAGUE MENOS 919 SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO PASTELARIA ERENITO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO SORVETERIA BOM GOSTO I SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - NO ESTABELECIMENTO VILA FIGUEIRA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - OLGA DE OLIVEIRA ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAG*MERCADINHOVALEDAS SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAGAMENTO CONTA LUZ - ELETROPAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAGAMENTO DE BOLETO - SERVIP SERVICOS P LTDA ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY A POSTO PON 02 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY AUTO POSTO 01 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY AUTO POSTO 03 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY DIVISAU AUTO POSTO 27 02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY FALCONI AUTO POSTO 22 02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY FRUTOS DE G 02 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY I CARRAVIE 01 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY NAGUMO 27 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PAG ESQUINA 31 12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PAG PATROPI 01 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PAG PIZZARI 01 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PAG REALSUL 03 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PANIFICADOR 03 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PORTAL POA AUTO POSTO 01 03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY PORTAL POA AUTO POSTO 27 03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY RODOANEL AUTO POSTO 06 02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY RODOANEL AUTO POSTO 13 02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY RODOANEL AUTO POSTO 28 03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY RODOANEL LE 07 02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY RODOANEL LE 14 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY SUPERMERCAD 02 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY SUPERMERCAD 03 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PAY THAI AUTO POSTO 22 02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - AGENDAMENTO - 08/02 05:39 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 02/02 07:11 LUCAS DOS SANTOS CORNELIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 02/02 21:58 MARIA DA CONCEICAO RAMOS D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 02/02 22:02 NEWFLEX COMERCIO DE MOVEIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 03/01 22:54 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 03/01 22:57 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 03/01 23:47 JOSE PINHEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 04/01 08:41 MIRIAN FERREIRA SANCHES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 05/03 18:21 MARIA DA CONCEICAO RAMOS D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 06/01 22:00 JOSE PINHEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 06/01 22:01 ANA GABRIELA PINHEIRO PINT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 06/02 10:48 TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 06/02 22:19 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 07/02 23:00 GISLANIA DE OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 07/02 23:01 FRANCISCA LINDINEIS NASCIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 07/03 23:52 VITORIA REGINA NUNES DA CO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 07/03 23:57 ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/02 08:46 NATHALIA CAROLINA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/02 09:39 TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/02 11:12 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/02 16:08 LUCAS DOS SANTOS CORNELIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/03 00:03 IGOR NASCIMENTO MEDEIROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/03 00:04 MARIA DA CONCEICAO RAMOS D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/03 00:05 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/03 10:47 BRUNO HENRIQUE SIMAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 08/03 10:50 NATHALIA CAROLINA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/01 21:24 STEFANY RAYNE SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/01 21:24 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/01 21:30 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/02 08:54 GISLANIA DE OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/02 22:06 JOICE CAROLINE SANTOS DE S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/03 17:32 GILBERTO DE CAMARGO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 09/03 22:09 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 10/01 21:41 ELVIS MARQUES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 10/03 13:07 360 IMPRIMIR COMPOSICAO DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 12/01 23:06 RICHARD KRASHINSKI SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 12/01 23:09 DIEGO JESUS GUEDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 13/01 19:06 GISLANIA DE OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 13/01 19:21 BANCO SANTANDER BRASIL S A', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 13/01 22:00 DIEGO FRANCISCO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 14/02 11:05 GILBERTO DE CAMARGO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 14/02 20:38 TATIANE PINHEIRO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 14/02 21:09 BANCO SANTANDER BRASIL S A', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 15/02 21:54 4ROI GROUP LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 15/02 22:00 GILBERTO DE CAMARGO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 16/01 21:17 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 16/02 21:45 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 16/02 21:49 JED MORENO EVENTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 17/01 21:42 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 17/02 00:55 GILBERTO DE CAMARGO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 17/02 11:39 GENALVA CAVALCANTE DA SILV', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 19/01 13:59 THALITA FANTINATO SANTOS P', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 19/01 21:52 DIEGO JESUS GUEDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 19/01 21:53 GUILHERME CESAR MENDES DOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 20/01 13:34 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 22/02 10:02 TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 22/03 20:18 SERVIP SERVICOS PORTARIA L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 23/02 19:32 LAUNCH PAD TECNOLOGIA, SER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 23/02 19:35 GAINEN CERTIFICADORA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 23/02 19:37 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 23/02 19:48 GUILHERME AUG FERREIRA MAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 23/02 19:49 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 24/01 08:36 MEDICINE ASSISTENCIA EM ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 24/01 20:15 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 24/01 20:57 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 24/01 20:58 GISLANIA DE OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 25/02 13:26 TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 25/02 16:09 GIOVANNA CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 26/01 12:04 SETH CELL COMERCIO, SERVIC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 26/01 21:42 LUCAS DOS SANTOS CORNELIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 27/01 20:40 DIEGO JESUS GUEDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 27/02 21:31 TATIANE PINHEIRO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 30/01 12:57 NEWFLEX COMERCIO DE MOVEIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 30/01 21:45 EMERSON WILLIAN DA SILVA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 30/01 21:49 DANILO JOSE DE FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 30/01 21:50 WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 31/01 07:35 GUILHERME AUG FERREIRA MAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 31/01 09:28 TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 31/01 10:40 PIX MARKETPLACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - ENVIADO - 31/01 10:43 AMAZON SERVIวOS DE VAREJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/02 14:10 00046602207881 TAYNARA CRI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/02 14:22 00012697132805 MARIA CELIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/02 14:50 00046602207881 TAYNARA CRI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 10:43 00038257479802 DIOGO FERRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 11:57 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 13:38 00010663714826 SOLANGE GOM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 14:13 00009516137822 RODNEY TIMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 16:09 00037424062808 GIRLENE DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 16:30 00038551006835 LARISSA CRI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 16:31 00022290884839 JEFFERSON R', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 17:16 00042476385808 MONIQUE FER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 01/03 17:17 00047351648808 NATมLIA MAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/01 10:32 00028042948972 ANTONIO MAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/01 11:12 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/02 10:07 00048391177807 LETICIA ROB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/02 11:27 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/02 12:16 00010663714826 SOLANGE GOM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/02 16:01 00048648689805 EMANUELLE S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/03 13:49 00017859076896 VLADIMIR DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/03 16:47 00007405904807 ROBERTO DOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/03 17:05 00002260156886 INALDA MARI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 02/04 11:47 00007405904807 ROBERTO DOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/01 16:01 00040203567854 KAIQUE BEZE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/02 09:12 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/02 11:41 00026343411801 LUSILENE MA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/03 11:32 00027461334824 FABIANO SAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/03 11:47 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/04 11:22 00029005640855 CASSIA CILE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/04 11:46 00029005640855 CASSIA CILE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/04 12:16 00019658584810 JOCELIA ALV', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 03/04 13:44 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/01 11:46 00022367986878 VALษRIO SAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/01 13:12 00009980794801 MARIA APARE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/01 13:13 12109247000120 CREDZ ADMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/01 14:34 00010663714826 SOLANGE GOM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/01 16:09 00026343411801 LUSILENE MA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/02 10:44 00041167978803 CARLOS ALBE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/02 10:57 00031589130898 MICHELE PIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/02 17:13 00037799726890 RAYELLE MEN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/03 11:46 00042981998862 PEDRO HENRI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/03 14:06 00012112834886 LUIS CLAUDI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/03 14:23 00003004327805 MARA REGINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/03 16:07 00033633700838 DEBORA MARI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX - RECEBIDO - 04/04 14:37 00035814658843 JAQUELINE S', 'juridica', NULL, True, NOW(), NOW());
