INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ZAINE SIQUEIRA (PERÍODO 21/02 A 31/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ZAYNE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRASPORTE: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - ZAINE CORDEIRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - ZAYNE CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE : Maria Elizabeth (para divulgadora)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE Bilhete: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE, Maria Isabel Moura da Silva (diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Adriana Cristina Oliveira da Silva (divulgadora, ref. - ida e volta Suzano)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Adriane Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Alessandra > ESTORNO > Maria Elizabeth > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Alessandra Barbosa Leme (ref. 09/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Alessandra Barbosa Leme (ref. 13/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Alessandra Santana (divulgação, ref. 06/12 a 10/12)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Aline Cristina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Aline Cristina Moreira da Cunha (SUZANO I) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Aline Cristina Moreira da Cunha (diferença ônibus ~ - ) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Carolina Bandeira Vital dos Santos > PIX: bandeiravitaldossantosa@gmail.com (e-mail) - ref.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Clara Faria Lamounier (ref. 12/09 - ) > PIX: (11) 9 8438-0346 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Clara Faria Lamounier (ref. 15/09 - ) > PIX: (11) 9 8438-0346 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Cristina Rodrigues Amancio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Cristina Rodrigues Amancio (diferença a pagar referente até o dia ) > PIX: (11) 9 4132-7245 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Cristina Rodrigues Amancio (ref. Perus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Cristina Rodrigues Amancio > PIX: (11) 9 4132-7245 (celular) > (ref. 04/11 a )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Paula Aparecida Moreira da Silva Yuki (ref. 12/07 - ) > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Paula Aparecida Moreira da Silva Yuki > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ana Paula Aparecida da Silva Yuki > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Anderson de Jesus Souza (ref. 17/08-) > PIX: andersondjesus742@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Andressa Bezerra da Silva > PIX: 496.339.448-05 (CPF) - ref. - teste', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Andressa Paula da Silva (dias trabalhados, ref. 13/12 a 24/12)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Anna Beatriz da Camargo Lorena', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Anna Beatriz de Camargo Lorena', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Anna Beatriz de Camargo Lorena PIX: 11940795920', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Cardozo (diferença, ref. 06/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Líbano (diferença de integração ~ 07/07 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Líbano (ref. ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Líbano (ref. 01/04 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Líbano (ref. 27/02 ~ ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: BRUNO HENRIQUE SIMAO (ref. 09/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Beatriz Silva de Matos Araújo (ref. ) > PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Beatriz Silva de Matos Araújo (ref. 04/12 - ) > PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Beatriz Silva de Matos Araújo (ref. 07/12 - ) > PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Beatriz Silva de Matos Araújo (ref. 17/12 - ) > PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Bianca Raquel da Silva Santos (adiantamento, ref. 26/06 ~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Bruna Dias de Souza (ref. 29/07 - ) > PIX: (11) 9 6088-1210 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Bruna Dias de Souza > PIX: (11) 9 6088-1210 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Bruno Henrique Simão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Bruno Henrique Simão (diferença, ref. 24/03 - 31/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Camila Faccin Vieira (ref. 07/04 - ) > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Camila Faccin Vieira (ref. 15/04 - ) > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Camila Faccin Vieira (ref. 23/04 - ) > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Camila Faccin Vieira > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Camila Faccin Vieira > PIX: (11) 9 5485-1322 (celular) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus (adiantamento)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus (ref. ) > PIX: 517.291.608-32 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus (ref. 15/04 e - dias trabalhados > MAUÁ e SUZANO) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus (ref. 18/03 e - dias trabalhados) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus (ref. 21/03 e 22/03 - dias trabalhados) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Cleberson Ribeiro de Jesus > PIX: ribeirocleber704@gmail.com (e-mail) - Manutenção das lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Davi Pereira Gonçalves Mônaco (ref. ) >PIX: diasroselaine01@gmail.com (EMAIL) <', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Dyenifer Nicole Brandão da Rocha (ref. 01/09 - ) > PIX: (15) 9 9773-6533 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Dyenifer Nicole Brandão da Rocha (ref. 1 dia trabalhado > ) > PIX: (15) 9 9773-6533 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Dyenifer Nicole Brandão da Rocha (ref. 14/08 - ) > PIX: (15) 9 9773-6533 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (auxiliar de vendas, ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (auxiliar de vendas, ref. ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (auxiliar de vendas, ref. 03/06 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (auxiliar de vendas, ref. 17/05 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (divulgadora, ref. ) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (divulgadora, ref. 05/02 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (divulgadora, ref. 19/01 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (divulgadora, ref. 23/01 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira (divulgadora, ref. 29/01 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Débora Lemes Siqueira > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Elaine Cristina da Silva > (divulgadora, ref. 20/03 - ) > PIX: (11) 9 3037-0304 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia (adiantamento, ref. 05/07~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia (divulgadora, ref. 14/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia (divulgadora, ref. 20/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia (divulgadora, ref. 27/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia (ref. 05/06 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eliana Savoia > PIX: (11) 9 4714-9764 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson William (ref. 07/10~) > PIX: 430.482.058-37 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson William da Silva Santos (diferença, ref. 06/2023 - 03/07 a 08/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson William da Silva Santos (ref. 05/08 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson William da Silva Santos ref. 05/08 e )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson William da Silva Santos ref. 07/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Emerson da Rocha (ref. 22/11 - ) - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Estefany de Oliveira Penha (divulgadora, ref. ) > PIX: epenhaoliveira@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eveline Gianetti (ref. 16/12 - ida e volta Suzano)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Felipe Arruda Lellis (divulgador, ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Felipe Arruda Lellis Bentoglio (adiantamento)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Felipe Roger Miranda > (diferença ônibus ~ - ) > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Felipe Roger Miranda > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Giovanna Camargo (ref. ) (SÃO MATEUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Gislainia de Oliveira Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Gislania de Oliveira Silva (ref. 01/02-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Isabella Santos da Silva (divulgadora, ref. 26/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Isabelle da Silva Sousa (divulgadora, ref. 08/03 - ) > PIX: (11) 9 8552-3110 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jannayna N. Alves (ref. 12/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jannayna N. Alves (ref. 13/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jenny Oliveira Santos Ramos (auxiliar de loja, ref. os dias trabalhados: ) > PIX: 422.164.908-90 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jenny Oliveira Santos Ramos (auxiliar de loja, ref. os dias trabalhados: 16/04 - ) > PIX: 422.164.908-90 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Joana D''arc (ref. 07/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Joana D''arc (ref. 27/02 - 04/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Joana D''arc Elvira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Joana D''arc Elvira (diferença, ref. São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Joana D''arc Elvira Jesus Alves Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Joana D''arc Elvira Jesus Alves Araújo > PIX: 239.961.918-80 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jocicreide Barbosa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jocicreide Macedo Barbosa Santos (ref. 03/02 - ) > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jocicreide Macedo Barbosa Santos > (diferença ônibus ~ ) > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: João Paulo Sirassava Guapo (ref. 22/05-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Julian Zaninie de Almeida > PIX: (11) 9 3216-9958 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Julian Zaninie de Almeida > PIX: (11) 9 3216-9958 (celular) - ref.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Julian Zaninie de Almeida > PIX: (11) 9 3216-9958 (celular) - ref. 04/03 ~', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Julian Zaninie de Almeida > PIX: (11) 9 3216-9958 (celular) - ref. 20/02 ~', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Julian Zaninie de Almeida > PIX: (11) 9 3216-9958 (celular) - ref. 24/02 ~', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kamilly Francisco Basílio (divulgadora, ref. o dia trabalhado ) > PIX: (11) 9 7568-4640 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kathleen dos Santos Campos (diferença ônibus ~ - ) > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kathleen dos Santos Campos (ref. 01/10 - ) > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kathleen dos Santos Campos (ref. 19/09 - ) > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kathleen dos Santos Campos (ref. 21/09 - ) > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kathleen dos Santos Campos > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kathleen dos Santos Campos > PIX: kathleendossantoscamposkety@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine (ref. ida ~ Mauá) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves Araújo (ref. 19/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (RIO PEQUENO) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (SUZANO I) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (moedas do escritório) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (ref. - ida/volta no laboratório) > PIX: (11) 9 3452-1707 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (ref. - ida/volta no laboratório) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (ref. 05/07 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (ref. 19/04 > ida/volta e > ida no laboratório) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo (ref. 26/06 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > (diferença ônibus ~ - ) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > PIX: (11) 9 3452-1707 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ SUZANO I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Kayllaine e Nicolly (ref. - ida/volta laboratório Style) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Keren Anacleto de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Keren Anacleto de Souza (ref. dias trabalhados 01/10 a )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lara Silva Wingeter De Souza (adiantamento, ref. 02/03 ~ 07/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lara Silva Wingeter de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lara Silva Wingeter de Souza (ref. 02/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lara Silva Wingeter de Souza (ref. 09/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lara Silva Wingeter de Souza (ref. 16/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias (ref. 04/04 - ida para São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo (diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo (ref. 06/2023 - diferença para as lojas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. 02/07 e ~ Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. 16/03 - ~ São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. 16/08 - ~ São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. 21/05 e ~ Rio Pequeno) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. ~ São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) >> (diferença, ref. ~ São Mateus) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) ~ Ida para Mauá >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Larissa Dias Fernandez Cardoso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Letícia Morais Domingos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Letícia Morais Domingos (adiantamento) > PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lineth Saraing (ref. 24/11 e ) - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campo (adiantamento, ref. 06/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos (descontado depositado a mais na 2° parc. do 13° salário)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos (diferença a pagar referente até o dia )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos > (diferença ônibus ~ - ) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail) - ref. > Campanha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (ref. 01/11 a )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Soares da Silva (ref. 10/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Soares da Silva (ref. 17/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Luana Soares da Silva (ref. 24/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Lucas S. Cornélio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (dinheiro de Mauá)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (dinheiro de PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (dinheiro de Perus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (dinheiro de Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (dinheiro de Suzano I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (dinheiro de São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Cristina de Jesus (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW());
