INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'SALÁRIO: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF) ~ (diferença a pagar)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Isabel Moura da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Isabel Moura da Silva (ref. 08/02-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria da Conceição Ramos de Moura (diferença a pagar, ref. MAR/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria da Conceição Ramos de Moura (diferença a pagar, ref. adiantamento salarial MAR/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria da Conceição Ramos de Moura > PIX: 102.281.264-52 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Melissa Ketelyn Sanches de Oliveira (divulgadora, ref. o dia trabalhado ) > PIX: ketelynmelissa196@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes (SUZANO II) > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes (SÃO MATEUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes (SÃO MATEUS) > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Miriam Ferreira Sanches', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva (MAUÁ) > PIX: (11) 9 5328- 7646 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) DN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicolas Coutinho da Silva > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicollas Henrique Souza dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicollas Henrique Souza dos Santos (referente os dias trabalhados, período 01/08-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Nicollas Henrique Souza dos Santos (referente os dias trabalhados, período 16/05-31/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Normando Ferreira da Silva Filho (ref. 26/08 - ) > PIX: (13) 9 8599-1407 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Pedro Henrique (ref. 1 dia trabalhado > ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Pedro Henrique Armiliato dos Santos (divulgador, ref. os dias trabalhados 07/01 - ) > PIX: silped213@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Pâmela de Oliveira Santos (divulgadora, ref. 27/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rafaela > PIX: krafaela409@gmail.com (e-mail) > (ref. dias trabalhados 23/11 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rayane Oliveira Ambrosio (adiantamento)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rayane Oliveira Ambrosio (divulgador)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rayssa Santos (divulgadora, ref. 04/08~07/08) > PIX: anamarsbc@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Robson (adiantamento, ref. 03/02 e 04/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Robson Luiz Alves dos Reis', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rogério Augusto Cruz (divulgador, ref. o dia trabalhado ~ teste: ) > PIX: (11) 9 6474-1528 (celular - Leonardo Luiz)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rogério Martins dos Santos - PIX: 306.348.488-10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rosana Lucas dos Santos (divulgadora, ref. os dias trabalhados - ) > PIX: 182.894.078-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rosangela Aparecida Dejane Felisbino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Rízia Sulamita Nakashima Lopes (auxiliar de loja, ref. os dias trabalhados 17/09 - ) > PIX: (11) 9 5947-5520 (celular) -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Samuel Henrique da Silva (ref. 07/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Sandy Cristina da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Sandy Cristina da Silva Santos (ref. 06/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Sarah Beatriz (ref. 01/08, 27/08 e ) > PIX: (11) 9 8799-3224 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Stephane Soares Lima', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Stephane Soares Lima (Ref. dias trabalhados 30/08 e 31/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Suellen Zancan Silva (divulgadora, ref. 12/07 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Tamirys Gabriele (divulgadora, ref. os dias trabalhados 04/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thais de Sousa Aliona (divulgadora, ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Vinicius Andrade SIqueira (ref. 14/05 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Vinicius Andrade SIqueira > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Vinicius Andrade Siqueira > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Yuri da Silva Yuki > PIX: (19) 9 9127-3092 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Yuri da Silva Yuki > PIX: yukicomercial@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Yuri da Silva Yuki > PIX: yukicomercial@gmail.com (e-mail) ~ MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Yuri da Silva Yuki > PIX: yukicomercial@gmail.com (e-mail) ~ RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Yuri da Silva Yuki > PIX: yukicomercial@gmail.com (e-mail) ~ SUZANO 1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Thiago Yuri da Silva Yuki > PIX: yukicomercial@gmail.com (e-mail) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Vanessa Mendes da Silva (ref. campanha avulsa em Perus: ) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail) - ref. > Campanha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Vanessa Santana Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Vitória Regina Nunes da Conceição', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Vivian Maria Ferraz Reis > PIX: 489.718.278-66 (CPF) > (referente os dias trabalhados, período 03/10-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Wellen Santos Silva (divulgadora, ref. os dias trabalhados 10/07-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Wevilly de Souza Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Wevilly de Souza Fernandes Líbano (ref. campanha avulsa em Perus: ) > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Yasmin Castilho Ferreira da Silva (auxiliar de loja, ref. os dias trabalhados ~ teste: 19/02 - ) > PIX: yasmincastilho2208@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Yasmin Emanuela Costa de Souza > PIX: costacarina148@gmail.com (e-mail) - (ref. dias trabalhados 18/10 e )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Yasmin Emanuela Costa de Souza > PIX: costacarina148@gmail.com (e-mail) > (ref. dias trabalhados 01/11 e )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Yasmin da Silva Costa dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Yasmin da Silva Costa dos Santos (ref. 01/12 a 05/12)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANDREMI BAZAR E PAPELARIA LTDA: Caneta esférica e ficha pautada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANDREMI BAZAR E PAPELARIA LTDA: Fio de nylon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANDREMI BAZAR E PAPELARIA LTDA: Papel sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANDREMI BAZAR E PAPELARIA LTDA: Recibo comercial', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANDREMI BAZAR E PAPELARIA LTDA: Sacolas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANTA FÉ LANCHONETE: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANTA HELENA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANTA HELENA DOCE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANTA HELENA DOCES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANTA HELENA: Pães', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SANTA REFEIÇÃO: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SAQUINHO PARA ÓCULOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SASAKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SASAKI COMPONENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SASAKI COMPONENTES ELETRÔNICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SBX MAUA COMERCIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SECULLUS BIJOUX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA - ADIANTAMENTO SEGURANÇA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA - CAIXINHA SEGURANÇA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA - PAGAMENTO PARA SEBASTIÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA - PAGAMENTO SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA - SEGURANÇA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA: Sebastião Luiz Rosa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA: Sebastião Luiz Rosa - PIX: 014.543.178-92 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA: Sebastião Luiz Rosa > PIX: 014.543.178-92 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURANÇA: Sebastião Luiz Rosa > PIX: 014.543.178-92 (CPF) - VENTILADORES (Ventisol/Delta Premium)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEGURO RESIDENCIA 05/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEIJUN YAMAUCHI PAPELARIA - ME: Super bonder', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEIJUN YAMAUCHI PAPELARIA ME: Envelopes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEIJUN YAMAUCHI PAPELARIA ME: Recibo comercial > Mike Rodrigues Gomes > PIX: (11) 9 4588-8760 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEM PARAR - PIX ENVIADO - CP :23114447-SEM PARAR INSTITUICAO DE PAGAMENTO LT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEMAR SUPERMERCADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SEREIA PERUS COMERCIO DE PRESENTES LTDA: Canetas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERGIO MOTTA MARQUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação das câmeras', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação das câmeras 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação das câmeras 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação das câmeras 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação das câmeras 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação das câmeras 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação dos alames', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Entrada - Instalação dos alarmes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 1/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 1/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 2/6 - 11) 9 5139-6200', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 2/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 3/6 - 11) 9 5139-6200', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 4/6 - 11) 9 5139-6200', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 5/6 - 11) 9 5139-6200', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras - Parcela 6/6 - 11) 9 5139-6200', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Instalação das câmeras 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Monitoramento da loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Monitoramento da loja (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Monitoramento da loja suzano II', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIP SERVIÇOS P LTDA ME: Monitoramento do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SERVIÇOS DE MARKETING: Investimento no Instagram ~ FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHIBATA COMERCIO E ATACADO: Água sanitária e leite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOP KID''S MAGAZINE LTDA: Balão liso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOP KID''S MAGAZINE LTDA: Balão liso, Kit para balão e sacola', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOP KID''S MAGAZINE LTDA: Balões', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOP KID''S MAGAZINE LTDA: Bexigas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOP KID''S MAGAZINE LTDA: Bexigas e sacolas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOP KID´S MAGAZINE LTDA: Amendoim, balão, sacola e suco em pó', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SHOPPING UTILIDADE S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL (ref. abr-2021 ~ 1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL (ref. abr-2021 ~ 2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL (ref. mar-2021 ~ 1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL (ref. mar-2021 ~ 2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL - Parcela 1/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL: Parcela 10/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SIMPLES NACIONAL: Parcela 9/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISPAG PIX RECISMEC COM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - MAQEXTREME COM INFORMATICA LT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - NEXTAR TECNOLOGIA DE SOFT LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - OMIE EXPERIENCE LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - OMIE EXPERIENCE LTDA: TREINAMENTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SISTEMA - REGISTRO PONTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SLI INFORMÁTICA CARTUCHOS E TONER: CARTUCHO COMPATÍVEL DE TONER TN1060', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SMT COMERCIO: Pilha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SO BLOCOS COMERCIO E SERVICOS OTICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SODIMAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOFT PEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOFT PEL PAPELARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOFT PEL: Glossy 50F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLAR PARA BRINDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 21341 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 21341 - ref. - diferença) > PIX: 65.532.707/0001-94 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ) - ref. OS 11454', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ) - ref. OS 11468', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ) - ref. OS 11664', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ) - ref. OS 11682', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ) - ref. OS 11898 (1° par)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato (Cód. cliente: 24652 - ref. ) > PIX: 65.532.707/0001-94 (CNPJ) - ref. OS 11898 (2° par)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SOLÓTICA: Lentes de contato > PIX: 65.532.707/0001-94 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STA CLARA LINGERIE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STEAVNEV LOM. E SERV. DE INFO LTDA - ME: 100 folhas sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS (diferença, ref. 16/05) > PIX: 43.849.253/0001-47', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > (foi abatido da lente 1.67)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS ,3744', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 10041, 10044 e 10045', 'juridica', NULL, True, NOW(), NOW());
