INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'SALÁRIO - NATHALIA CAROLINA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - PAGAMENTO DE HORA EXTRAS: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - PAGAMENTO DE MULTA: ARIANE GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - PAGAMENTO DE SALÁRIOS: KAILANE CRISTILLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - PAGAMENTO PARA CRISTIANE DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - PAMELA GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - RECEBIVEIS DE VENDA - CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO 1/2: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO DIVULGAÇÃO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ADRIANA GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ALDENIR PAULA (DIFERENÇA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ALESSA BISPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ALESSA BISPO ROSA (DIAS TRABALHADOS 08/04 A 14/04)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ALINE DA CRUZ SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ANDREIA PAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: APARECIDA NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ARIANE GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ARIANI DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: DIEGO FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: EVELINE RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: JHENNIFER XIMENES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: JOCICREIDE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: KAILANE CRISTILLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: MARIA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: MATHEUS RAFAEL (REF. AOS DIAS TRABALHADOS PERÍODO 28/05 A 31/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: NATHALIA CAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: PAULO CÉSAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: RAQUEL RONCONI (DIAS TRABALHADOS 05/04 A 08/04)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: VICTOR CURY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SALÁRIO: ZAYNE CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - TIELLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - VALE TRANSPORTE: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - VALE TRANSPORTE: MARIA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ZAINE CORDEIRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Adriana Cristina Oliveira da Silva (divulgadora, ref. - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Adriane Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Adriane Dias Fernandes Cardozo (ref. 21/12-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Alessandra Barbosa Leme', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Alessandra Barbosa Leme (meio período)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Araújo Silva (ref. 25/02-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha (SUZANO I) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha (diferença a pagar)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha (férias vendida) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF) - PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF) - RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF) - SUZANO 1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF) - SUZANO 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF) - moedas escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline Cristine Ferrari (referente os dias trabalhados)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ana Carolina Bandeira Vital dos Santos > PIX: bandeiravitaldossantosa@gmail.com (e-mail) - ref. 15/02 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ana Clara Faria Lamounier (ref. os dias trabalhados 15/09 - ) > PIX: 518.356.358-65 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ana Clara Silva Kretschmer (divulgadora, ref. 03/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ana Cristina Rodrigues Amancio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ana Cristina Rodrigues Amâncio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ana Paula Aparecida Moreira da Silva Yuki > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Anderson de Jesus Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Anderson de Jesus Souza (ref. os dias trabalhados 01/09 a )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Andreia Firmino de Souza (divulgação, ref. 08/02 a 15/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Anna Beatriz de Camargo Lorena', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Anna Beatriz de Camargo Lorena (ref. ao dia trabalhado )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 01/04 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 01/05 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 01/07 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 01/08 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 01/09 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 01/10 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 02/06 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano (ref. 22/04 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Beatriz Silva de Matos Araújo > (auxiliar de vendas, ref. os dias trabalhados 16/12 - ) PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Beatriz Silva de Matos Araújo > (dia trabalhado, ref. ) PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Bianca Raquel da Silva Santos (ref. os dias trabalhados, período 22/06-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Bruna Dias de Souza > PIX: (11) 9 6088-1210 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Bruno Henrique Simão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Camila Faccin Vieira (ref. 19/04 - ) > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Carolina Beatriz dos Santos Serafim (auxiliar de loja/vendas, ref. os dias trabalhados 18/02 - ) > PIX: (11) 9 3387-4351 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Carolina Rodrigues Da Silva (auxiliar administrativo, ref. 19/08 - ) > PIX: carolinarodrigues297@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Carolina Rodrigues da Silva (auxiliar administrativo, ref. 21/08 - ) > PIX: carolinarodrigues297@gmail.com (e-mail) - SUZANO 1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Carolina Rodrigues da Silva (auxiliar administrativo, ref. 23/09 - ) > PIX: carolinarodrigues297@gmail.com (e-mail) ~ SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Claudia Maria Teixeira (divulgadora, ref. 22/09 ~ > meio período) > Agência: 0659 I Conta corrente: 00037293-7 > CPF: 306.706.708-80', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (adiantamento da recisão)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 09 dias trabalhados) > PIX: 4541adc2-aa91-42c3-9d7f-1bc5112d5e89 (chave aleatória) - Giovanna Mello de Camargo > INTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 1 dia trabalhado > ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 1 dia trabalhado > ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 2 dias trabalhados > 09/04 e ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 2 dias trabalhados > 16/07 e ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 2 dias trabalhados > 23/04 e ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 2 dias trabalhados > 24/03 a 25/03) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 21/03 e 22/03 - dias trabalhados) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 03/03 a 08/03) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 06/05 - ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 15/04 - ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 17/02 a ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 18/03 a 20/03) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 19/05 - ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 3 dias trabalhados > 31/03, 03/04 e ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 4 dias trabalhados > 10/02 a ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus (ref. 4 dias trabalhados > 22/07 a ) > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cleberson Ribeiro de Jesus > PIX: ribeirocleber704@gmail.com (e-mail) - Manutenção nas lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Cristiano Domingues Avalo Filho > PIX: 243.498.708-73 (CPF) > (referente os dias trabalhados, meio-período 23/10-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Daniel Nunes de Carvalho (ref. 23/12-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Davi Pereira Gonçalves Mônaco (ref. ) >PIX: diasroselaine01@gmail.com (EMAIL) <', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Diego do Nascimento (divulgação, referente os dias trabalhados 25/01 e 26/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Dyenifer Nicole Brandão da Rocha (ref. 1 dia trabalhado > ) > PIX: (15) 9 9773-6533 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Débora Lemes Siqueira (divulgadora, ref. os dias trabalhados 01/02 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Débora Lemes Siqueira (divulgadora, ref. os dias trabalhados 22/01 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Débora Lemes Siqueira (divulgadora, ref. os dias trabalhados ~ teste: 19/01 - ) > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Débora Lemes Siqueira > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Eduarda Andrade Ferreira (divulgadora, ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Elaine Cristina da Silva (divulgadora, ref. os dias trabalhados ~ teste: 20/03 e ) > PIX: (11) 9 3037-0304 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Elaine Cristina da Silva (divulgadora, ref. os dias trabalhados: 22/03 - ) > PIX: (11) 9 3037-0304 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Eliana Savoia > PIX: (11) 9 4714-9764 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Estefany de Oliveira Penha (divulgadora, ref. o dia trabalhado ~ teste: ) > PIX: epenhaoliveira@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Felipe Arruda Lellis Bentoglio (divulgador, ref. 01/07~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Felipe Roger Miranda > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF) - DN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Giovanna Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Giovanna Mello de Camargo > PIX: (11) 9 5491-5739 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Igor Nascimento Medeiros', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Iris Roseno Pereira da Silva (referente os dias trabalhados, período 24/07-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Isabela Santos Silva Alves (ref. os dias trabalhados, período 22/06-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Isabelle da Silva Sousa (divulgadora, ref. os dias trabalhados ~ teste: 08/03 e ) > PIX: (11) 9 8552-3110 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Isabelle da Silva Sousa (divulgadora, ref. os dias trabalhados: 11/03 - ) > PIX: (11) 9 8552-3110 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Jenny Oliveira Santos Ramos (auxiliar de loja, ref. os dias trabalhados: ) > PIX: (11) 9 6416-8685 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Jenny Oliveira Santos Ramos (auxiliar de loja, ref. os dias trabalhados: 18/04 - ) > PIX: (11) 9 6416-8685 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Joana D''arc Elvira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Joana D''arc Elvira (estorno de diferença de salário) > PIX: 239.961.918-80 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Joana D''arc Elvira (ref. diferença salarial)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Joana D''arc Elvira Jesus Alves Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Joana D''arc Elvira Jesus Alves Araújo > PIX: 239.961.918-80 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: João Paulo Sirassava Guapo (ref. 22/05-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Julian Zaninie de Almeida > PIX: (11) 9 3216-9958 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Juliana Reis Honorato (divulgador)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kamilly Francisco Basílio (divulgadora, ref. o dia trabalhado ) > PIX: (11) 9 7568-4640 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Katherine de Lima Santos (ref. a dois dias trabalhados)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kathleen dos Santos Campos > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Katrelly (referente a dois dias trabalhados)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Katrelly Eullly Barbosa dos Santos Leite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo (RIO PEQUENO) > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ SUZANO I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Keren Anacleto de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Keren Anacleto de Souza (ref. diferença salarial)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kethelyn Miranda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kethelyn Miranda (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Kethelyn Miranda (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Lara Silva Wingeter de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Larissa Dias Fernandes Cardozo (ref. diferença salarial - set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Laura Andreza Costa Pereira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Letícia Morais Domingos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Letícia Morais Domingos (ref. o dia trabalhado )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Lineth Saraing (teste, ref. 24/11 e ) - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail) - ref. > Campanha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Luana Soares da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Lucas S. Cornélio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Marcela da Silva Lemes (divulgadora, ref. 27/10 ~ ) > PIX: (11) 9 4059-9162', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Marcelo Narcisio Santos (divulgador, ref. 27/07 e )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Marcelo Narciso Santos (divulgador, ref. dias trabalhados)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de Mauá)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de Perus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de Suzano II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de Suzano)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Cristina de Jesus (dinheiro de São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Eduarda Santos Brandão (ref. 4 dias trabalhados em Perus - 11/08, 14/08, 15/08 e ) > PIX: (11) 9 8514-1871 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW());
