INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'PAgto FEsta - PIX TRANSF AMANDA 08 08', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAgto Opto Campanha - PIX ENVIADO - VANESSA RODRIGUES SEIDLE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDESTAL, BENJAMIN E PEN DRIVE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDREIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDREIRO: Manutenção da loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - 04/02 13:03 NETPARK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - 21/12 15:37 NETPARK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - 27/11 16:41 ESTACIONAMENTO EGN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - ANCHIETA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - ARUJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - BARUERI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - CASTELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - COMPRA CARTAO - NO ESTABELECIMENTO ECOPISTAS ITAQUAQUECETU BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - COMPRA CARTAO - NO ESTABELECIMENTO SPMAR SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - DUTRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - GASTOS PARA PAGTO FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - ITAQUACETUBA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - OSASCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - PEDÁGIO: ATALAIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - PEDÁGIO: DANIELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - RAPOSSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PEDÁGIO - REGIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PELICULAS CELULAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PELÍCULA DE CELULAR - LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PERFUMARIA TAKARA: ACETONA FARMAX 80ML', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PERFUMARIA TAKARA: ESMALTE BELLA PERO ONIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PERFUMARIA TAKARA: ESMALTE LUDURANA BASE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PERFUMARIA TAKARA: LIXA DE UNHA (PASSAGEM)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PERFUMARIA TAKARA: Lixa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PERFUMARIA TAKARA: Sabonete líquido', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PET CENTER SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIMENTA VERDE ALIMEN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PINTOR: Francisco Hélio Nogueira Arcanjo - Parcela 1/2 > PIX: (11) 9 8211-8927 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PINTOR: Francisco Hélio Nogueira Arcanjo - Parcela 2/2 > PIX: (11) 9 8211-8927 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PINTURA DA LOJA: Felipe Roger Miranda (ref. ) > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 04/2021 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 04/2021 (1° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 04/2021 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 04/2021 (2° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 11/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 11/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 12/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 12/2022 (Multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional - 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 01/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 01/2023 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 01/2023 - Parcela 7/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 01/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 01/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 01/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 02/2023 - Parcela 10/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 02/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 02/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 02/2023 - Parcela 9/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 02/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 03/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 03/2023 - Parcela 12/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 03/2023 - Parcela 13/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 03/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 03/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 04/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 04/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 10/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 11/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 2/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 24/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 26/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 27/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 28/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 29/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 3/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 30/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 31/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 32/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 33/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 34/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 35/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 36/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 37/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 38/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 39/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 4/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 40/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 41/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 42/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 43/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 44/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 45/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 46/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 47/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 48/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 49/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 5/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 50/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 51/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 52/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 53/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 54/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 55/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 56/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 57/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 58/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 59/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 6/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 60/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 7/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 8/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2021 - Parcela 9/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 05/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 06/2021 - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 06/2021 - Parcela 11/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 06/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 06/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 14/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 15/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 16/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 17/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 18/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 2/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 3/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2022 - Parcela 5/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 07/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 13/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 14/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2021 - Parcela 15/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 08/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 09/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 09/2022 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 09/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 09/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 10/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 11/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 11/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 12/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIS: Simples Nacional 12/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX ENVIADO INTERNO - 00019 0070615551 GILBERTO JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX QRS KAMIX FOODS31/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX QRS Uber23/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX RECEBIDO - NICOLAS COUTINHO DA SILVA (abateu no acordo rescisório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ANA PAU01/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ANA PAU12/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ARIANE 16 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ARIELLI20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Andre B17/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Ariane 20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF BARBARA09/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF BARBARA13/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF BRUNA O21/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF CAROLYN18/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF CAROLYN20/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF CELIA C12/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Carolin27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Clebers20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Clebers21/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF DAIANE 20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF DALILA 28/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ELIANA 13/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ELIANA 29/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF GABRIEL10/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF GABRIEL13/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF GIGI C 25/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF GILBERT30/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF GIOVANN13 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Gilbert14/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Gilbert15/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Gilbert21/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann09/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann14/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann15/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann19/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann20/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Giovann30/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ISABELL20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF JEFERSO23/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF JOSE RO13/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF JOSIE D11/02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF JOSIE D13/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF JULIANA27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Joana D16/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Joana D20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Joyce C10/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Joyce C13/02', 'juridica', NULL, True, NOW(), NOW());
