INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 18/03 09:33 00047959503850 LDIA DA SIL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 20/03 14:16 00023944157893 FELIPE HENR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 20/03 18:59 00057360723868 NOEMIA FERR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 24/03 17:25 00024065649838 EZIONI SANT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 25/03 12:57 00018695635813 MARCOS CARV', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 25/03 14:40 00009367050780 GISELE TAVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE - 27/03 17:14 00014533990894 NEUMA DE CA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE01/04 09:48 00026807990898 DEBORA GUTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE01/04 10:44 00011441558861 EDEMILSON D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE01/04 17:52 00053826580800 GUILHERME H', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE04/04 10:27 00007351939837 NANCY BICEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE04/04 16:01 00039487755837 RAYSSA CRIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE04/04 16:52 00049337404885 GABRIEL HEN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE05/04 13:47 00017581819825 ELIZABETH A', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX-RECEBIDO QR CODE05/04 17:58 00005254729325 FRANCISCA V', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - ANGELICA LIMA PURGATO ZEFERINO 43059781800', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - ASSAI ATACADISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - AUTO POSTO PARQUE PIQUERI LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - AUTO POSTO RODOANEL LESTE LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - BG LESTE ALIMENTOS LTDA almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - BOIZAO EVENTOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - CONDOR PET CENTER ITAQUA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - E V SILVA RESTAURANTE EIREL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - ESTACIONAMENTOS EPARK EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - FACEBOOK ADS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - FARNEZI ADMINISTRACAO DE POSTOS LTDA EPP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - GRAN SUZANO AUTO POSTO LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - IFOOD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - IFOOD.COM AGENCIA DE RESTAURANTES ONLINE S.A.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - JOSE TOSI NETO SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - KIZUI SUSHI LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - LALAMOVE TECNOLOGIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - LALAMOVE TECNOLOGIA - REUNIÃO GERENCIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - LAUNCH PAD TECNOLOGIA, SERVIÇOS E PAGAMENTOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - MAGAZINE LUIZA MARKETPLACE', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 7/13 (1000 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - OFICIAL DE REGISTRO CIVIL P. N. I. TUTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - ON BRASIL COMERCIO DE ALIMENTOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - PICANHA NOBRE CASA DE CARNES E MINIMERCADO EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - PIX MARKETPLACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - SANTA HELENA DOCES E PAES LTDA EPP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - SK SUPERMERCADOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - SR9 - ESTACIONAMENTO LTDA - ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX ENVIADO - SUZURAN BOMBONIERE LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - 47.078.060 RAFAELA MENDES JARDIM DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - 49.628.268 ROBERTO CORREIA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - 49.771.050 PAULO BARBOSA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - 53.503.252 TAINA SOUZA ANDRADE DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ADENILSON SOARES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ADRIANA APARECIDA BRAZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ADRIANA GOMES DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - AIRTON ROCHA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALDIMEIA PEREIRA MENDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALERCIO SERAFIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALESSANDRA GIRARDI DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALESSANDRA SIMOES DE JESU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALESSANDRA SIMÕES DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALEX GONCALVES DE SOUZA 30487198816', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALEX SANDER DA SILVA ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALEXANDRA INEZ ALENCAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALEXSANDRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ALINE SANTANA DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - AMALIA RANGEL DE LIMA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - AMANDA DA SILVA NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANA CAROLINA GARCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANA CLEIA VIEIRA GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANA LUCIA DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANDERSON JAQUES DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANDERSON RAFAEL DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANDREA ALVES LIMA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ANDREILTON SANTOS DE AMORIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ARNALDO BARBOSA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ATILLA COSTA MATOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BARBARA HELENA SOARES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BEATRIZ DE LIMA FERRARI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BIANCA CARDOSO BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BRENO NEVES SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BRUNA FERNANDA NORONHA BARBOZA NONATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BRUNA TOLEDO RODRIGUES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BRUNO LEONARDO SOUZA DE ARRUDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - BRUNO OLANDINO FOOK SHIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CAMILA BARBOSA ALBINO CHARDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CAMILA DA CRUZ CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CAMILLI NICOLI CUER RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CARINA CORREA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CARINE ALMEIDA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CARLINHOS FERREIRA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CASA DO XAVIER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CELI RAMOS DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CESAR AUGUSTO CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CIBELE DE PAULA MENDONÇA MORALES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CICERO BENTO DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CICERO FRANCISCO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CINTIA VANESSA MAIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CLAUDEMBERG DA SILVA MACIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CLAUDIONOR DE JESUS GOES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CLEBER DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CLEITON ANGELO NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CLEONICE ROCHA MORAIS FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CRISLAINE SANTANA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CRISTIANE DE CASSIA BUKE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - CRISTIANE PEREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DANIEL MAXUEL LIMA MARCONDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DARCI ALICE VICENTINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DAVID QUISPE SOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DEBORA CONDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DEISE CRISTINA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DENIS APARECIDO PEREIRA CRUZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DENISE MARIA DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DEUSDETE GOMES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DIEGO PEREZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DIOGO FERREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DIRCE GABRIELLE RIBEIRO SILLOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DIVA DE OLIVEIRA BAHIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DOUGLAS LOPES ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DOURIVAL CLEMENTE DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - DÉBORA SILVA DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDINALDO SEBASTIAO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDIVALDO APARECIDO VIANA MENEZES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDNEUSA APARECIDA EVARISTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDUARDA FERNANDA AMÂNCIO VALEO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDUARDO APARECIDO DE HOLANDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDVALDO DA SILVA MACEDO 28181555848', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDVAN ARAUJO DE PAIVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EDVANIA CARVALHO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELAINE GOMES DE MORAES CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELENITA DIAS DOS SANTOS JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELIANA ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELIANA SAVOIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELIAS ZEFERINO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELIEL DUARTE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELISANGELA TEIXEIRA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELIZANDRA DIAS FERREIRA MONTEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELIZÂNGELA ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELLEN CRISTINA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ELZA DOS REIS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EMERSON ROBERTO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ERICA TAMIRIS ROSA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ERICH CRISTIANO RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ERICH CRISTIANO RODRIGUES JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ERIVALDO PORFIRIO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ESTELITA QUARESMA DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EUDES CONCEICAO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EVERALDO SERAFIM CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - EZEQUIEL PEREIRA SOLEDADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FABIANA ALVES VERISSIMO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FABIANA DE ALMEIDA LIMA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FATIMA AUGUSTA DA SILVA REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FELIPE CARRIÃO PORTELLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FERNANDA APARECIDA ROCHA MIYAWAKI DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FERNANDO JOAO PAGNANI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FRANCINE MARCONDES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FRANCISCO DALTON DE ARAUJO OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - FRANSIMAR APARECIDO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GABRIEL LUIZ HOMAN LEMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GABRIEL MATEUS DE JESUS HODEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GABRIELLA MARTINS TORISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GEOVANNA ALMEIDA FELIZARDO DE PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GILEIDE COLOIA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GILMAR CESAR DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GILMAR JOSE DE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GILMAR LOPES MARINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GILVANILSON JACINTO DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GISELE MOURA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GRAZIELA CRISTINA VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - GUSTAVO ANDRADE SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HEITOR GROIDE MAGALHAES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELEN LUCINDA JANUARIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELEN MARIA CARVALHO VENCESLAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELENA CRISTINA OLIVEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELENA SOARES DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELIO NUNES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELLEN SILVA DE ANDRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HELLEN VITORIA G S LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HENRIQUE LIMA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - HINGLISNEY DA SILVA FERNANDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - IMACULADA DA CONCEICAO APARECIDA PIRES DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - INGRID R C CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - IRACELO ALVES FEITOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ISABEL DE OLIVEIRA MOREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ISABELA DE OLIVEIRA PIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ISAIAS RIBEIRO DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - IURAPUAM LUIZ DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - IVÂNIA PEREIRA NEVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - IZALTINA JULIA DOS S BARBOZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JAILTON FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JAIME RODRIGUES XAVIER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JANAINA DAIANE PINHEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JAQUELINE DOS SANTOS MEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JENIFFER VITÓRIA MENDES SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JESSICA JAINE MOREIRA DE SOUZA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOANA PAULA LOPES TAVARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOAO SANTANA DE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOCICREIDE MACEDO BARBOSA', 'juridica', NULL, True, NOW(), NOW());
