INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'PIX TRANSF KAMIX F31/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LAURO A27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LETICIA20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LILIAN 07/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LUCAS D09 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LUCIANA20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LUCIANE28/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF LUCIENE20/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Leticia29/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Ligia M02/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF MARIA V07 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF MARIA V11 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF MARINA 27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF MATHEUS07/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF MAYARA 07/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Mateus 12/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Mateus 18/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF Mateus 30/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF NATHALI12/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF NATHALI26/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF PATRICI22/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF RAFAEL 27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF RENATA 10/02', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF ROBERTO24/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF STYLUS 31/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF TATIANA13 01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF TMO C V15/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF VITORIA27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF WALDEMI19/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF WILLIAN27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PIX TRANSF isabel 13/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PLANETA AGUA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PLAQUETAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS (SEM número)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 10097 e 10111', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 10180', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 10574', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 1062', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 1066 (122)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 3712', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 4652', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 4699', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 4779', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 9768', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 9843', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS 9966', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 10164 e 10180', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 10190 e 10366', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 10194,. 10199 e 10207', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 10219 e 10313', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 10321 e 10366', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 10332, 10333 e 10408', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 3741', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 3753', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 4519, 4605, 4606 e 4618', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 4537', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 4652, 4680 e 4689', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 4682 e 4701', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 4692 e 4695', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 6925', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 6964 e 6965', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 9695, 9755 e 9876', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'POLYLUX - QUICK OTICA ACESSORIOS LTDA > PIX: 45.422.708/0001-79 (CNPJ) - ref. OS''s 9859, 4472, 4475 e 4500', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PONTO DO DOCE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PONTO DO DOCE: Guloseimas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTAL DE POA AUT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 1/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 10/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 11/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 12/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 2/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 3/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 4/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 5/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 6/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 7/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 8/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PORTO SEGURO: Seguro fiança - Parcela 9/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRARCO VERDE COM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - ARIANE GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - ARIANI DIAS FERNANDES CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ALDENIR PAULA - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ALDENIR PAULA - META SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ALINE DA CRUZ SANTOS - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ALINE DA CRUZ SANTOS - META SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ANDREIA PAES - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: EMERSON WILLIAM - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: JOCICREIDE BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: LARISSA DIAS - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: LARISSA DIAS - META SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: MATHEUS RAFAEL NASCIMENTO FERREIRA - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: MATHEUS RAFAEL NASCIMENTO FERREIRA - META SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: NATHALIA CAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: NATHALIA CAROLINA - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: NATHALIA CAROLINA - META SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ZAINE SIQUEIRA - META DIÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - BONIFICAÇÃO: ZAINE SIQUEIRA - META SEMANAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - MC DONALDS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - META BATIDA: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - META BATIDA: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - NATHALIA CAROLINA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - PAGAMENTO DE BONIFICAÇÃO: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - PAGAMENTO PARA DÍZIMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - PREMIAÇÃO: FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO - ZAINE CORDEIRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Bruno Henrique Simão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Igor Nascimento Medeiros', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Joana D''arc Elvira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Jocicreide Macedo Barbosa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Keren Anacleto de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Rosângela Aparecida Dejane Felisbino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Sandy Cristina da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO GOOGLE: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO META REF -12/08: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO META REF -12/08: Jocicreide Macedo Barbosa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO META REF -12/08: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO META REF -12/08: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PREMIAÇÃO: Dia de Mc Donald''s', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTE MORAIS FOOD: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTE MORAIS FOOD: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTES DE MORAIS FOOD: ALMOÇO - TATY E JÚNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTES MORAIS FOOD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTES MORAIS FOOD: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTES MORAIS FOOD: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRESTES MORAIS: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE > Gilberto de Camargo Silva Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE > Tatiana Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE JUNIOR -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE: Tatiana Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRO-LABORE: Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROCURAÇÃO: Óticas Taty Mello - Rio Pequeno (GIGI COMERCIO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROCURAÇÃO: Óticas Taty Mello - Suzano II (GI COMERCIO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 1033 - Aline de Santana Morais (ref. OS 1060: Lorenzo Guilherme Moreira dos Santos) > PIX: 049.033.865-89 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 1292 - Leonor de Lima de Jesus (ref. OS 1811 - Lucimar e OS 1813 - Julieta Palmeira de Lima) > PIX: (11) 9 5877-5495', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 1364 - Fabiano Borges (ref. OS 1549 - Luiz Carlos da Silva)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 1694 - Edson Souza (ref. OS 1873 e OS 1874 - Érika Souza) > PIX: 288.026.658-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 1867 - Iraildes de Souza da Silva (ref. OS 1883: Lourival Vitorino, OS 1884, Elenildes de Souza e OS 1813: Telma de Souza) > PIX: (11) 9 5388-5348 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 2238 - Vera Lucia (ref. OS 2411- Cláudia Cristina)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 2385 - Luciene Santos Rocha (ref. OS 2808 - Shayane Santos Lima, 2809 - Manoel Messias Rocha, 2810 - Kherolaynne Santos Lima)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 2616 - Edson Bernardo Leite (ref. OS 2681 - Sandra Maria Pontes Leite)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 3497 - Helen da Silva Cordeiro (ref. OS 3584 - Cícero Cândido Cordeiro)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 3714 - Tatyane Marques do Nascimento (ref. OS 3730- Marly Nunes da Silva) - Pix: 318.831.088-96', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 761 - Rita de Cássia (ref. OS 785- Ana Cláudia e OS 786 - Valdeci de Souza) > PIX: (11) 9 4829-4749', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 7789 - Edilane SantosMangueira (ref. OS 7800 - Cícero dos Santos)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 879 - Adriana Souza Silva (ref. OS 905- Gustavo Gabriel Souza da Silva Pereira) > PIX: (11) 9 6461-1556', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 914 - Viviane Oliveira Silva Fernandes (ref. OS 919: Silvana Mendes Cardoso) > PIX: (11) 9 4126-9745 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 924 - Maria Zuleide Barbosa (ref. OS 1001: Fernando de Almeida Amadeu) > PIX: (11) 9 8217-0684 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROMOÇÃO QUEM INDICA AMIGO É!: OS 973 - Neusa Paulina de Siqueira (ref. OS 974: Heidi Antonio Paulina Sassaki) > PIX: (11) 9 7296-4243 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PROTESTO: EDP BANDEIRANTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRÊMIOS - CESTA DIA DOS NAMORADOS - SORTEIO (INSTAGRAM): FABIANA CAUSIN SILVA - PARCELA 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRÊMIOS - PAGAMENTO DE PREMIAÇÃO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRÊMIOS - PAGAMENTO DE PREMIAÇÃO: KETHILYN SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PRÊMIOS - PREMIAÇÃO: TAMIRES MACIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PUPPETS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Padaria Renascer: Pão francês > Nicolas Coutinho > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Padaria Renascer: Pão francês > Nicolas Coutinho > PIX: 490.832.378-00 (CPF) Referente ao pão do dia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Padaria Santa Helena ( Pães e doces para a festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento 1/2 - decoração Dalila', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Cris da festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Giovanna', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Joana - festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Luciana - limpeza do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Mateus - transporte festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento Pães festa 14/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento cartão XP do buffet', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento cleberson', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento comissão pela festa - Giovanna', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento conta luz edp sao paulo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento conta luzedp sao paulo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de Boleto CORA PAGAMENTOS LTDA.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de Boleto CORA SOCIEDADE DE CREDITO DIRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de Boleto KONSEP CONTABILIDADE C LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de BoletoCORA PAGAMENTOS LTDA.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de BoletoCORA SOCIEDADE DE CREDITO DIRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de BoletoKONSEP CONTABILIDADE C LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de Festas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de Impostos DAS - SIMPLES NACIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de Impostos RFB-DARF CODIGO DE BARRAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de ImpostosDAS - SIMPLES NACIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento de ImpostosFGTS ARRECADACAO GRF', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento do sinal Barbára Ambiel - Festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento doces Nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento doces e bolo - Dulce Paladares', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pagamento equipe das festas dos dias 16 e', 'juridica', NULL, True, NOW(), NOW());
