INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'ALMOÇO - PRESTE MORAIS FOOD: ALMOÇO - ANDREIA, THAYSSA E YASMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD: ALMOÇO - ALINE CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD: ALMOÇO - ANDREIA LEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD: ALMOÇO - EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD: ALMOÇO - LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD: ALMOÇO - ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRESTES MORAIS FOOD: ALMOÇO FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - PRIMUS RESTAURANTE: ALMOÇO FUNCIONÁRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - RESTAURANTE ARTE DA COMIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - RPG COMERCIO DE ALIMEN S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - S L PANIFICAÇÃO E CONVENIÊNCIA LTDA: MARMITEX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - SABORES DA TERRA SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - SABORES DA TERRA: TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANEIRO: WILLIAM E ZAINE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANERO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANERO SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANERO: ALMOÇO - ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANERO: ALMOÇO - ALINE CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - TEMPERO MANERO: ALMOÇO - EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - THI VI PASTELARIA SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - VALE: ALMOÇO EM EQUIPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO - YUUKIBOX SUZANO BRA, NÃºM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO DA TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO EM EQUIPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO EQUIPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO EQUIPE: Francisca, Gislania e Wevilly', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO GIOVANNA E NICOLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Ariani Dias', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Francisca Lindineis Nascimento de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Maria Elizabeth (ref. 14/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Nicolas Coutinho da Silva Pix: nicolascoutinho9015@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Nicolly', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Stefany Rayne Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Stefany Rayne dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Taty (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Taty Mello', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Taty e Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALMOÇO: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - 148,51', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - BRENO JÚNIOR IMÓVEIS - CLÍNICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - BRENO JÚNIOR IMÓVEIS - LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - BRENO JÚNIOR IMÓVEIS LTDA: MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: SUZANO (ALUGUEL REF. PAGAMENTO À MENOR NO BOLETO DE )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: SUZANO (CONSUMO DE PAGAMENTO À MENOR REFERENTE À COBRANÇA 17375 LIQUIDADA EM 2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: SUZANO (DESCONTO DE IR)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: SUZANO (IPTU REF. PAGAMENTO À MENOR EM MARÇO E ABRIL)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - CONCEPT IMÓVEIS LTDA: SUZANO (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - NAMBU IMÓVEIS LTDA - ME: ALUGUEL - REF. ATÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - NAMBU IMÓVEIS LTDA - ME: IPTU - PARCELA 6/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - NAMBU IMÓVEIS LTDA - ME: IPTU - PARCELA 7/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - NAMBU IMÓVEIS LTDA - ME: IPTU - PARCELA 8/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL - NAMBU IMÓVEIS LTDA - ME: TAXA BANCÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL CLÍNICA - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL CLÍNICA - MAUÁ (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL CLÍNICA - MAUÁ (IPTU) > Banco: Bradesco I Agência: 2229 I Conta: 1433-8 I CPF: 690.905.488-15', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL CLÍNICA - MAUÁ (diferença, ref. 03/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (IPTU) - (NUBANK - Giovanna)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (IPTU) > PIX: 02.131.820/0001-48 (CNPJ) > SANTANDER - Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (IPTU, ref. 02/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (IPTU, ref. 03/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (ITAÚ - Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (NUBANK - Giovanna)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (multa por atraso do aluguel, ref. 01/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (multa por atraso do aluguel, ref. 02/2024) > PIX: 02.131.820/0001-48 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (multa por atraso do aluguel, ref. 09/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO (multa por atraso do aluguel, ref. 12/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO > PIX: 02.131.820/0001-48 (CNPJ) - (ITAÚ - Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO > PIX: 02.131.820/0001-48 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO > PIX: 02.131.820/0001-48 (CNPJ) > SANTANDER - Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL ESCRITÓRIO - SUZANO > PIX: 02.131.820/0001-48 (CNPJ) > SANTANDER - Junior (diferença da multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA (taxa bancária)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - MAUÁ (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - MAUÁ (IPTU) - ref. 03/2024 (diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - MAUÁ (diferença, ref. 03/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - PERUS > PIX: santos3imoveis@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (IPTU) - (ref. 14 dias)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (IPTU) - (ref. 9 dias)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (IPTU) > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (PIX) Roberto - 52.597.549/0001-09 (cnpj)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (ref. 14 dias)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (ref. 9 dias)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (taxa bancária)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO (⚠ descontar depositado a mais em janeiro/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO - JUROS POR ATRASO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (IPTU > ref. 05/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (IPTU) ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (IPTU) ~ (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (multa por atraso do aluguel, ref. 02/2024) > PIX: 02.131.820/0001-48 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (multa por atraso do aluguel, ref. 03/2024) > PIX: 02.131.820/0001-48 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (multa por atraso do aluguel, ref. 04/2024) > PIX: 02.131.820/0001-48 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (multa por atraso do aluguel, ref. 07/2025) > PIX: 02.131.820/0001-48 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I (ref. 05/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO I ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (IPTU) - (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (IPTU) > PIX: 39.794.111/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (Juros/Multas) - (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (Juros/Multas) - (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (SÃO MATEUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (taxa boleto)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (taxa boleto) - (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (taxa boleto) - (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II (taxa boleto) > PIX: 39.794.111/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SUZANO II > PIX: 39.794.111/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SÃO MATEUS (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SÃO MATEUS (IPTU) ~ (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SÃO MATEUS (IPTU) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SÃO MATEUS (taxa bancária)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ALUGUEL LOJA - SÃO MATEUS - multa Atraso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AM PM COMESTIVEIS LT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AMGRI COMERCIO DE PR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANIMAÇÃO (ref. ) ~ Perus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANTENAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim - Parcela 1/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim - Parcela 2/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim - Parcela 3/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 256.255.908-85 > Parcela 10/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 256.255.908-85 > Parcela 5/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 256.255.908-85 > Parcela 6/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 256.255.908-85 > Parcela 7/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 256.255.908-85 > Parcela 8/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 256.255.908-85 > Parcela 9/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ANUIDADE CLIENTE: Marcos Luiz Serafim > PIX: 44 > Parcela 4/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AOYAGI COMERCIO DE MATERIA CREDENCIADORA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AOYAGI COMERCIO DE MATERIAIS CREDENCIADORA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AOYAGI COMERCIO DE MATERIAIS CREDENCIADORA: Interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AOYAGI COMERCIO DE MATERIAL CREDENCIADORA: Papel interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AP MAX POWER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'APARECIDO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'APOLLO GRILL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARCO VERDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARCO VERDE COM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO > Nicolas Coutinho > PIX: 490,832,378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Caderno de recado > Nicolas Coutinho > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Caixa de caneta, caixa de grampo, fita adesiva e saco para presente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Folha de sulfite > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Folha sulfite (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Folha sulfite > Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Itens para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Itens para o escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Itens para o escritório e lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO LTDA: Papel sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMARINHOS FERNANDO: Grampos > Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ACETATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ANDRÉ (FAST): COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ANDRÉ 1/2: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ANDRÉ 2/2: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - COMPRA DE SOLARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - FAST COMPANY ARMAÇÕES E LENTES LTDA 1/4: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - FAST COMPANY ARMAÇÕES E LENTES LTDA 1/4: COMPRA DE ARMAÇÕES - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - FAST: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - FLORENCE4111 (PREÇO UNITÁRIO )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ROSE 1/2: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ROSE 2/2: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ROSE: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - ROSEMARE M. SILVA: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - SENADOR (PREÇO UNITÁRIO: )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - SENADOR QUEIROZ: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - SOLARES DE BRINDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - TNG: ARMAÇÕES ~ MURILO A. FLÓRIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - TNG: COMPRA DE ARMAÇÕES - PARCELA 05/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - TNG: COMPRA DE ARMAÇÕES - PARCELA 06/10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - TNG: COMPRA DE ARMAÇÕES - PARCELA 06/10: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES - WILTON JÚNIOR: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES: Parcela 1/2 > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ARMAÇÕES: Parcela 2/2 > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW());
