INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'COMISSÃO: Joana D''arc Elvira (agendamentos, ref. ago/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Joana D''arc Elvira (agendamentos, ref. set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Joana D''arc Elvira Jesus Alves Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Joana D''arc Elvira Jesus Alves Araújo > PIX: 239.961.918-80 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Jocicreide Macedo Barbosa Santos (ref. a diferença sobre as entradas) > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: João Paulo Sirassava Guapo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Kaylane Milena Silva (divulgação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Kethelyn Miranda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Kethelyn Miranda (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Kethelyn Miranda (agendamentos, ref. set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Kethelyn Miranda (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Laura Andreza Costa Pereira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Letícia Morais Domingos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Letícia Morais Domingos (agendamentos, ref. set/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Luana Cristina Martins Campos (ref. OS entregue ~ MAUÁ, parcela 1/2) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Luana Cristina Martins Campos (ref. OS entregue ~ MAUÁ, parcela 2/2) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Luana Cristina Martins Campos (ref. a diferença sobre as entradas) > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Luana Soares da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Maria Elizabeth Pereira do Nascimento (ref. a diferença sobre as entradas) > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Maria Isabel Moura da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Miriam Ferreira Sanches(ref. nov~dez)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Robson Luiz Alves dos Reis', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rogério Aparecido de Morais (ref. 29/04-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rogério Aparecido de Morais (ref. dez/2023 - entregas Rio Pequeno) > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rogério Martins dos Santos (ref. Rio Pequeno - MAR/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rogério Martins dos Santos (ref. Suzano I - MAR/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rosangela Aparecida Dejane Felisbino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rosangela Aparecida Dejane Felisbino (ref. a diferença sobre as entradas) > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF) - DN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Sandy Cristina da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Thayssa Roberta Lima da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Thayssa Roberta Lima da Silva (telemarketing)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Wevilly de Souza Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Wevilly de Souza Fernandes Líbano (ref. a diferença sobre as entradas) > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Wevilly de Souza Líbano (ref. Jan/2023 - diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Yasmin Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Érika de Oliveira Gomes (agendamentos, ref. ago/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COML KIN DE HIDR FERRAG ELETR LTDA: Multiuso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPANHIA DE DESENVOLVIMENTO HABITACIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA ATELIÊ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA CARTAO - NO ESTABELECIMENTO ITAQUERAO SUSHI HOUSE SAO PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DA LOJA - ENTRADA DE COMPRA: COMPRA DA LOJA - ÓTICAS TATY MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DA LOJA - PARCELA 1/5: COMPRA DA LOJA - ÓTICAS TATY MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DA LOJA - PARCELA 2/5: COMPRA DA LOJA - ÓTICAS TATY MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DA LOJA - REGINALDO DONIZETE: ARMÁRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DA LOJA - RESTANTE DE ENTRADA: COMPRA DA LOJA - ÓTICAS TATY MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ACESSÓRIOS: Capinha para óculos e estojos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÃO - EPI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES (solares)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES E SOLARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: 25 DE MARÇO - 118 PEÇAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: 25 DE MARÇO - 20 PEÇAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: 25 DE MARÇO - 30 PEÇAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: ANDRÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: ANDRÉ - PARC. 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: ANDRÉ - PARC. 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: ANDRÉ - PARC. 3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: ANDRÉ - PARC. 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: ANDRÉ - PARC.3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Allegre Comercial LTDA > PIX: zfang4426@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Balgriff', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Clipon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Du Qingsong > PIX: 056.075.737-96 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Enming Li > PIX: 245.265.668-29 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Huang Wenha > PIX: 241.941.928-69 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Lihuang Yao > PIX: (11) 9 8138-2999 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: NA LIU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: Qin Pi > PIX: (11) 9 8205-1988 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ARMAÇÕES: SLD MISSI LTDA > PIX: (11) 9 1188-8880 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE AÇÚCAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CABO DE REDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CADEADO PARA A LOJA - Luana > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CARREGADOR - Luana > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CARREGADOR - Rosangela > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CELULAR: Setor DCL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CORDINHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE CORDÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ESTOJOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ESTOJOS CAIXINHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ESTOJOS CARTEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE FLANELAS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ITENS PARA LOJA (decoração): Giovanna Mello de Camargo > PIX: 517.291.608-32 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ITENS PARA LOJA: Cartão Fidelidade + Tags de sacolas - Giovanna Mello de Camargo > PIX: 517.291.608-32 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ITENS PARA LOJA: Cartões Panfleto, Cartão OL e Tags de sacolas - GiOVANNA COMERCIO VAREJISTA DE OTICA LTDA > PIX: 51.837.184/0001-80 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ITENS PARA LOJA: Tags de sacolas > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE LENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE PAPEL HIGIÊNICO - Luana > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE PAPEL HIGIÊNICO - Rosangela > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE PILHAS - Luana > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE SOLARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE SOLARES (brinde)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE SOLARES: Enming Li > PIX: 245.265.668-29 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE SOLARES: Kebin Lin > PIX: 233.740.788-85 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Everton Cardoso > PIX: 365.967.588-18 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Felipe > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Felipe > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Luana > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Rogério > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Rosangela > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Tatiana > PIX: 285.876.68-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Wevilly > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - William > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA - Érika > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA > PIX: (11) 9 4742-3099 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA DE ÁGUA> Larissa Dias > PIX: larissadiss766@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA E GRAVAÇÃO DE AMOSTRAS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA E GRAVAÇÃO DE ESTOJOS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA E GRAVAÇÃO DE FLANELAS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA E GRAVAÇÃO DE SAQUINHO SOLAR: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA MERCADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA PARA LOJA: Compra de Balões, Cartolina, Copos descartavies, lixa e palito de unha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRA PARA LOJA: Cordão de nylon e fiita PVC cristal', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS > Nicolas Coutinho > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS DE ACESSÓRIOS PARA A LOJA (ref. ) > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS DE ARMAÇÕES: Óculos de sol > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 05/09 13:05 ASSAI ATACADISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 05/10 14:23 SOFT PEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 08/10 18:42 COMERCIO DE DOCES IM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 09/11 10:24 LOJAS KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 09/11 10:38 DUPARI COMERCIAL EIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 13/10 15:18 PAPELARIA SOFT PE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 13/11 17:11 ARMARINHOS FERNAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 17/09 14:38 LETICIA UNIFORMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 17/09 14:43 LIMPEZA DESCARTAVEIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 17/11 17:06 SOFT PEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 21/03 15:56 DUPARI COMERCIAL EIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 21/03 15:59 DUPARI COMERCIAL EIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 23/09 17:07 DISPEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - 28/11 13:18 ARMARINHOS FERNAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ACF EMPÓRIO DO REAL UTILIDADES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ACF EMPÓRIO DO REAL UTILIDADES DOMÉSTICAS LTDA: XERETA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ACF EMPÓRIOI DO REAL UTILIDADES DOMÉSTICAS LTDA: AÇÚCAR REFINADO E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ADELIA EMI KOMURA SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ALCOOL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ALCOOL LÍQUIDO 70% 1L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AOYAGI COMERCIO DE MATERIA CREDENCIADORA: INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AOYAGI COMPRA DE MATERIAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AOYAGI COMÉRCIO DE MATERIAIS CREDENCIADORA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AOYAGI COMÉRCIO DE MATERIAIS CREDENCIADORA: INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ARMARINHOS FERNANDO LTDA: COMPRA DE ITENS PARA O ESCRITÓRIO E LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - ARRUELA LISA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AYOAGI COMÉRCIO DE MATERIAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AYOAGI COMÉRCIO DE MATERIAIS: ESPONJA, INTERFOLHA E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AYOAGI COMÉRCIO DE MATERIAIS: SABONETE LÍQUIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - AÇÚCAR UNIÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BALA E BISCOITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BALA MASTIGÁVEL E PIRULITO MIGUELITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BALÃO MÁGICO: ITENS PARA DECORAR A LOJA (ESPECIAL DIA DOS NAMORADOS <3)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BANCO DO BRASIL: CARTÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BARÃO TEXAS COMÉRCIO DE CARNES E DERIVADOS LTDA: REFRIGERANTE FANTA LARANJA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BAZAR KO FUKO LTDA: BEXIGA 8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BAZAR KO FUKO LTDA: BEXIGA SANTA CLARA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BMP UTILIDADES DOMÉSTCAS S.A.: REFRIGERANTE PET 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BMP UTILIDADES DOMÉSTICAS S. A.: PILHA COMUM AA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BMP UTILIDADES DOMÉSTICAS S. A.: REFRIGERANTE KUAT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BMP UTILIDADES DOMÉSTICAS S.A.: PILHA AAA CARTELA COM 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BMP UTILIDADES DOMÉSTICAS: CHOCOLATE AO LEITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BMP UTILIDADES DOMÉSTICAS: CLIPS N° 20 E FITA DUPLA FACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BOBINA TÉRMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BOLACHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BOLACHA E BALAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - BOLACHAS E BALAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CASA BONITA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CASA BONITA: PANO DE CHÃO E ROUPÃO FLANNEL TAUPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CASA PRESTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CASA PRESTES E MORAI SUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CHAO SU PRESENTES SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CHAVEIRO MEDEIROS: CHAVE PARA A PORTA DA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CIA DA LIMPEZA: INTERFOLHA BRANCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CIA DA LIMPEZA: PACOTE PAPEL DE MÃO E PACOTE DE SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - CLORO, DETERGENTE, DESINFETANTE, LIMPA PEDRA, SACO DE LIXO E SAPÓLIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMERCIAL MATRIZ LTDA: ORQUÍDEA PHALAENOPSI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO LTDA: FIO PARALELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO: PILHA ALCALINA AA BLISTER C/ 4 E LINHA NYLON PESCA EKILON 0.60MMX100M', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO: SOQUETE M13 65', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMPRAS PARA LOJA - COMERCIO DE DOCES IMPE S', 'juridica', NULL, True, NOW(), NOW());
