INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-PEDRO CARDOZO DE MATTOS JÚNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-ROBERTA TEREZA RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-ROSANA CORREIA NOGUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-SILVANIRIA APARECIDA PEREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-VALDIRENE PEREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-VALTAIR DE OLIVEIRA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-VANDERLEI DE OLIVEIRA BORGES PESSOA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :08561701-VIVIANE JESUS DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :09554480-ELAINE MAXIMIANA DA SILVA CENA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :09554480-EVA APARECIDA DE CAMPOS PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :09554480-FLAVIA SANTOS MONTEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :09554480-HELDA MARIA DOMINGOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-ADRIANA SILVA DE OLIVEIRA ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-ANA PAULA LOPES ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-ELIANE SOARES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-FRANCISCO JOSE DE SOUSA 24658626349', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-GILMAR BATISTA NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-GILVANA PEREIRA SALES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-GIOVANNA TIEMI HIRAKAWA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-JOAO BATISTA DE OLIVEIRA 04846875814', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-JUSSARA PACHECO FALCAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-LAIS FLORENTINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-LILLIAN DOS SANTOS GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-NATALICE DE CARVALHO MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-NEEMIAS OLIVEIRA DE MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-PEDRO CARDOZO DE MATTOS JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-RENAN CARLOS MARSOLA SOUZA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-RICHARD TIGUEIREDO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-SIDNEY BISPO DO ESPIRITO SANTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-T. M COMERCIO VAREJISTA DE OTICA SOCI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-THARLES RICARDO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10573521-WILSON APARECIDO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :10664513-BENEDITA MARCELINO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :11275560-DANILO MIGUEL ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :11275560-MATHEUS SANTOS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :13370835-MARIA DO SOCORRO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :16501555-EDSON NUNES DE HOLANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17184037-APARECIDA TEIXEIRA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17184037-ELAINE MAXIMIANA DA SILVA CENA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17184037-HELIO DEZIDERIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17184037-MARIA DE LOURDES LOPES ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-BIANCA CARDOSO BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-ESTEFANY PAULINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-ISABELA PEREIRA DE BRITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-JULIANA SANTOS SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-LAERT ANGELO DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-MARIA JOSE MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-MARTA OLIVEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-ROSEMEIRE CARDOSO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-SIRLENE DOS SANTOS TEIXEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-TATIANA PEREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-UELITON SANTOS CAVALCANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-VALDIVO PEREIRA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :17192451-VINICIUS DANIEL C DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-50.660.223 GISELE ZANETTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ADAM DA SILVA NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ADEMAR MAAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ADRIANA APARECIDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ADRIANO BRITO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ALDIMEIA PEREIRA MENDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ALESSANDRA VALÉRIA PRECRIMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ALEX NASCIMENTO DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ALEXANDRE DA SILVA VIDAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ALINE JULIANA DO CARMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANA ALICE DOS SANTOS CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANA CRISTINA FERREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANA MARIA BARBOSA LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANA MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANA PAULA GOMES PERES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANDREA LUIZA MARTINS DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANE CAROLINE ARAUJO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ANTÔNIA ELIANE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ARIANI DIAS FERNANDES CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BARBARA DE SOUZA SCHUMACHER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BEATRIZ SILVA MANGINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BIANCA FRANCO ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BRUNO CAMPANHOLI DOS SANTOS PELICER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BRUNO DANILO FERREIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BRUNO PEREIRA DOS ANJOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-BÁRBARA APARECIDA DE PAULA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CAMILA ANDRADE PINTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CAMILA MIURA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CARINA CONCEIÇÃO COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CECÍLIA TEIXEIRA SILVA MENEZES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CLAUDEMIR SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CLAYTON GOMES LEFUNDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CREUZA MARCIANO DA SILVA SILVERI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-CÍCERO MAICO TEIXEIRA DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-DAIANE DOS SANTOS FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-DANIEL GOMES DE CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-DANILO VIEIRA FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-DARLAN ALVES DO NASCIMENTO DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-DEBORA MARIA DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EDEMILSON DE SOUZA BEZERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EDER DOS SANTOS SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ELAINE CRISTINA SOARES DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ELIANA SAVOIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ELIANE ALMEIDA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ELISANGELA MARA DEL SANTO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EMERSON PEREIRA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EMERSON WILLIAM DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ERICA CRISTINA LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EROTIDES FRANCISCA VIEIRA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ESTEFANY PAULINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ESTER BARBOSA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ESTORNO LOCAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EVANDRO DOS SANTOS GUEDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EVERSON DE PAULA VIANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-EXCLUSIVE SOLUCOES IMOBILIARIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FABIANA CRISTINA RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FABÍOLA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FELIPE DOS SANTOS ZEFERINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FERNANDA DA SILVA PADILHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FERNANDA FIGUEIREDO CAFRUNI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FRANCIELE APARECIDA SILVA MOSCHIAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FRANCIELLY SUELEN DA SILVA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FRANCISCO DAS CHAGAS ALENCAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FRANCISCO EDUARDO DA SILVA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FÁBIO AUGUSTO PACHECO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-FÁTIMA AUGUSTA DA SILVA REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GABRIEL HENRIQUE CAVALCANTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GABRIELA SANTIAGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GABRIELY CRISTINA MATEUS DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GI COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GIOVANNA CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GISELE ZANETTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-GUILHERME ESPANGUER ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-HELEN DA SILVA CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-HELOÍSA APARECIDA CHAVES HILBERT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-IRANI FRANCISCA DA SILVA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-IZAURA CAMPANHOLI DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JAQUELINE OLAITAN OLUWABUKUNMI MOTUNR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JESSE MATOS DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JOELMA ADRIANA FARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JOELMIR SOUZA DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JOSEANA LOPES DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JOÃO BATISTA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JOÃO CORA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JUCINEIDE PEREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JULIANA ALVES DE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JULIANO PATRICK TOPAZIO ANASTACIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JUREMA REGINA NASCIMENTO GENTIL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JÉSSICA HENRIQUE DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-JÚLIA ALMEIDA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-KAIQUE GOMES MIRANDA ELIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-KETHELYN MIRANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-KEVIN MATSUMOTO COUTINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LARISSA CRISTINA DE SOUZA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LARISSA CRISTINA FERRAZ BERTOLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LEIDIANNE OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LEIDYLA SILVA NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LETICIA CRISTINA VITURIANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LETÍCIA CORREIA RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LEVI CORREIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LUANA PEREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-LUCIVALDO GUILHERME DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARCELIA DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA DE FÁTIMA MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA DE FÁTIMA RIBEIRO OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA DE LOURDES LOPES ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA ELIZABETH PEREIRA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA RÚBIA FERREIRA ALENCAR SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA SOLANGE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIA THAYS NOGUEIRA DE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIANE SANTOS FALCÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MARIENE ARRUDA SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MELLANIE CRISTINE DOS SANTOS RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MICAELA APARECIDA MELO DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MIGUEL JESUS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MIKAELLY DAMIANE LOPES FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MIRIAM APARECIDA DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MIRIAM MARCIA DE SOUZA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MONIQUE FERREIRA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-MURILO ANTUNES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-NATALICE SOUZA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-NATÁLIA MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-NAYARA RIBEIRO SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-NEIDE DA SILVA SOUSA DE AZEVEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-NICOLAS COUTINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-NICOLLAS HENRIQUE SOUZA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-OZEILDO SANTOS DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-PATIENCE BELLO SHAMAKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-PATRICK RAMOS BENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-PAULA LOPES OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-PEDRO HENRIQUE LUKE RICIERI ALVES CAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-PRISCILA APARECIDA CAVALCANTE NASCIME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-PRISCILA DE SOUZA KUKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-RAPHAELA DA SILVA BASTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-RAQUEL COSTA ASSUNÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-REBECA COSTA MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-REGIANE MACIEL RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-RENATA SILVA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-RENILZA DA SILVA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-RITA DE CÁSSIA COELHO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROBERTA TERESA RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROBERTO LANDIM DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROGÉRIO DE ALMEIDA FREDI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROGÉRIO FELIPE DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW());
