INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Tekbond', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA SANTOS MONTANARI MATERIAIS PARA CONSTRUÇÃO LTDA: Areia e cimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA SANTOS MONTANARI MATERIAIS PARA CONSTRUÇÃO LTDA: Areia e cimento > Wevilly > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASAS PERNAMBUCANAS: CHIP TIM (DCL)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAUÇÃO - ALUGUEL ESCRITÓRIO (renovação do contrato de aluguel 2024) > PIX: 02.131.820/0001-48 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAUÇÃO - ALUGUEL ESCRITÓRIO: Parcela 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAUÇÃO - ALUGUEL ESCRITÓRIO: Parcela 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CEA SUS 523', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CEI 005812 DEP CHQ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTER CARNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRAL DAS CORES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO AUTOMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO AUTOMOTIVO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO AUTOMOTIVO DU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO AUTOMOTIVO TR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO MEDICO CLUBE DS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO MEDICO CLUBE DS LTD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CENTRO MÉDICO CLUBE DS > PIX: 35.553.747/0001-51 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CEUSS MEDICINA DI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHAVEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHAVEIRO > Larissa A. S. Albuquerque: Cópia de chaves > PIX: 474.400.388*51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHAVEIRO > Larissa A. S. Albuquerque: Miolo do portão + 2 chaves > PIX: 474.400.388*51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHAVEIRO SOS SOARES > PIX: 27.177.706/0001-80 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHEQUE COMPENSADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHIP Tim', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHS BURGER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHUPS SORVETE ART', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHURRASCARIA BOI NOB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHURRASCARIA E PIZZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CHÃO SU PRESENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CIA DA LIMPEZA: Interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CIA DA LIMPEZA: Interfolha 12 pacotes > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CIA DA LIMPEZA: Interfolha branco', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CIA DA LIMPEZA: Papel interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLIENTES - CELIA R. MARQUES FIGUEI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLIENTES - TROCO PARA CLIENTE: PATRÍCIA L. S. ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLIENTES - UBER: CLIENTE NADIR PARA JOCY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLIENTES - ZONA AZUL CLIENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLINICA INFINITY VISION SUZANO LTDA > PIX: 53.141.209/0001.31 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLÍNICA DOS OLHOS PERUS: Renan de Toledo Rodrigues. > PIX: 333.268.378-01(CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLÍNICA MÉDICA HÓRUS VISION', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLÍNICA MÉDICA HÓRUS VISION > Alline Figueiredo Sanches - PIX: 384.017.378-77 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLÍNICA MÉDICA HÓRUS VISION > PIX: 384.017.378-77 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CLÍNICA SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COCO E FRUTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 04/2021 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 04/2021 (1° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 04/2021 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 04/2021 (2° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 11/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 11/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 12/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 12/2022 (Multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional - 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 01/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 01/2023 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 01/2023 - Parcela 7/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 01/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 01/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 01/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 02/2023 - Parcela 10/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 02/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 02/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 02/2023 - Parcela 9/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 02/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 03/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 03/2023 - Parcela 12/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 03/2023 - Parcela 13/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 03/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 03/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 04/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 04/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 10/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 11/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 2/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 24/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 25/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 26/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 27/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 28/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 29/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 3/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 30/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 31/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 32/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 33/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 34/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 35/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 36/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 37/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 38/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 39/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 4/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 40/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 41/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 42/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 43/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 44/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 45/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 46/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 47/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 48/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 49/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 5/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 50/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 51/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 52/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 53/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 54/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 55/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 56/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 57/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 58/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 59/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 6/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 60/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 7/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 8/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2021 - Parcela 9/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 05/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 06/2021 - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 06/2021 - Parcela 11/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 06/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 06/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 14/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 15/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 16/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 17/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 18/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 2/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 3/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2022 - Parcela 5/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 07/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 13/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 14/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2021 - Parcela 15/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 08/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 09/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 09/2022 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 09/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 09/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 10/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 11/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 11/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 12/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COFINS: Simples Nacional 12/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO FERREIRA MASTER: NICOLLY MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI SOCIEDADE: NICOLLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Apostilas - Nicolly Mello de Camargo - Parcela 8/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 1/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 10/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 11/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 12/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 2/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 3/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 4/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 5/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 6/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 7/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 8/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Extras - Nicolly Mello de Camargo - Parcela 9/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 1/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 10/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 11/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 12/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 2/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 3/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 4/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 5/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 6/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 7/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 8/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade + Rematrícula - Nicolly Mello de Camargo - Parcela 9/12 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 2/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 4/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 5/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade- Nicolly Mello de Camargo - Parcela 1/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade- Nicolly Mello de Camargo - Parcela 3/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade- Nicolly Mello de Camargo - Parcela 6/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO INTEGRADO LUMBINI: Mensalidade- Nicolly Mello de Camargo - Parcela 7/11 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 1/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 10/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 11/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW());
