INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CRISLAINE SANTANA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CRISTIANE B D BRASILEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CRISTIANE BARROS DOS SANTOS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CRISTIANE SILVA TAVARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CRISTINA DE JESUS BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CRISTINA SOARES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CUSTODIO SILVA DE MELO 25344839863', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CÁTIA CARVALHO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DALILA APARECIDA DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIEL ALVES DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIEL LUIZ CUSTODIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIEL PEREIRA SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIEL TAVARES DASAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELA GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELA GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELA JUNQUEIRA RINO PIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELA MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELA SANTOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELA VIEIRA FERNANDES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELLE ANDRADE GUERINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANIELLE PEDROSO GRANSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DANILLO MARQUES BRITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DARCI ALICE VICENTINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DAVID QUISPE SOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DAVID RODRIGUES MACRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DAYANE KARINA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DEBORA L G DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DEBORA LIMA MAGALHAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DEBORA MARIA DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DEISE CRISTINA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DEISEANE ROCHA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DEISYANE DE CASTRO SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DENIS SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DENISE SOARES FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DIEGO HUMBERTO PIMENTEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DIEGO PEREZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DIEGO SILVA VIANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DIVA RAMIRES CUENCA DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DJNNYFER ALMEIDA PRADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DOMINIQUE RODRIGUES COULANGE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DONA MARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DOUGLAS DE PAULA FERNANDES PESSOA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DOUGLAS GOMES DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DOUGLAS PEDROSO COMERCIO DE VARIEDADES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - DOURIVAL CLEMENTE DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDEMILSON DE SOUZA BEZERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDILE R M MARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDILENE DOS SANTOS MANGUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDILSON DA CONCEICAO DELGADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDNALVA MARIA DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDNEUSA APARECIDA EVARISTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDSON DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDSON DE OLIVEIRA 05495138848', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDSON MARQUES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDUARDO ADRIANO DA SILVA MALTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDUARDO DA SILVA CORREIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EDVALDO SOARES DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EGNALDO MARCIAL DE BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELAINE GOMES DE MORAES CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELENI DE LIMA BICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELENITA DIAS DOS SANTOS JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIANA DOMINGOS MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIANA PELLEGRINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIANA SAVOIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIANE ALVARENGA DA SILVA BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIANE PEDROSO ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIAS MARTINS CUSTODIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIEL DUARTE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIETE DAMBROSIO DIAS COELHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELISABETE GOMES MARQUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELISANGELA MIRANDA DOS REIS FRANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELITA SOARES DA SILVA BRITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZABETE AGUIAR LUZ BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZABETE ALVES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZANDRA DIAS FERREIRA MONTEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZANGELA ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZANGELA STEIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZEU LUCIO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELIZÂNGELA ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELLEN CRISTINA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELTON JOSE SOUSA DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ELZA DOS REIS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EMERSON BULCAO GOMES PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EMILY RAYSSA LOYO SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EMILY SILVA DE LILA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ERICA DA SILVA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ERICA KIYOMI SENZAKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ERICA YOKOMINAKAWA TERASHIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ERICH CRISTIANO RODRIGUES JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ESDRAS AURELIANO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ESTELITA Q CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ESTELITA QUARESMA DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ESTER MARTINS DA GAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EUDES CONCEICAO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EUNICE GOMES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EUNICE LAU DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EVERTON DONHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EVIVALDO CLIMACO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - EZEQUIEL PEREIRA SOLEDADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIANA ALVES VERISSIMO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIANA BLASIO BELLUOMINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIANA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIANA MARCIA DA SILVA MORAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIO ALEXANDRE DE JESUS GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIO AUGUSTO ALVES COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIO DE MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIO GONCALVES MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIO JUNIOR DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FABIOLA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FATIMA APARECIDA DE MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDA APARECIDA ROCHA MIYAWAKI DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDA DOS SANTOS ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDA GALLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDA MAGDA BATISTA DE PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO DE ALMEIDA AMADEU 32295784816', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO DE OLIVEIRA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO JOAO PAGNANI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO MACEDO GODOI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO RIBEIRO ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO RODRIGUES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FERNANDO TAVARES CAMILO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FLAVIA BARBOSA DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FLAVIO RODRIGUES GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANCIELE MARIA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANCINEIDE MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANCISCA MARGARETH GADELHA MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANCISCA SOLANGE JUSTINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANCISCO ANTONIO IADOCICCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANCISNIEL AMORIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FRANSIMAR APARECIDO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - FREDERICO ESTEVAO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIEL AUGUSTINHO DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIEL CARDOSO DE OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIEL H TAVARES ADAIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIEL HENRIQUE CAVALCANTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIEL MARQUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIELA CONCEICAO VICENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIELA DE BRITO LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GABRIELY VITORIA SOARES DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GEISLA MENDES DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GENIVALDO ABADE DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GEORGIA NAZARE DA CONCEICAO MENDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GEOVANA APARECIDA GASTÃO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GEOVANI TAVEIRA DE BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GI COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIANE DE MELO MATHEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIGI C V O LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GILBERTO DE CAMARGO SILVA JR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GILBERTO DOS SANTOS OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GILBERTO EVANGELISTA DA SILVA PIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GILEANE DE VASCONCELOS MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GILMAR LOPES MARINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIOVANA NASCIMENTO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIOVANNA BELLUOMINI MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIOVANNA C V O LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIOVANNA CRISTINA FRANCA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIOVANNA DA SILVA BOSQUETI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GISELE CRISTINA GUILHERMETTE MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GISELLE LIMA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GISLEINE RODRIGUES N LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GIVANILDO PEDRO DAS DORES 16613887870', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GLEUSON CAMPOS SILVA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GRACE KELLY MAGNAVITA STUTZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GRACE KELLY MAGNAVITA STUTZ 43330403888', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GRACIELA ANTONIA GREGORIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GRAZIELA SOUZA BRITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GRAZIELE CUSTODIO MARQUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GRAZIELE DOS SANTOS SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GUSTAVO SOUZA DE CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - GUSTAVO SOUZA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELDA MARIA DOMINGOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELEN MARIA CARVALHO VENCESLAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELENA BENEVIDES FARIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELENA S NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELLEN VITORIA G S LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELLEN VITORIA GONCALVES DA SILVA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HELOISA ALVES FIGUEIREDO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HENRIQUE LIMA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HENRIQUE OLIVEIRA RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HENRY CHUKWUNONSO UMEH', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HERMES ADAO MACEDO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HILDA SOUZA DOS SANTOS PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - HOSANA BARACHO DOS SANTOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IGREJA APOSTÓLICA UNÇÃO SEM LIMITES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ILVANETE PEREIRA RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IMACULADA DA CONCEICAO APARECIDA PIRES DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - INDAIARA CELIA DOS SANTOS CAVALCANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - INDAIARA CÉLIA DOS SANTOS CAVALCANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IRACELO ALVES FEITOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IRIS DOS SANTOS XAVIER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ISABELA CRISTINA CALABRÓ BLASCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ISABELLE VIANA SILVA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ISABELLY VIEIRA SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ITALO HUGO CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IURAPUAM LUIZ DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IURAPUAN LUIZ DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IVONETE ALVES SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IZABEL DOS SANTOS PIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IZABEL MOREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW());
