INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11854', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11855', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11857', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11866', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11868', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11872', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11876', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11879', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11886', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11894', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11946', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11947', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11955', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11958', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11963', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11964', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11973', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11978', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11981', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11990', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11992', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 11996', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12004', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12026', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12035', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12038', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12043', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12044', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ) - ref. OS 12047', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Sacos para bolos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Sinal do pagamento dos doces', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Soft Pel- Bloco adesivo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Stylus - festa Nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Sumup Sol Pagam Antecipac', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Sumup Sol Pagament Débito', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Superlógica - Aluguel condominio apto', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Supermercado Nagumo: Pão, margarina café e lava limpa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Suzanmi Bazar e Papelaria: Papel crepom > Mike Rodrigues > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSORIOS OPTICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSORIOS OPTICOS - Mola p/ armações', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSORIOS OPTICOS: Cordão tecido e cordão silicone', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSORIOS OPTICOS: Mola Para armações', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSORIOS OPTICOS: Plaqueta especial', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS OPTICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: ALICATE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CHAVE - CONJUNTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CIREX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO FASHION', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO INFANTIL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO METAL LUXO (04 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO PÉROLA (09 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO SILICONE (05 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO TECIDO (10 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: CORDÃO VELCRO (04 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: Conjunto de chaves 10 pontas > PIX: spao@spao.com.br (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: Cordão de tecido e Ponteira emborrachada > PIX: spao@spao.com.br (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: MOLA ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: Mola para armações > Nicolas Coutinho > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: PINÇA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: PLAQUETA PARA ACETATO (04 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: PONTE ANATÔMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: Plaquetas de silicone > Nicolas Coutinho > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: SAQUINHO MICROFIBRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: SAQUINHO MICROFIBRA (13 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS ÓPTICOS: TERMINAL DE PONTEIRA (02 UNIDADES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS: Flanelas > Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS: Flanelas, parafusos guia e plaquetas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS: Itens para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS: Molas, plaquetas de silicone e parafusos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÃO PAULO ACESSÓRIOS: Saquinhos para solar > PIX: spao@spao.com.br (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS - JEFFERSON RICARDO ALBERTINI > PIX: (11) 9 5808-0667 (celular) - ref. OS 10762', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. ID 2556', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. ID pedido: 152959 (Lentes do Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10141', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10214, 10215, 10297 e 10309', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10336', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10370', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10398', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 10470', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 4239-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 4600', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 6918', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 6934', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 6951', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 9585', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 9655', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 966', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS 9940', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOCOS > PIX: jeffersonalbertini@gmail.com (e-mail) > ref. OS''s 10399, 10417 e 10421', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SÓ BLOOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'São Paulo Acessórios Opticos - 10 Parafusos valor: 7,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'São Paulo Acessórios Opticos - 3 Plaquetas de Silicone valor: 25,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'São Paulo Acessórios Opticos - 4 Plaquetas para Acetato valor: 5,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'São Paulo Acessórios Opticos - 5 Plaquetas de PVC valor: 10,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'São Paulo Acessórios Opticos - 6 Plaquetas para acetato', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'São Paulo Acessórios Ópticos: Cordão Silicone', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'T. S. FONSECA PRESTAÇÃO DE SERVIÇOS: Guincho do carro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TABOAO DA SERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAKEJI MIZUGUCHI-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAR DOC/TED ELETRÔNICO - COBRANÇA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAR PACOTE ITAU MAR/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TARIFA FORNEC CHEQUE - COBRANÇA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TARIFA PACOTE DE SERVIÇOS - COBRANÇA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TARIFA PACOTE DE SERVIÇOS - RECARGA DE CRÉDITO: CELULAR DO ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE EXPEDIENTE 2025 - Prefeitura Municipal de Suzano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ANÚNCIOS - Parcela 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ANÚNCIOS - Parcela 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ANÚNCIOS - Parcela 3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ANÚNCIOS - Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO - ref. 06/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS (instalação) - Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS (publicidade) - Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS - Parcela 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS - Parcela 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS - Parcela 3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E DE ANUNCIOS - Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO) - Parcela 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO) - Parcela 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO) - Parcela 3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO) - Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUNCIONAMENTO - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUNCIONAMENTO - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUNCIONAMENTO - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE LICENÇA E FISCALIZAÇÃO DE FUNCIONAMENTO - Parcela Única', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - AMERICAN EXPRESS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - ELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - HIPERCARD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - MASTERCARD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - SOROCRED', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - TAXA DE PARCELAMENTO E DA CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA DE VENDAS CARTÃO - VISA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXA EXPEDIENTE - 2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TAXAS DA SUMUP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TEKBOND PAPELARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TEMPERO MANERO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TENDA ATACADO: Papel higiênico e sanol', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TERUIA PERFUMARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TERUYA MAUÁ BARÃO DE MAUÁ COMÉSTICOS LTDA: LIXA PARA UNHAS - POLIDORAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TFE - ref. 2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'THAIS CHEN DU: Compra de saquinhos para solar > PIX: (11) 9 4890-9607 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TIRTA FERRAGENS: Extensão elétrica e prego de aço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TIRTA FERRAGENS: Lâmpadas fluorescentes LED - Felipe > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TNG', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TNG - Armações', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TOP LAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TOP LAR: Coca cola 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TOP LAR: Copo descartável e desinfetante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TOPFER COMERCIO D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TOQUE DE MESTRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TOQUE DE MESTRE: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TORRA TORRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSF AUTORIZ ENTRE AGS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - APORTE FINANCEIRO: INVESTIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - BANCO ITAÚ - DEPÓSITO BANCÁRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: BRK AMBIENTAL: ÁGUA - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: CONCEPT IMÓVEIS - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: DIVULGAÇÃO - RAISSA (COMISSÃO - MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: ENEL ELETROPAULO METROPOLITANA ELETRICIDADE DE SÃO PAULO S. A.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: MATERIAIS - ATELIÊ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: SEGURANÇA - SEBASTIÃO (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: SÓ BLOCOS: COMPRA DE LENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - INVESTIMENTO: ÁGUA - ATELIÊ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - PAGTO ELETRON COBRANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - RECEBIVEIS DE VENDA - CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - TRANSF FDOS DOC-E H BANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSFERÊNCIAS - TRANSF.AUT.C/C P/POUP.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRANSPORTE: Confraternização ref.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRELLO - Controles', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TREVISAN NEGOCIOS IMOBILIARIOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TREVISAN NEGOCIOS IMOBILIARIOS LTDA (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TREVISAN NEGOCIOS IMOBILIARIOS LTDA (taxa boleto)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRIDENT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TRIUNFO DOS PAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TROCO (estorno): Larissa Dias > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TROCO (estorno): Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TROCO (estorno): Samuel Henrique da Silva > PIX: 492.256.288-54 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TROCO (estorno): Érika de Oliveira Gomes > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TUTI BAZAR E PAPELARIA LTDA: Prancheta', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TWS TELECOMUNICAÇÕES LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'TWS TELECOMUNICAÇÕES LTDA: Ativação única de plano de controle', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Tarifa Pacote de Serviços Cobrança referente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Tarifa Pacote de ServiçosCobrança referente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Tarifa Pix Enviado Tar. agrupadas - ocorrencia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Tarifa Pix EnviadoTar. agrupadas - ocorrencia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Taxa de Fiscalização de Estabelecimentos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Taxas de Link do Cartão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Taxas de Vendas no Link no Cartão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Telefone Pre-Pago 11985992141-TIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Telefone Pre-Pago11985992141-TIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Tenda Atacado: Café e Papel higiênico > Nicolas Coutinho > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transferência enviada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transferência enviada06/07 4437 11920-2 T.M.C C V O S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transferência recebida 18/01 16:07 TMO C V OTICA LTDA', 'juridica', NULL, True, NOW(), NOW());
