INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IZABELA DOS SANTOS MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - IZALTINA JULIA DOS S BARBOZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JACKELINE MELO ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JANAINA DA SILVA DANTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JANE PEREIRA ANGELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JAQUELINE DOS SANTOS MEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JAQUELINE DOS SANTOS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JAQUELINE FERREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JAQUELINE MOREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JEANNE DE LIMA AMARAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JEFERSON CARLOS RESINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JEFERSON MITSUO TAKEUTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JEFFERSON RODRIGUES SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JESSICA CRISTINA DE OLIVEIRA GONCALVES LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JHONATAN GOMES VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JHONATAN PEZZUOL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JL GUINCHOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JLELETRICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO CARLOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO JUSTINO FILHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO PEDRO LOURENCO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO SANTANA DA SILVA NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO VICTOR DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO VICTOR OLIVEIRA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO VITOR DOS SANTOS NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAO VITOR ESPINDOLA CATTANIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOAQUIM ANDRE DE MELO COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JODENILSON SANTOS SAMPAIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOELMA MARIA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOELMA SILVA RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOENES PEREZ AMORIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOICE APARECIDA DA SILVA MIRANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOICE FRANÇA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOICE RABELO DAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOICIELE SANTOS TENORIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JORGE LUIZ DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JORGE LUIZ OLIVEIRA DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JORGE MAYCON AMARAL MIRANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE BEZERRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE CLAUDIO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE FERNANDES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE FERREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE JOAO DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE OSMAR RICARTE COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSE ROBERTO LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSELMA ALVES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSEMARE SOARES RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSEMRE SOARES RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSIANE VICENTE DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSIAS ALMEIDA DE PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOSUE LOPES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOZELI SILVA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOÃO GABRIEL CARDOZO CASTRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOÃO GUSTAVO SOARES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JOÃO VITOR ESPINDOLA CATTANIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JUDY ANN FUKAKUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIA FRANZE BATISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIANA BARBOSA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIANA PEDROSO DOS PASSOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIANA PEREIRA LEÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIANA SANTOS SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIO BATISTA DOS SANTOS FILHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JULIO CESAR ALVES LIMA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JUSSARA CARVALHO F JANUARIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JUVENAL GONCALVES DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - JÚLIO CESAR BARBOSA RIBEIRO GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAIO CEZAR DA SILVA SANDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAIQUE GOMES MIRANDA ELIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAREN SOARES DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KASSIO REIS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KATIA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KATIA DE OLIVEIRA MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KATIA MARIA DA SILVA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAUANY RIBEIRO OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAWANE FERNANDES F SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAWANY CHAVES DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAYLLAINE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KAYO EDUARDO ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KELLY DOS SANTOS FARIA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KETTELYN ARAUJO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - KETTELYN ARAUJO DE OLIVEIRA DA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAERCIO HILARIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAERT ANGELO DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAIS FLORENTINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LARISSA DOS SANTOS GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LARISSA RANIELLE RIBEIRO DE BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAURA DIAS FERNANDES CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAURO MARQUES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAZARO APARECIDO MACHADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LAÍS FLORENTINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEANDRO ALONSO RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEANDRO ESTEVAM DA SILVA VATEZECK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEANDRO PEREIRA JACINTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEANDRO VATEZECK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEDINEIA ESTEVES FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LELIA HAKEMI GEN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEONARDO ALMADA NOGUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEONARDO DE LIMA MARQUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEONARDO DE SOUZA TALARICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEONILDA MARTINS MOREIRA 39910846861', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEONILDA SIQUEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEONILDO PAULINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LETICIA AKEMI ABRANCHES NOHARA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LETICIA CRISTINA VITURIANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LETICIA JORGE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LETICIA PINTO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LETÍCIA ANDRESSA CORRÊA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LEUDIMAR OLIVEIRA CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LILIAN APARECIDA TRAJANO DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LILIAN CRISTINA COUTINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LILIANE COELHO DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LILIANE SANTOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LORRAINE NADINE SOUZA DE GODOY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUAN FARO GLASS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUAN FRANÇA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUANA CRISTINA MARTINS CAMPOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUANA STHEFANI DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCAS BARRETO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCAS OLIVEIRA MOTA SILVA 43892158843', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCAS SOUZA CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIANA BARBARA DA ROCHA DE JE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIANA RIBEIRO DA ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIANO DE SOUSA FONTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIANO FELIX SOUZA ESTEVAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIANO PAIANI DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCILENE PALMEIRA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIMARA MENEZES PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUCIVANE DANTAS DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUISA BATISTA DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUIZ CESPEDES CHAGAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUIZ GUSTAVO ROCHA GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUIZ HENRIQUE ARAUJO DIAS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUIZ ROBERTO FERNANDES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUZIA APARECIDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - LUZILENE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAGNO FIGUEIREDO DE BRITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAISA RENATO DE AQUINO COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MANOEL ALVES DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MANOEL BEZERRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MANOEL F RAMINELLI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MANOEL LIBERATI DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCELA SALES SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCELIA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCELIA DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCELO CLARINDO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCELO ROBERTO DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCIA FERREIRA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCIA PEREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCIA REGINA TEIXEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCIO DE LIMA TEIXEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCIO FAVERO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCIO HENRIQUE LOUREIRO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCOS ALVES DOS SANTOS JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCOS ANTONIO RODRIGUES DE MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCOS JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARCOS LUIS GUSMAO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA ANDREIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA ANTONIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA APARECIDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA APARECIDA FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA CLARA BARROS DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA CLAUDIA DA SILVA SALES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DA CONCEICAO BENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DA CONCEICAO DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DAS VITORIAS NEVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DE FÁTIMA MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DE JESUS SOUSA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DE LOURDES LOPES ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DE SOUZA CASTRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DO SOCORRO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA DORES SILVA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA ELIZABETH PEREIRA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA GERLANE ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA GORETI HERCULANO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA IVANI DO CARMO CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA JOSE FRANCISCO DE ANDRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA JOSE MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA LUCIA ROQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA LUZINAIDE VIEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA MESSIAS B DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA N SANTOS SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA NEUZA SANTOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA NILZA NERIS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA PAULA FARIAS MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA RAIMUNDA DA B M DE P OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA ROSA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA ROSEMARY DOS SANTOS ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA SOUZA DOS SANTOS OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIA ZULEIDE BARBOZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIANA A L BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIANA ROSA DE J DO CARMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIANE MARCELINO DE CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIANE MERIS RODRIGUES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARICELIA DE PAULA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIE GERMAINE BELLAMY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARILENE AGOSTINHO M OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARILIA BASTOS LEAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARILIA DA SILVA MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARILU CANDIDA JACOB PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARILU SENZIALI FLOR FERREIRA', 'juridica', NULL, True, NOW(), NOW());
