INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 52/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 53/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 54/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 8/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - FRANQUIA >> - parcela 3/3 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - INSTITUTO VISÃO: 1° Quinz. Março > PIX: sac@studio7otica.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - INSTITUTO VISÃO: 2° Quinz. Fevereiro > PIX: sac@studio7otica.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - INSTITUTO VISÃO: 2° Quinz. Março > PIX: sac@studio7otica.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - LIVRO ÓPTICO: Vivian Maria Ramos > PIX: 309.167.958-61 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Acordo 3/5 > PIX: 375.938.028-09 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Acordo 4/5 > PIX: 375.938.028-09 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Acordo 5/5 > PIX: 375.938.028-09 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Ariani Dias Fernandes Líbano - Acordo 6/6 > PIX: 487.287.868-07 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 10/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 11/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 12/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 13/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 4/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 5/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 6/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 7/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 8/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 9/13 > PIX: larissadiss766@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Mike Rodrigues Gomes - Acordo 7/7 > PIX: 413.050.558-02 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Vanessa Mendes da Silva - Acordo 2/6 > PIX: vanessamendys151619@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Vanessa Mendes da Silva - Acordo 3/6 > PIX: vanessamendys151619@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Vanessa Mendes da Silva - Acordo 4/6 > PIX: vanessamendys151619@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Vanessa Mendes da Silva - Acordo 5/6 > PIX: vanessamendys151619@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Vanessa Mendes da Silva - Acordo 6/6 > PIX: vanessamendys151619@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 9/9 > PIX: 453.302.308-88 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL CLÍNICA - MAUÁ (IPTU) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL CLÍNICA - MAUÁ >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL CLÍNICA - MAUÁ > + (juros/multas) =', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - MAUÁ (IPTU) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - MAUÁ >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - MAUÁ > + (juros/multas) =', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - RIO PEQUENO (IPTU) > PIX: 52.597.549/0001-09 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - SUZANO I (IPTU) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - SUZANO I > + (juros/multas) =', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - SUZANO I > + =', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - SUZANO II (IPTU) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - SUZANO II (taxa boleto) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ALUGUEL LOJA - SUZANO II >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: COLÉGIO INTEGRADO LUMBINI: Apostilas - Nicolly Mello de Camargo - Parcela 8/12 > PIX: 00.875.904/0001-60 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 10/11 > PIX: 00.875.904/0001-60 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 11/11 > PIX: 00.875.904/0001-60 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 8/11 > PIX: 00.875.904/0001-60 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: COLÉGIO INTEGRADO LUMBINI: Mensalidade - Nicolly Mello de Camargo - Parcela 9/11 > PIX: 00.875.904/0001-60 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 10/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 10/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 11/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 11/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 12/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 12/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 13/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 13/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 14/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 14/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 15/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 15/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 16/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 16/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 17/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 17/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 18/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 18/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 19/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 20/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 21/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 22/22 (compra da loja + rescisão Karina) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 5/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 6/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 7/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 8/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 9/18 > PIX: fastnegocios@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FOCO OPTOMETRIA > PIX: 46.081.461/0001-37 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FRANQUIA > PIX: (11) 9 8117-7178 (celular) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FRANQUIA > PIX: 52.597.549/0001-09 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: FRANQUIA >> > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: KENERSON GO - Parcela 1/10 > (restante da diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: KENERSON GO - Parcela 2/10 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: OPTOTAL HOYA LTDA >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: PASSWORD INTERATIVA BI E SOFTWARE - VIXEN (mensalidade, ref. 08/2023) > PIX: 15.495.166/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: PASSWORD INTERATIVA BI E SOFTWARE - VIXEN (proporcional ao cancelamento) > PIX: 15.495.166/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 2/6 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 2/7 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 3/6 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 3/7 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 4/6 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 4/7 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 5/6 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 5/7 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 6/6 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 6/7 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: ROB SOL INDUSTRIAL LTDA - Parcela 7/7 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: SYGMA LABORATORIO OPTICO LTDA - Parcela 1/3 > PIX: 30.576.013/0001-74 (CNPJ - Espeed) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: SYGMA LABORATORIO OPTICO LTDA - Parcela 2/3 > PIX: 30.576.013/0001-74 (CNPJ - Espeed) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: SYGMA LABORATORIO OPTICO LTDA - Parcela 3/3 > PIX: 30.576.013/0001-74 (CNPJ - Espeed) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO: VIP TELECOM 484542 - ESCRITÓRIO >', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


