INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'MERCADO - CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ PILÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAPSULA CAFÉ PILÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CHIBANA COMÉRCIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMERCIAL MATRIZ LTDA: PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMERCIAL OSWALDO CRUZ LTDA LJ 02: PÃO FRANCÊS E SACOLINHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMPRA ATELIÊ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMPRA PARA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMPRAS PRA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COMÉRCIO DE DOCES IMPERIAL GOLD EIR: SUSPIRO BRANCA DE NEVE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COPO DESCARTÁVEL 200ML', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - COPO DESCARTÁVEL, FILTRO DE CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CÁPSULAS PILÃO E ÓLEO SOYA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - DETERGENTE LÍQUIDO E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - DUDIS SALGADOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - EMPÓRIO DA ECONOMIA: DESINFETANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - EMPÓRIO DO REAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - EMPÓRIO DO REAL: BOLO PANCO, FOLHATA, TORTINHA, TANG E PÃO GALEGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - EMPÓRIO DO REAL: COPO DESCARTÁVEL E PÃO DE FORMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - EMPÓRIO DO REAL: PÃO PULMANN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ESPONJA DE AÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - FESTIPEL EMBALAGENS LTDA: BALA, BALÃO, FITILHO E SACO DECORADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - FILTRO DE PAPEL, PAPEL FRANCÊS E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - INTERFOLHA E AGUA SANITARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: IOGURTE, MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: LEITE INTEGRAL 1L E MORTADELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: LEITE INTEGRAL 1L, MARGARINA, MORTADELA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: PRESUNTO E QUEIJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - KILOUCURA DOCES EIRELI: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - LIMPEZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - LUCIMAR TOLEDO LIMA VAZ - ME: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MARGARINA, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MERCADO LEVE MAIS PAGUE MENOS: CAFÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MERCADO LEVE MAIS PAGUE MENOS: CAFÉ E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MERCADO LEVE MAIS PAGUE MENOS: CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MERCADO LEVE MAIS PAGUE MENOS: MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MERCADO LEVE MAIS PAGUE MENOS: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MERCADO LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MEXEDOR PARA CAFÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MILHO DE PIPOCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MORTADELA MARBA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MUSSARELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - MUÇARELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ORION REAL LTDA: AÇÚCAR, PORTA AÇÚCAR, PORTA CAFÉ E SACOLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ORION REAL LTDA: ESPONJA MULT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ORION REAL LTDA: ROSQUINHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E CONFEITARIA PAINEIRA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: CAFÉ, PÃO FRANCÊS E SUCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: FILTRO DE PAPEL E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: LEITE INTEGRAL 1L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: PÃO FRANCÊS E SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: ÁLCOOL E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: CHÁ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: DESINFETANTE, DETERGENTE E MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: MAIONESE E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS PAGUE MENOS: PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LEVE MAIS PAGUE MENOS: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO LIVRE MAIS E PAGUE MENOS LTDA: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA E MERCADO PAGUE MAIS E LEVE MENOS LTDA: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA L M P M', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA RENASCE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA RENASCE: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PADARIA RENASCE: PÃO FRANCÊS (ZAINE SIQUEIRA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PAGAMENTO DE UTENSÍLIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PAPEL HIGIENICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PAPEL HIGIÊNICO E PÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PAPEL HIGIÊNICO E SACO DE LIXO 40L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PERA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PILHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PIPOCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PREPARATIVOS CAMPANHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PRODUTOS DE LIMPEZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO DE QUEIJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO E COPO DESCARTÁVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO E FILTRO DE CAFÉ 102', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO E MANTEIGA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO E SUCO EM PÓ TANG', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E CAFÉ MOKA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E COPO DESCARTÁVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E REFRIGERANTE KUAT GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E REQUEIJÃO TRADICIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E SUCO EM PÓ TANG', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS E ÁGUA SANITÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS, CAFÉ E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO FRANCÊS, CAFÉ, MARGARINA E DETERGENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO INTEGRAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - PÃO, CAFÉ E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRESCO EM PÓ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRESCO EM PÓ, PÃO FRANCÊS E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRESCO FIT E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRIGERANTE COCA COLA 2.5L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRIGERANTE COCA COLA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRIGERANTE DE LARANJA (FANTA) 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRIGERANTE KAUT GUARANA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRIGERANTE KUAT GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - REFRIGERANTE SPRITE 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - S L PANIFICAÇÃO E CONVENIÊNCIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - S L PANIFICAÇÃO E CONVENIÊNCIA LTDA: ALMOÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - S L PANIFICAÇÃO E CONVENIÊNCIA LTDA: MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - S L PANIFICAÇÃO E CONVENIÊNCIA LTDA: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - S L PANIFICAÇÃO E CONVENIÊNCIA LTDA: PÃO FRANCÊS E REQUEIJÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - S L PANIFICAÇÃO E CONVENIÊNCIA: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUCO EM PÓ E BISCOITOS AMANTEIGADOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUCO MAGUARI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUCO TANG', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUCO, LARANJA E LIMÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUCO, LIMAO, LARANJA E PO DE CAFÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERC SEMAR SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCAD VERAN: PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO SEMAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ADOÇANTE 100ML', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ADOÇANTE E DESINFETANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ALHO A GRANEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR E CAFÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR REFINADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR REFINADO, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR, ADOÇANTE, CAFÉ E MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR, CAFÉ, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR, DETERGENTE LÍQUIDO, DETERGENTE EM PÓ E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: AÇÚCAR, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: BOLO DE CHOCOLATE, LEITE INTEGRAL 1L, BOLO PULLMAN, PÃO DE QUEIJO E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: BOLO DE LARANJA, LEITE INTEGRAL, MORTADELA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: BOLO FRAPE, LEITE INTEGRAL, QUEIJO E SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: BOLO GOTAS, LEITE INTEGRAL, MORTADELA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: BOLO, DESINFETANTE, LEITE INTEGRAL 1L E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ E MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ EM PÓ, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ, COPO DESCARTÁVEL, PÃO FRANCÊS E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ, DETERGENTE, MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ, PÃO FRANCÊS E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CAFÉ, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: COPO DESCARTÁVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: CÁPSULAS DE CAFÉ, PÃO FRANCÊS E REFRESCO DE PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DESINFETANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DESINFETANTE E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE LÍQUIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE LÍQUIDO E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE LÍQUIDO E SABÃO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE LÍQUIDO, MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE LÍQUIDO, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: DETERGENTE, MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ENERGÉTICO (JÚNIOR), ISQUEIRO E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ESPONJA 2 FACES E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ESPONJA 2 FACES, LUSTRA MÓVEIS, DESINFETANTE E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ESPONJA DE AÇO E VINAGRE DE ÁLCOOL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ESPONJA E REFRIGERANTE FANTA GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ESPRESSO, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO DE CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO DE CAFÉ, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO DE PAPEL E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO DE PAPEL E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO DE PAPEL, MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO DE PAPEL, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO PAPEL E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: FILTRO, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: GENGIBRE E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LASANHA BOLONHESA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LASANHA BOLONHESA E REFRIGERANTE COCA COLA ZERO 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LASANHA BOLONHESA E REFRIGERANTE KUAT 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE E REQUEIJÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL 1L, MORTADELA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL 1L, PRESUNTO E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL 1L, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL 1L, PÃO FRANCÊS E REQUEIJÃO VIGOR 200G', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL 1L, PÃO FRANCÊS E SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL 1L, PÃO FRANCÊS, PRESUNTO, QUEIJO MUSSARELA, REFRESCO EM PÓ, ROSCA DE COCO E TORRADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LEITE INTEGRAL E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: LIMPA PERFUME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MACARRÃO INSTANTÂNEO E REFRIGERANTE FANTA UVA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MARGARINA E MILHO DE PIPOCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MARGARINA E MORTADELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MARGARINA, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MORTADELA, PAPEL HIGIÊNICO E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW());
