INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 12/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 2/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 3/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 4/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 5/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 6/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 7/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 8/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COLÉGIO LUMBINI: Escola 9/12 - Nicolly Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 01/01 15:06 POSTO CASA BLANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 01/12 07:58 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 01/12 19:07 AUTO POSTO KIMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 02/01 10:32 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 02/09 19:20 REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 02/10 13:47 AUTO POSTO KIMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 02/11 07:22 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 02/12 13:11 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 03/01 13:03 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 03/11 17:17 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 03/12 11:11 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 03/12 19:07 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 05/03 11:12 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 06/01 12:21 GRAN SUZANO AUTO POS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 06/11 12:35 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 07/10 16:46 PORTAL DE POA AUT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 07/10 16:47 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 07/11 13:59 AUTO P NOVA RADIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 08/01 12:24 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 08/12 12:05 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 09/03 19:50 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 09/11 07:34 AUTO POSTO KIMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 09/12 11:34 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 10/02 19:04 POSTO RIO NEGRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 10/09 13:33 SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 10/09 19:14 PAG*AUTOPOSTOBOXTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 10/11 08:02 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 10/12 19:50 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 11/01 16:12 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 11/02 17:04 AUTO POSTO DUQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 11/03 12:54 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 11/03 12:59 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 11/03 18:37 CENTRO AUTOMOTIVO SA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 12/03 11:25 REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 12/12 09:09 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 13/03 10:55 REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 13/03 23:10 AUTO POSTO PARQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 13/11 09:10 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 13/11 17:51 AUTO POSTO PARQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 13/11 17:54 AUTO POSTO PARQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 14/09 16:21 POSTO DE SERVICOS AU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 14/09 16:22 POSTO DE SERVICOS AU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 14/12 12:06 POSTO CASA BLANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 15/02 10:32 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 15/03 16:09 FG NOVO CENTRO POSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 15/12 17:30 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 16/03 11:29 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 16/09 15:21 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 16/11 12:42 AUTO POSTO BETHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 17/03 11:24 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 17/11 17:12 POSTO QUALITY BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 18/01 10:55 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 18/02 15:55 AUTO POSTO VILA URUP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 18/03 10:19 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 18/12 10:55 AUTO POSTO BAGUA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 18/12 16:45 AUTO POSTO IMPERIO L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 18/12 17:17 POSTO FAROL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 19/09 00:27 AUT POSTO NOV EST PE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 19/10 07:44 AUTO POSTO KIMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 19/11 08:06 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 19/12 16:14 POSTO CASA BLANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 20/11 09:30 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 20/11 18:07 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 21/12 11:29 POSTO CASA BLANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 21/12 14:30 POSTO CONFIANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 21/12 18:23 AUTO POSTO IMPERIO L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 22/01 16:28 POSTO LAV LUB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 22/11 14:17 AUTO POSTO BETHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 22/12 14:23 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 23/09 15:39 AUTO POSTO KIMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 23/12 20:30 GRAN SUZANO AUTO POS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 24/03 20:59 AUTO POSTO RODOAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 24/12 10:37 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 25/03 17:03 AUTO POSTO DUQUE SAK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 25/03 18:14 AUTO POSTO PEDRAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 25/11 18:02 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 25/11 22:07 AUTO POSTO MARMELL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 25/11 22:08 AUTO POSTO MARMELL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 26/10 13:28 REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 26/11 12:43 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 26/11 19:30 PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 27/10 15:39 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 27/12 14:26 AUTO POSTO RENOVACAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 28/01 15:58 PAG*POSTOSETEE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 28/10 19:04 REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 29/01 15:16 DUTRAO AUTO POSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 29/10 13:19 POSTO SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 29/12 12:57 PORTAL POA AUTO POST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 31/01 14:39 REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - 31/12 21:35 POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - ARCO VERDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO CENTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO DE SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO KIMURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO KIMURA LI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO MRP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO PARQUE PIQUERI LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO RODOAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO RODOANEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO SUZAN PEC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - AUTO POSTO VILA URUP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - COMBUSTIVEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - CRIS AUTO POSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - FRANGO ASSADO POSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - GASOLINA: DIEGO FRANCISCO DOS SANTOS (REF. 04/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - GASOLINA: DIEGO FRANCISCO DOS SANTOS (REF. 05/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - GASOLINA: DIEGO FRANCISCO DOS SANTOS (REF. 21/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - GASOLINA: DIEGO FRANCISCO DOS SANTOS (RETIRADA DE SERVIÇOS - SUZANO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - GASTOS PARA PAGTO FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - PAG*AUTOPOSTODIVISAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - PAG*AUTOPOSTOMAXPOWE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - PETROBRAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - POSTO ANEL VIARIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - POSTO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - POSTO CASA BLAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - POSTO CASA BLANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - POSTO SERVCONFIANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - REDE DE POSTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - RODOANEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMBUSTIVEL - SUZAN PETRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL GLOBAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO LTDA: Esguicho, torneira e rosca', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO LTDA: Fechaduras', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO: Gesso rápido, massa corrida PVA e trincha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MD MATERIAIS PARA CONSTRUÇÃO: Tomada, plugue e fio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MD MATERIAL: Bucha e veda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL MITSUHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL OSWALDO CRUZ LTDA: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL OSWALDO CRUZ LTDA: Biscoito, pão francês e saquinho', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL OSWALDO CRUZ LTDA: Bolo de chocolate, suco e sacolinha (Café especial para o dia das mães, ref. 13/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL OSWALDO CRUZ LTDA: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL OSWALDO CRUZ LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL OSWALDO CRUZ LTDA: Água mineral 6L > Wevilly > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIAL RAYES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIO DE DOCES IM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERCIO EM DOCES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMERICAL OSWALDO CRUZ LTDA: Papel higiênico e sacolinha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - ARIANE GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ADRIANA GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ALESSA BISPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ALINE DA CRUZ SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ANDREIA PAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ANDREIA PAES - DIFERENÇA PAGA REF. AGO~SET/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ARIANI DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: DIEGO FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: JOCICREIDE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: JOÃO VITOR (24/08 Á 05/09', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: NATHALIA CAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: YASMIN SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - COMISSÃO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - DIFERENÇA COMISSÃO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - DIFERENÇA COMISSÃO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - DIFERENÇA COMISSÃO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - FREELANCER COMISSÃO: LUCAS CORNÉLIO (VENDEDOR REF. 08/07 E 09/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - PAGAMENTO DE COMISSÃO: APARECIDA NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - PAGAMENTO PARA CRISTIANE DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Adriane Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Ana Cristina Rodrigues Amancio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Ana Cristina Rodrigues Amâncio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Anderson de Jesus Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Andreia Firmino de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Ariani Dias Fernandes Líbano - MEDIA LIC MATERNIDADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Bruno Henrique Simão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Bruno Henrique Simão (diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Bruno Henrique Simão (ref. 20 dias trabalhados)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Bruno Henrique Simão (ref. MAR/2023 - Suzano I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Bruno Henrique Simão (ref. MAR/2023 - São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: ELIANA SAVOIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Emerson William da Silva Santos (ref. jul./2023 - diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Felipe Roger Miranda (ref. OS entregue ~ SUZANO I) > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Felipe Roger Miranda (ref. a diferença sobre as entradas) > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Felipe Roger Miranda > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Igor Nascimento Medeiros', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COMISSÃO: Joana D''arc Elvira', 'juridica', NULL, True, NOW(), NOW());
