INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - AUTOPOSTOVILA SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - BENJAMIN SALGADOS SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - COMERCIAL MD MATE SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - CONCESSIONARIA SP ITAPECERICA DBR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - DROGARIAS PINHEIR SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - ECOPISTA FPAY ITAQUAQUECETUBR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - ESTACAOMAUAAUTO MAUA BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - ESTACIONAMENTOS EPARK SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - F D I BAZAR LTDA ME SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - GRAN SUZANO AUTO POSTO SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - LOJAS KING SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - LUIZ ROBERTO RESTAURANT SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - MARCOSMOREIRAGOME SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - MASUDA SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - NAGUMO- VILA MAZZ SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - NAGUMO-SUZANO SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - PHARAOAUTOPOSTO SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - RODOANEL SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - SAPOCAR SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - SUPERMERCADO SHIB SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CDB POS DI LIQ. BANCO INTER SA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CIELO VENDAS CRษDITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CIELO VENDAS DษBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COBRANÇA SEGURO PIX - PARA: PAGSEGURO INTERNET INSTITUICAO DE PAGAMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMERCIO DOCES I GOLD EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMISSรO FLAT - COBRANวA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - Assaí', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO ASSAI ATACADISTA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO ATACADO ESPERANCA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO AUTO POSTO KIMURA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO AUTO POSTO RODOANEL LE SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO CEA SUZ 523 ECPC SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO COMERCIAL MITSUHOSHI SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO CONSTRUSERG SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO DOM''C ATELIER SUZANO BRA SOUSPLATS E TAÇAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO GRAN SUZANO AUTO POSTO SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO IFOOD *IFD*ATACADAO VILA YARA O', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO MINUTO PA-0077 SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO PAG*COQUINHO ITAQUAQUECETU BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO PAG*GOLDENPARK SAO BERNARDO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO PUNTO *GRAN SUZANO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO SAHARA SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO SANTA HELENA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO SHOPPING SUZANO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - NO ESTABELECIMENTO SUPERMERCADO DA FREGUE SAO PAUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA CARTAO - gasolina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO 13.518.442 JOSELI APAR OSASCO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO ASSAI ATACADISTA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO AUTO POSTO RODOANEL LE SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO AUTO POSTO RODOANEL SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO AUTO POSTO VILA FIGUEI SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO BENJAMIN SALGADOS SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO BERLINF*AVIGNON COMERC SAO PAUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO BOIZAO GRILL CHURR. SAO PAULO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO BOTECO HELENA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO CONCESSIONARIA SPMAR S ITAPECER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO CONVENIENCIA IMPERIO SAO PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO ECOPISTA FPAY ITAQUAQUECETU BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO ECOPISTAS ITAQUAQUECETU BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO ESTACIONAMENTOS EPARK SAO PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO GRAN SUZANO AUTO POSTO SUZANO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO INSTITUTO GERANDO FALC POA BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO LOJA DONA MARIA VARIE SAO PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO MP *DEGADOBAIANO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO MP *GONCALVES SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO MP *LOJADONAMARIA SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO MP *MAKTUBSUSHIAVENIDA OSASCO B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO MP *SALGADOS SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO MR3 SORVETES SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO NAGUMO- VILA MAZZA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO NN BOLOS LTDA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO NO PRECINHO SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO PADARIA RENASCER SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO PAG*COMERCIODEDOCES SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO PAG*SERGIOSHIGUEO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO PAG*VERDIGALLEFONDUES SAO PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO PERFUMARIA SHN LTDA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO POSTO VILA URUPES SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO PUNTO *RODOANEL SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO QUINTAL DO ESPETO TATU SP BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO RESTAURANTE E LANCHONE SAO PAUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO SANTA HELENA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO SUZAN POINT COMERCIO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO SUZURAN BOMBONIERE SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO SWIFT SUZANO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DEBITO: NO ESTABELECIMENTO TEMPERO MANERO SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DÉBITO - PAG*CENTRALDASCORES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DÉBITO - PAG*DISPEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - COMPRA NO DÉBITO - SUZANMI-BAZAR E PAPELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CONCESSIONARIA SPMAR ITAPECERICA D BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CONCESSIONARIA SPMAR S ITAPECERICA D BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-CLAUDETE ZAPATER TEODORO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-DEUSA APARECIDA VICTORIO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-MARCELIA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-ON BRASIL COMERCIO DE ALIMENTOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-RAIMUNDO NONATO ALVES DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-THIAGO DO NASCIMENTO CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00000000-VANILDA ALVES S JUVINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-AURINO FILHO PEREIRA NOVAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-CAMYLLE CARDOSO DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-LORRAINE NADINE SOUZA DE GODOY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-LUCILENE PALMEIRA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-OSEIAS BELTRAMI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-PATRICIA APARECIDA FERNANDES LOPES DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-PATRICIA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :00360305-RONIELIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :08561701-CHARLENE FERREIRA DE GOIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :08561701-EMERSON ROBERTO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :08561701-GI COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :08561701-GIANE DE MELO MATHEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :09554480-HELDA MARIA DOMINGOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :10573521-ANA PAULA LOPES ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :10573521-EMPREEND PAGUE MENOS SA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :10573521-GILMAR BATISTA NUNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :10573521-JUSSARA PACHECO FALCAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :10573521-PEDRO PAULO SOARES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :14796606-IFOOD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :16501555-ANDEFER COMERCIO DE FERRO E ACO NOVOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :17192451-BIANCA CARDOSO BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :17192451-LAERT ANGELO DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :17192451-MARIA JOSE MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :17192451-SIRLENE DOS SANTOS TEIXEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-ALDIMEIA PEREIRA MENDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-ANA PAULA GOMES PERES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-ANNA BEATRIZ DE CAMARGO LORENA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-BIANCA FRANCO ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-CREUZA MARCIANO DA SILVA SILVERI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-DANILO VIEIRA FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-DEBORA MARIA DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-EDEMILSON DE SOUZA BEZERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-EROTIDES FRANCISCA VIEIRA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-FABIO AUGUSTO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-GABRIEL HENRIQUE CAVALCANTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-GI COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-JULIANA ALVES DE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-KEVIN MATSUMOTO COUTINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-LAURA BEATRIZ AMORIM PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-LIRIS EDIRLE RANGEL ICHIE 26447621896', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-MARIA ELIZABETH PEREIRA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-MARIA SOLANGE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-NATALICE SOUZA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-PRISCILA DE SOUZA KUKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-RITA DE CÁSSIA COELHO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-ROBERTO LANDIM DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-ROSEMEIRE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-SANDRA CRISTINA LEITE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-SARANA DA SILVA PINHEIRO BERTOLLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-SEBASTIANA FERREIRA DA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-SUELEN RIBEIRO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-T. M COMERCIO VAREJISTA DE OTICA SOCI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-VALDINEI VIEIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-VINICIUS DA SILVA SANTOS 47742791889', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :18236120-WELLINGTON BARBOSA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :20855875-DANIELLE PEDROSO GRANSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :22896431-ANGELO MAXIMO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :22896431-DEJAIR BENEDITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :22896431-MARIA DA CONCEICAO XAVIER DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :22896431-MIRIAN MADEIRA DOMINGUES DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :22896431-RENILDA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :31872495-GIOVANNA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :31872495-MARIANA RESENDE DE NOVAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :31872495-SANDRA FARIAS DE FREITAS SANTIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :31872495-VALDINÉIA MOLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :37880206-DENAS REPRESENTACOES LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-ANDREA M N DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-CAMILA RODEIGUES BARBALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-CLAUDIO KATSUHIRO SAMESIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-FLAVIO RODRIGUES GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-GILMAR JOSE DE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-GRAZIELI ELIZIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-GUACIARA GALLATI DE LIMA VEIGA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-JOAO VICTOR OLIVEIRA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-KETTELYN ARAUJO DE OLIVEIRA DA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-LOURIVAL BORGES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-LUANA KARINE IKARI SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-MARCO ANTONIO ALVES DO AMARAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-MONICA MIYASHIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-PET CENTER COMERCIO E PARTICIPACOES S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-RODRIGO FELIX S S 36534033836', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-ROSELI RAMOS DO AMARAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-TAIANE SILVA SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60701190-ZILDA SILVA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-CREDZ S.A INSTITUICAO DE PAGAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-FABIANA CHAVES DE PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-GIOVANNA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-JONATHAN SANTOS DE FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-MARIA DE FATIMA FIGUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-RAQUEL MANDES DE MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :60746948-VALERIA BUCZEK BITTAR FONSECA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-BONIFACIO DA SILVA PAIVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-CLINICA ODONTOLOGICA SUZANO LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-DANIELE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-EDUARDO PEZZUOL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-FERNANDA SILVA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-FPS COMERCIO DE PRESENTES LTDA EPP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-GISELE CALADO LESSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-KATHLEEN DE ALMEIDA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-KAWANY CHAVES DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-KELVIN BEN BERTOLLA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CP :90400888-MARIA DA CONCEICAO MARTINS', 'juridica', NULL, True, NOW(), NOW());
