INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Maria da Conceição Ramos de Moura 102.281.264-52 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mariana Brandão Almeida (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Melissa Ketelyn Sanches de Oliveira (divulgadora, ref. o dia trabalhado ) > PIX: ketelynmelissa196@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (bilhete QR code) > ref. ida/volta Sygma > PIX: 537.903.908-10 (CPF - Aline)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (bilhete único - ida/volta para laboratório e Mauá))', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (bilhete único - laboratórios)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (bilhete único)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (bilhete único) - ida para Só Blocos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (bilhete único) - ida/volta Express', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (diferença)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (ref. ) ~ Barueri', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes (ref. 29/04 ~ ) > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes > PIX: 11945888760 mudou, cuidado!!!!', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Miriam Ferreira Sanches', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Mirian Ferreira Sanches (adiantamento ref. 07/11 a 10/11)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Monica Suellen (adiantamento de vale transporte, ref. 16/11 a 17/11)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho (ref. 24/01 - 30/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da SIlva (ref. ida e volta - HighVision', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (2 onibus e 1 trem)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (2 trems)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (SUZANO I) > PIX: (11) 9 5328- 7646 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (bilhete único)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (bilhete único) > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (bilhete único) > PIX: 490.832.378-00 (CPF) - diferença de vale transporte usado a mais para realizar entrega na casa do cliente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (bilhete único) > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (diferença) > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (moedas do escritório) > PIX: (11) 9 5328- 7646 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (ref. armações para Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva (ref. entrega de óculos)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva - Laboratório dia 06/03, 13/03 e 27/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva - ONIBUS RIO PEQUENO SABÁDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva - ida e volta express', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) - DN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva( ida e volta ao laboratórios)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva( ida e volta em são mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva( ida na espeed e ida na só blocos)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva( ida na solótica e hivision)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva(Mauá)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicolas Coutinho da Silva) entregar de pedido em mogi)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Nicollas Henrique (ref. ) ~ Mauá', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Normando Ferreira da Silva Filho (ref. 26/08 - ) > PIX: (13) 9 8599-1407 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Patrícia Henrique de Souza (divulgadora, ref. 22/08-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Paulo Sérgio Bueno Junior (ref. 08/04 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Pedro Henrique Armiliato dos Santos (ref. 07/01 - ) > PIX: silped213@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Pâmela de Oliveira Santos (ref. 27/06~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rafaela > PIX: krafaela409@gmail.com (e-mail) > (ref. dias trabalhados 23/11 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Robson Luiz (ref. 16/02 e 17/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Robson Luiz Alves dos Reis', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais (diferença do mês) > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais (diferença, ref. Perus ~ 19/01 - ) > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais (diferença, ref. as idas e vindas Suzano~São Mateus) > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais (diferença, ref. ida e volta 3x > catraca) > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais (ref. 14/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail) ~ Ida para Mauá >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rogério Martins dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rosana Lucas dos Santos (ref. ) > PIX: 182.894.078-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rosana Lucas dos Santos (ref. - ) > PIX: 182.894.078-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rosana Lucas dos Santos (ref. 03/01 - ) > PIX: 182.894.078-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Rízia Sulamita Nakashima Lopes (auxiliar de loja, ref. os dias trabalhados 17/09 - ) > PIX: (11) 9 5947-5520 (celular) -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Samuel Henrique da Silva (ref. 09/05 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Sandy Cristina da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Stefany Rayne Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Stephane Soares Lima', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Stephane Soares Lima (Ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Tamirys Gabriele (ref. 04/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Tamirys Gabriele (ref. 05/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Tatiana Mello (lojas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Tatiana Mello (ref. ~ RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Tatiana Mello (ref. ~ São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Tatiana e Junior (ida e volta - 25 de Março)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Taty (ida/volta para São Paulo)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Taty (volta)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Taty e Giovanna', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira (diferença ~ 02/06 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira (diferença ~ 26/05 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira (ref. 02/06 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira (ref. 14/05 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira (ref. 19/05 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira (ref. 26/05 - ) > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Thiago Vinicius Andrade Siqueira > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail) - (ref. - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail) - ref. > Campanha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vanessa Santana Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vanessa Santana Ribeiro (adiantamento, ref. 02/03 ~ 07/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vanessa Santana Ribeiro (ref. 12/01 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vitória Regina Nunes da Conceição', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vitória Regina Nunes da Conceição (ref. 28/01-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Vivian Maria (ref. 03/10 a 07/10)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Weligton Monteiro (divulgação, ref. 28/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Wellen Santos Silva (adiantamento, ref. 12/07 ~)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Wemilly Maria (divulgação, ref. 28/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Wevilly de Souza Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Wevilly de Souza Fernandes Líbano (diferença, ref. Perus ~ 19/01 - ) > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: William (ref. 15/08~21/08) > PIX: 430.482.058-37 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: William (ref. 23/08~25/08 e 31/08) > PIX: 430.482.058-37 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: William (ref. 26/08~30/08) > PIX: 430.482.058-37 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin Castilho Ferreira da Silva (auxiliar de loja, ref. 19/02 - ) > PIX: yasmincastilho2208@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin Emanuela Costa de Souza > PIX: costacarina148@gmail.com (e-mail) - (ref. dias trabalhados 18/10 e )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin Emanuela Costa de Souza > PIX: costacarina148@gmail.com (e-mail) > (ref. dias trabalhados 01/11 e )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin Santos (ref. São Mateus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin da Silva Costa dos Santos (diferença a pagar, ref. nov/2022 ~ dez/2022 - Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Yasmin dos Santos (ref. 07/12 - condução Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Zaine de Lima Siqueira (diferença, ref. Mauá)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Érika Oliveira > PIX: 481.332.818-06 (CPF) > ref. 28/09 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRASNPORTE: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE: Ana Cristina Rodrigues Amancio > PIX: (11) 9 4132-7245 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE: Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALMIR MUNIZ: ARMÁRIO - LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VICENTE DE PAULO FERNANDES DE ALMEIDA: Saco de lixo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VILA PERUS LAR & CONSTRUCAO: Desentupidor para sanitário e soda cáustica', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VILA PERUS LAR & CONSTRUCAO: Extensão > Cleberson > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VILLA BEST FOOD RESTAURANTE LTDA: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIP TELECOM 484542 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIRAL GIRLS MODAS (compra de roupas para divulgadora Wemilly)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 1/3 - PIX 34.130.608/0001-52', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 1/3 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 1/4 > PIX: 34.130.608/0001-52 (CNPJ) REF : 3162,55', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 1/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 2/3 - PIX 34.130.608/0001-52', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 2/3 > PIX 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 2/3 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 2/4 > PIX: 34.130.608/0001-52 (CNPJ) REF : 3162,55', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 2/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 3/3 > PIX 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 3/3 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 3/3: Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 3/4 > PIX: 34.130.608/0001-52 (CNPJ) REF : 3162,55', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 3/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 4/4 > PIX: 34.130.608/0001-52 (CNPJ) REF : 3162,55', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 4/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 5/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 6/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 7/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME - Parcela 8/8 > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Créditos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: (11) 9 8194-9317 (celular) > NUBANK - Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS 10345 - Eduardo Adriano > Poli Foto Blue com AR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS 1076', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS 4649', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS''s 10361, 10388 e 10413', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS''s 10563, 10564, 10606, 10607, 10621 e 10622', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS''s 4759 e 4760', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS''s: 10152 e 10153', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS''s: 10152 e 10153 (NUBANK - Taty)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. OS: 1047 (NUBANK - Taty)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > Jéssica Paschoalini > PIX: 230.032.638-89 (CPF) - ref. Uber Flash (entrega das lentes)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 34.130.608/0001-52 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 34.130.608/0001-52 (CNPJ) - NUBANK ~ Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 34.130.608/0001-52 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11323', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11324', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11325', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11326', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11404 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11404 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11405', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11479', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11503', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11510', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11525', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11526', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11535', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11541', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11595', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11598', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11599', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11610', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11611', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11641', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11697 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11697 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11714', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11715', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11822', 'juridica', NULL, True, NOW(), NOW());
