INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARILU SENZIALI FLOR OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARINA SANTANA CAMARGO F SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARINEIA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARINEIA DE SOUZA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIO MIRANDA DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARIO ROSA LIMA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARISA A BATISTA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARISA DE ARAUJO BATISTA DA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARLI FERREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARLI FERREIRA FRANCO ISABEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARTA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARTA VAZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARY HELLEN AMANCIO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MARÍA SANDRA DA SILVA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MATEUS DA SILVA CAVALCANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MATEUS DOS ANJOS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MATHEUS CHAVES HILBERT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MATHEUS VIEIRA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAURICIO MONTEIRO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAURILIO SANTOS AUGUSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAURO ROBERTO AMARO DE MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAYCON SANTOS PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MAYME SANTOS DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MESSIAS JACOB ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICAELE APARECIDA DOS SANTOS GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHAEL BRENDEL VIEIRA CARMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHAELLA DA SILVA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHELE DOS SANTOS FONSECA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHELE FABIAN TORELLI DO NASCIMENTO BEZERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHELE MARIA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHELE RODRIGUES SAITU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MICHELLE ABDALLA PRADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MIGUEL JESUS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MILEIDE CRISTINA ABADIA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MILTON DONIZETE COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MIRIAN ARCANJO DE MACENA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MIRIAN DE SOUZA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MISLENE ALVES CORREIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MOISES LOPES MACHADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MONETI APARECIDA FERREIRA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MONICA CRISTINA GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MONICA MIYASHIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MONIQUE FERREIRA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - MÁRCIA FERREIRA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NAILSON FERREIRA DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NAIR APARECIDA DE SOUZA RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NATANAEL ANTUNES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NATIELLY DOS SANTOS ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NAYANE DE ARAUJO SILVA MENDES MAGNESI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NEIDE MARIA MENDES ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NELITO AUGUSTO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NELSON ANISIO SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NELSON DE SOUZA JARDIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NELY MARIA DA MATA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NICOLAS COUTINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NIVALDA RABELO DAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NOEMIA ALVES PATRÍCIO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - NUTRI CARNES COMERCIO DE CARNES E DERIVADOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ODILIA BRAZ DE ANDRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - OLIVIA DOS SANTOS ROCHA SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - OSNEI FERNANDO PALADINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - OSWALDO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - OTICAS TATY MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PABLO ROMEU ROCHA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PALOMA ARAUJO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PALOMA DE SOUSA CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PALOMA DOMINIQUE FERNANDES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PALOMA DUARTE ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PALOMA THAINA LEONALDO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PAMELA PACIFICO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PASTELARIA DO CEARA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA APARECIDA FERNANDES LOPES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA DA SILVA LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA DE FATIMA PRAZERES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA HOMAN LEMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA PACIFICO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA PAULINO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRICIA SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRÍCIA BORGES FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PATRÍCIA CURTO FONTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PAULA ROCHA ABADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PAULA VITORIA OLIVEIRA RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PAULO MARCOS DE CARVALHO ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PAULO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PEDRO ALVES DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PEDRO BRITO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PEDRO DANILO BARBOSA DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PETER DA COSTA ANDRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PETRUCIO AVELINO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PRISCILA DE SOUZA KUKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - PRISCILA GONÇALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - QUEREEN SANTOS DE MELLO SARMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAABE DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAIRA LIMA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAISSA MILENA SIQUEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAIZA ARAÚJO DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAMON FERRAMOSCA MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAQUEL DANTAS DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAQUEL DIOGO ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAQUEL MENDONCA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAQUEL PIRES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RARIANE FERREIRA TELES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RARIANE FERREIRA TELES DE ALCANTARA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAUL FELIPE ALVAREZ MUNOZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAYANE SANTOS LIMA RIBEIRO BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RAÍSSA APARECIDA PREVIATO PAULINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REGINA APARECIDA P GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REGINA CUSTODIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REGINALDO MAGALHAES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REINALDO ROMAGNOLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REINARA PRAXEDES SINISCALCHI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REINARÁ PRAXEDES SINISCALCHI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - REJANE DA SILVA MORAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RENAN NAZARO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RENILZA DA SILVA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RICARDO CAMPANI PIRES BASTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RICARDO ROSA PASSOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RICARDO VIEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RICHARD AUGUSTO DE CAMPOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RITA DE CASSIA CARDOSO LANDIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RITA DE CASSIA DE SOUZA FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RITA DE CÁSSIA COELHO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBERT LAHUERTA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBERTO LANDIM DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBERTO MARCOS BARBOSA DE BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBERTO RODRIGUES MORATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBSON RODRIGUES PEGO 23344197886', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBSON SILVA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROBSON SOUZA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RODOLFO CALASANS PALANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RODOLFO SILVA AMORIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RODRIGO SILVA DE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROGENVAL FARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROGERIO APARECIDO DE MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROGERIO FAUSTINO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROMULO FREITAS CUNHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONALDO DEL-FIOL MODOLO JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONALDO DOS SANTOS BENEDITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONALDO KESLER LAHUERTA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONALDO MENESES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONIELIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONIELIA DA SILVA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RONIVALDO PEREIRA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSA MARIA MARTINS SOUSA REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSALVO LOPES GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANA GLESIA RODRIGUES LEITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANGELA APARECIDA DEJANE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANGELA CELESTINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANGELA DA SILVA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANGELA DOS SANTOS MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANGELA MENDES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSANGELA MORAIS DIAS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSELI APARECIDA SILVA CAVALCANTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSELI VIEIRA RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSEMEIRE SANT ANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSILEIDE SOUZA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROSÂNGELA MARIA DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - ROZILEIDE BRITO RIBEIRO DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RUTH COSTA ASSUNÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RUTH PINHEIRO GARCEZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - RUTI ELIAS DOS SANTOS LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SABRINA DA SILVA CAMPOS ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SABRINA XAVIER DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SALMIR FERNANDES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SAMIRA DE OLIVEIRA GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SAMIRA DE OLIVEIRA GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SAMUEL APARECIDO DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SAMUEL APARECIDO DE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SAMUEL DE BARROS RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SAMUEL SILVA FELIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SANDRA DIAS ANDRADE SANT ANNA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SANDRA FARIAS DE FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SANDRA FERNANDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SANDRA MARIA ALVES PASSOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SANDRA MARIA MALTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARA DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARA DE AMORIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARA PATROCINIO GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARA RAQUEL SANTOS OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARA REGINA CORREA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARA ROCHA DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARAH DE ALMEIDA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARAH VICTORIA DOS S GARCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SARANA DA SILVA PINHEIRO BERTOLLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SEBASTIANA DOS SANTOS GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SELMA BORGES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SELMA MIRANDA DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SERGIO CHAGAS DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SERGIO ROBERTO DE SOUZA AGUIAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SHIRLEY RIBEIRO DE SOUZA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SIDILAINE APARECIDA DE PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SIDNEI ROQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SILAS DIEGO DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SILAS FRANCISCO DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SILAS RODRIGUES FARNEZI JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SILVANA MENDES CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SILVANA RODRIGUES HIRASAKA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - SILVANI FATIMA B MESQUITA', 'juridica', NULL, True, NOW(), NOW());
