INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Pix-Recebido QR Code27/07 13:33 00034567484851 Paulo Henri', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code27/09 17:21 00007393777878 SILVIA REGI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code27/10 11:48 00006586540470 MARIA NAZAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code27/12 15:50 00033886052893 PAULO DA PA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code28/07 16:52 00005596094854 Valdivo per', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code28/10 15:29 00022183729830 LILIA CAMBU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code28/11 17:04 00042783132842 THAYS CAROL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code29/09 12:19 00001681848503 JUSSIARA LO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code29/11 11:12 00022931640808 WILLIAM GAB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code29/11 13:47 00028743086845 ROSANGELA M', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code29/11 17:10 00048779236839 Daniela Gon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code29/11 17:11 00048779236839 DANIELA GON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code30/01 14:42 00038528149870 DANIELLE PE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code30/07 15:31 00046505568808 Gabriel Lui', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code31/01 09:19 00047351648808 NATALIA MAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pix-Recebido QR Code31/01 18:09 00012927027889 ANDRE LUIZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pro-Labores', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pro-Labores (Detergente, filtro de papel e sabão em pó)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pro-labores', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Prêmio para Jocicreide', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PÃO FRANCÊS > Mike Rodrigues > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PÃO: Ariani Dias', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PÃO: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PÃO: Vanessa Santana Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PÃO: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pães festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pães festa Nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'QUALICLINICA POPULAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'QUINTAL DAS PLANTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'QUITANDINHA DA GENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'R C P FARMACIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RAD BRASIL: Compra de estojos > PIX: (11) 9 6435-8470 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RAD BRASIL: Compra de flanelas > PIX: (11) 9 6435-8470 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RAIA 230', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECARGA DE CARTÃO PRÉ-PAGO - MASTERCARD FINAL 6092', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECARGA DE CELULAR - TIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECEBIMENTOS DE CARTÕES, DIFERENÇA DAS TAXAS - CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECEBIMENTOS DE CARTÕES, DIFERENÇA DAS TAXAS - CREDZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECEBIMENTOS DE CARTÕES, DIFERENÇA DAS TAXAS - PAGBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECEBIMENTOS DE CARTÕES, DIFERENÇA DAS TAXAS - SUMUP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RECEBIVEIS DE VENDA - CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REDE PAPA 8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Emerson William da Silva Santos Banco', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Felipe Roger Miranda > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF) 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF) ~ (diferença a pagar)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Rosangela Aparecida DEjane Felisbino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Rosangela Aparecida Dejane Felisbino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Wevilly de Souza Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Zaine de Lima Siqueira Ba', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFLEXO DE COMISSÕES DSR:Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFORMA NAS LOJAS: José Hilton Gonçalves Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REFRIGERANTE COCA COLA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REGINALDO DONIZETE: 02 cadeiras giratórias', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REGIS COMÉRCIO DE ÓCULOS: COMPRA DE ACESSÓRIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REGISTRO PONTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REND PAGO APLIC AUT APR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'REND PAGO APLIC AUT MAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 1/9 > PIX: 46.081.461/0001-37 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 2/9 > PIX: 46.081.461/0001-37 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 3/9 > PIX: 46.081.461/0001-37 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 4/9 > PIX: 46.081.461/0001-37 (CNPJ) - ref. Coluna', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 5/9 > PIX: 46.081.461/0001-37 (CNPJ) - ref. Lensômetro Digital VIsion - mod.: TL 6500', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 6/9 > PIX: 46.081.461/0001-37 (CNPJ) - ref. Lensômetro Digital VIsion - mod.: TL 6500', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RENEGOCIAÇÃO: FOCO OPTOMETRIA - Parcela 7/9 > PIX: 46.081.461/0001-37 (CNPJ) - ref. Lensômetro Digital VIsion - mod.: TL 6500', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Cristina Rodrigues Amâncio - Acordo 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Cristina Rodrigues Amâncio - Acordo 1/3 > PIX: (11) 9 4132-7245 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Cristina Rodrigues Amâncio - Acordo 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Cristina Rodrigues Amâncio - Acordo 2/3 > PIX: (11) 9 4132-7245 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Cristina Rodrigues Amâncio - Acordo 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Cristina Rodrigues Amâncio - Acordo 3/3 > PIX: (11) 9 4132-7245 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Acordo 1/5 > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Acordo 2/5 > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ariani Dias Fernandes Líbano - Acordo 1/6 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ariani Dias Fernandes Líbano - Acordo 2/6 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ariani Dias Fernandes Líbano - Acordo 3/6 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ariani Dias Fernandes Líbano - Acordo 4/6 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Ariani Dias Fernandes Líbano - Acordo 5/6 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Bruno Henrique Simão - Acordo 1/5 > PIX: henriqueferrarib@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Bruno Henrique Simão - Acordo 2/5 > PIX: henriqueferrarib@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Bruno Henrique Simão - Acordo 3/5 > PIX: henriqueferrarib@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Bruno Henrique Simão - Acordo 4/5 > PIX: henriqueferrarib@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Bruno Henrique Simão - Acordo 5/5 > PIX: henriqueferrarib@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Camila Faccin Vieira - Parcela 1/2 > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Camila Faccin Vieira - Parcela 2/2 > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Cleberson Ribeiro de Jesus - Acordo 1/6 > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Cleberson Ribeiro de Jesus - Acordo 2/6 > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Cleberson Ribeiro de Jesus - Acordo 3/6 > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Cleberson Ribeiro de Jesus - Acordo 4/6 > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Cleberson Ribeiro de Jesus - Acordo 5/6 > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Cleberson Ribeiro de Jesus - Acordo 6/6 > PIX: ribeirocleber704@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: DIvulagadoras Patrícia > PIX: (11) 9 5369-8413 (celular) - Larissa Marques', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Débora Lemes Siqueira > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eliana Savoia - Acordo 1/6 > PIX: 276.526.448-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eliana Savoia - Acordo 2/6 > PIX: 276.526.448-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eliana Savoia - Acordo 3/6 > PIX: 276.526.448-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eliana Savoia - Acordo 4/6 > PIX: 276.526.448-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eliana Savoia - Acordo 5/6 > PIX: 276.526.448-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eliana Savoia - Acordo 6/6 > PIX: 276.526.448-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 1/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 10/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 2/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 3/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 4/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 5/10 > PIX: (11) 9 7176-5828 (celular) + de moedas quer estavam paradas no escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 6/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 7/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 8/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Emerson William da Silva Santos - Acordo 9/10 > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 1/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 2/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 3/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 4/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 5/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 6/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 7/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 8/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda - Acordo 9/9 > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Felipe Roger Miranda > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Igor Nascimento Medeiros- Acordo 1/3 > PIX: igormeirells203@gmail.com (E-MAIL)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Igor Nascimento Medeiros- Acordo 2/3 > PIX: igormeirells203@gmail.com (E-MAIL)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Igor Nascimento Medeiros- Acordo 3/3 > PIX: igormeirells203@gmail.com (E-MAIL)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 1/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 10/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 11/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 2/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 3/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 4/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 5/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 6/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 7/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 8/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Jocicreide Macedo Barbosa Santos - Acordo 9/11 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 1/7 > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 2/7 > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 3/7 > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 4/7 > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 5/7 > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 6/7 > PIX: 551.651.198-40 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kathleen dos Santos Campos - Acordo 7/7 > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Keren Anacleto de Souza - Acordo 1/4 > PIX: (11) 9 6336-2536 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Keren Anacleto de Souza - Acordo 2/4 > PIX: (11) 9 6336-2536 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Keren Anacleto de Souza - Acordo 3/4 > PIX: (11) 9 6336-2536 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Keren Anacleto de Souza - Acordo 4/4 > PIX: (11) 9 6336-2536 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kethelyn Miranda - Acordo 1/4 > PIX: PIX: 508.457.918-26 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kethelyn Miranda - Acordo 2/4 > PIX: PIX: 508.457.918-26 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kethelyn Miranda - Acordo 3/4 > PIX: PIX: 508.457.918-26 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Kethelyn Miranda - Acordo 4/4 > PIX: PIX: 508.457.918-26 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Lara Silva Wingeter de Souza - Acordo 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Lara Silva Wingeter de Souza - Acordo 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Lara Silva Wingeter de Souza - Acordo 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 1/13 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 2/13 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Larissa Dias Fernandes Cardozo - Acordo 3/13 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Letícia Morais Domingos - Acordo 1/3 > PIX: 496.272.188-71 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Letícia Morais Domingos - Acordo 2/3 > PIX: 496.272.188-71 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Letícia Morais Domingos - Acordo 3/3 > PIX: 496.272.188-71 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 1/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 10/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 11/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 12/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 13/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 2/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 3/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 4/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 5/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 6/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 7/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 8/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria Elizabeth Pereira do Nascimento - Acordo 9/13 > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria da Conceição Ramos de Moura - Acordo 1/2 > PIX: 102.281.264-52 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Maria da Conceição Ramos de Moura - Acordo 2/2 > PIX: 102.281.264-52 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Mike Rodrigues Gomes - Acordo 1/7 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW());
