INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'LIMPEL COMERCIO DE EMBALAGENS: Talão de recibo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL COMERCIO DE EMBALAGENS: Água sanitária', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Copo descartável', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Desinfetante 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Papel higiênico e papel interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Papel interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Sacola Kraft', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Sacolas Kraft', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEL EMBALAGENS: Água sanitária', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEZA DA LOJA: Faxineira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEZA DA LOJA: Rosimeire Farias da Silva (ref. ) > PIX: (11) 9 1677-3502 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIMPEZA DA LOJA: Vitoria Mendes da Silva (ref. ) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LINHO FINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LITORAL PARK ADMI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIVRO ÓPTICO: Vivian Maria', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIVRO ÓPTICO: Vivian Maria Ramos > PIX: 309.167.958-61', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LMK MICROFIBRAS EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Aromatizante, copos descartáveis e parafuso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Açúcar refinado, álcool, copo descartável, desinfetante, filtro de papel, papel higiênico e saco de lixo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Copo descartável', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Cordão prolongador, filtro de linha e pilha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Desinfetante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Garrafa Paris 1,9L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Papel sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Rodo borboleta', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Saco branco', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Super bonder > Rosangela > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Água lindoya e folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Água lindoya, aromatizante, balde 27L, bala de café, bala de canela, bolo, papel higiênico, pirulito, sabonete líquido, sacos para lixo, suco 1L, talher e toalha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA VARIEDADES: Água sanitária e aromatizante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJA DONA MARIA: Alcool líquido e aromatizante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS AMERICANAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Adesivo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Caderno', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Coca cola', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Copo descartável e folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Folha sulfite > Jocicreide > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Sabonete líquido', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS KING: Álcool em gel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS MEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOJAS RENNER FL 1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LOM E SERV. DE INFO LTDA - ME: Cópias (30 uni)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LORENA THIFANY PRIMO DINIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUAN ENFEITES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUAN ENFEITES LTDA: Bexiga lisa e balão metalizado', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUAN ENFEITES LTDA: Bexigas lisas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUCILENE PALMEIRA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUCIMAR TOLEDO LIMA VAZ - EPP: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUCIMAR TOLEDO LIMA VAZ - EPP: Pão francês > Thiago Yuri da Silva Yuki > PIX: yuricomercial@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUIZ MASAKAZU TATEISHI ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LUMMAR TAMBORE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Laisa Kroli - pix: 35825845852', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lançamento a maior - HASTEN MARKETING E PRODUÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lançamento parcial - B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lançamento parcial - FRANQUIA > PIX: (11) 9 8117-7178 (celular) - PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lançamento parcial - HASTEN MARKETING E PRODUÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Locação Ana Bia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lojas King : Pacote de folha sulfite > Nicolas Coutinho > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lubrificação das portas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Lubrificação das portas (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Luiz Geraldo - Pix: 16681094848', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'M A L U CACAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MAGALU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MAGAZINE E ARMARINHO CASA DA MAMAE: Clipes e grampos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MAKIS PLACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 01/02 19:39 TELHA NORTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 04/02 14:33 TELHA NORTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 05/11 16:51 SASAKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 05/11 16:56 SASAKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 09/03 11:33 SODIMAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 09/03 11:44 FINAMIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - 19/03 14:20 SODIMAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - AGUINALDO (TÉCNICO): COMPUTADOR DE TELEMARKETING - PARCELA 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - AGUINALDO (TÉCNICO): COMPUTADOR DE TELEMARKETING - PARCELA 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - AGUINALDO (TÉCNICO): COMPUTADOR NOVO - PARCELA 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - ALBA CHAVEIRO: CHAVE TETRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - CASA DE SALGADOS DEUS É FIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - CHAVEIRO MEDEIROS: DUAS CÓPIAS DE CHAVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - COMERCIAL MD SUZANO BRA,', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - ELETRICA SAO PAULO SUZAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - ELETRO HIDRAULIC SUZAN S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - ELÉTRICA SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - ENGRAXE DAS PORTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - IGOR PEREIRA SOUZA: TAPETE PARA A LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - LIMPEZA E GRAXA NAS PORTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - LUBRIFICAÇÃO DAS PORTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - NC COMÉRCIO DE EQUIPAMENTOS CONTRA INCÊNDIO LTDA ME: TROCA DE EXTINTORES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - RIPÃO DE 3M', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO - TROCA DAS CORREDIÇAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DA LOJA: Nilton Aparecido Gama', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DAS CADEIRAS: Consertos das cadeiras giratórias do escritório - Reginaldo Donizete > PIX: (11) 9 7684-1836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DAS CÂMERAS: Edinilson Tavares Costa Pereira > PIX: (11) 9 4977-9528 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DAS PORTAS - Suzano I: Luis da Silva > PIX: (11) 9 9874-3936 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DAS PORTAS - Suzano I: Wendell Sene Leandro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DAS PORTAS DE AÇO: Sergio Antônio da Silva > PIX: (11) 9 1684-3402 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DO CARRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DO CARRO (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DO CARRO (parte mão de obra)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO DO CARRO (peças)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO ELÉTRICA: Nicolas Emanuel Milantez > PIX: 449.610.918-20 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MANUTENÇÃO: Retirada de grama da entrada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 01/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 01/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 02/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 02/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 03/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 03/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 04/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: EMBALAGENS - PARCELA 1/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 1/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 2/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 3/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 3/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 4/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 5/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 6/7 pix: 21.508.278/0001-44', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARCELLY: Embalagens - Parcela 7/7 - pix: 21.508.278/0001-44', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARIA DORES SILVA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARIANA ALVES DE SÁ: Desinstalação de ar condicionado', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARQUES E ARAUJO COMERCIO: Biscoito, bolacha e doces (Café especial para o dia das mães, ref. 13/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MARQUES E ARAUJO COMERCIO: Refrigerante (Café especial para o dia das mães, ref. 13/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MASSAMBANI MODA G', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MATERIAL DE CONSTRUÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MATERIAL DE ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MATERIAL ESCOLAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MATERIAL PARA ARRUMAR BANHEIRO DA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MATSUMOTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MATSUMOTO - NAZIH', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MAURICIO NOBUMASS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MC DONALDS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MC DONALDS: Lara Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MD MATERIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MD Materias p/ construção : Thinner, massa corrida e vassoura > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MEGA SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MEGA SUCO: Larissa Dias', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MEGA SUCO: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MEL SHOP VARIEDADES: Fonte telefone', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELHOR DAS CASAS: Durex > Larissa Dias > PIX: larissadiss766@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA - Parcela 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA - Parcela 3/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA - Parcela 4/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA - Parcela 5/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA: COMPRA DE EQUIPAMENTOS - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA: Compra de equipamentos - Parcela 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA: Copo descartável e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA: Itens para a loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA: Margarina e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA: Mortadela, pão francês, queijo e suco líquido', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA: Mortadela, pão francês, queijo prato e suco integral', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Biscoito, bolacha, casadinho, doce de leite, maionese, sardinha enlatada e suco', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Café', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Café, pão francês e rosquinha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Genérico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Margarina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Pão francês e papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMPRAS: Álcool e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADINHO VALE DAS COMRPAS LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - 21/12 11:16 COMERCIO DE DOCES IM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - 23/12 15:58 COMERCIO DE DOCES IM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - 23/12 16:28 D B L COM DE DESCART', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ACF EMPÓRIO DO REAL UTILIDADES: AÇÚCAR, CAFÉ E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ACF EMPÓRIO DO REAL UTILIDADES: PÃO DE FORMA E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ACF EMPÓRIO DO REAL UTILIDADES: REFRIGERANTE KUAT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ASSAI ATACADISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ASSAI ATACADISTA SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ASSAÍ ATACADISTA: PRODUTOS PARA A LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - AÇÚCAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - AÇÚCAR E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - AÇÚCAR, CAFÉ E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - BISCOITO ADRIA AGUA E SAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - BISCOITO RECHEADO, MORTADELA, BOLO DE CHOCOLATE E PÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - BMP UTILIDADES DOMÉSTICAS S. A.: REFRIGERANTE KUAT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - BOLO DE LIMÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - BOLO SIMPLES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - BUCHA DE LOUÇA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ 3 CORAÇÕES, SUCO EM PÓ TANG E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA MANHÃ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA MANHÃ E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA MANHÃ E PRODUTOS DE LIMPEZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA MANHÃ ESCRITORIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA MANHÃ/COMPRAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA MANHÃ: PÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ DA TARDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - CAFÉ E PÃO', 'juridica', NULL, True, NOW(), NOW());
