INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Capital de Giro - Parcela 19/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 2/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 2/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 2/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 2/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 20/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 20/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 20/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 21/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 21/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 21/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 22/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 22/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 22/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 23/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 23/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 23/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 24/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 24/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 25/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 26/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 27/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 28/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 29/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 3/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 3/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 3/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 3/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 30/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 4/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 4/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 4/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 4/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 5/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 5/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 5/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 5/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 6/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 6/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 6/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 6/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 7/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 7/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 7/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 7/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 8/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 8/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 8/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 8/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 9/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 9/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 9/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 9/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 9/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Carregador de celular - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cartão de Todos - Mauá', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cartão de Todos - Perus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cartão de Todos - Rio Pequeno', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cartão de Todos - Suzano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cartão de Todos - São Mateus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cesto De Roupa Suja Dobrável Organizador 3 Compartimentos Cor Preto/b', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cesto De Roupas Bambu Organizador Multiuso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Chocolate para divulgadora: Alessandra', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cielo Vendas Crédito', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cielo Vendas Débito', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cobrança de I.O.F.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Combustível - COMPRA CARTAO - NO ESTABELECIMENTO PAG*PORTALDEPOAAUTO POA BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Combustível para festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Comissão Giovanna', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Comissão errada da Zaine - PIX ENVIADO - CP :18236120-ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parc. 1/4 - Calção do Aluguel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parc. 2/4 - Calção do Aluguel _ pix: (11) 9 6930-7417', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parc. 3/4 - Calção do Aluguel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parc. 4/4 - Calção do Aluguel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 1/6 (Renegociação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 2/6 (Renegociação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 3/6 (Renegociação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 4/6 (Renegociação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 5/6 (Renegociação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 6/6 (Renegociação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 7/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 7/11 - 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 8/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 8/11 - pix cliente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra da loja - Óticas Taty Mello: Parcela 8/11 - pix cliente depositou na Macedo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de 2 parafusos e uma plaqueta para acetato', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações - Kebin Lin', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações SOLARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 01 armações - valor 16,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 01 armações - valor 20,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 01 armações - valor 25,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 01 armações - valor 26,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 01 armações - valor 30,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 02 armações - valor 20,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 02 armações - valor 9,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 02 óculos de segurança - valor 50,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 03 armações - valor 15,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 03 armações - valor 25,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 04 armações - valor 10,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 05 armações - valor 30,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 05 armações - valor 38,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 06 armações - valor 12,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 06 armações - valor 29,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 07 armações - valor 12,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 07 armações - valor 14,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 07 armações - valor 28,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 1 armações - valor 23,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 1 armações - valor 28,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 1 armações - valor 30,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 1 armações - valor 32,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 1 armações - valor 35,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 1 armações - valor 38,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 13 armações - valor 28,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 13 armações - valor 5,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 14 armações - valor 12,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 16 armações - valor 12,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 17 armações - valor 10,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 18 armações - valor 14,90,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 18 armações - valor 16,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 19 armações - valor 15,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 2 armações - valor 15,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 2 armações - valor 35,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 2 armações - valor 38,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 20 armações - valor 6,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 24 armações - valor 7,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 3 armações - valor 12,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 3 armações - valor 19,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 3 armações - valor 20,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 32 armações - valor 5,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 40 armações - valor 5,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 40 armações - valor 7,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 40 armações Loja suzano - valor - 7,90', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 62 armações - valor 18,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 7 armações - valor 18,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 8 armações - valor 20,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário - 8 armações - valor 6,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário -1 armações - valor 18,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário -1 armações - valor 20,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário -1 armações - valor 30,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário -2 armações - valor 25,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário -2 armações - valor 35,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário -8 armações - valor 35,00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Armações receitoário e solares', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de Produtos de limpeza p/loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de armações (receituários e solares)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de bobina para o escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de celular para Telemarkting', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de celular para a Cobrança', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de cordão de nylon preto grande, capinha sunglass e fita pvc cristal', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de mateal de limpeza para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de materiais para o Escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de pão (loja)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de utencilios para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra de utincilios: Margarina e Água sanitátia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra no débito - Nawate', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra no débito - Soft Pel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra supermercado ASSAI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compra supermercado para festa 14/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compras Nagumo - COMPRA CARTAO - NO ESTABELECIMENTO NAGUMO- VILA MAZZA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compras de casa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Compras para festa 14/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00019 0132350521 RAISSA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00019 0183170040 FABIANA PACINI PEREIRA FRANCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00019 0214084671 MARIE GERMAINE BELLAMY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00019 0269152024 LAURA CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00019 0298638037 GIGI C V O LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00:29 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 00:53 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 01:02 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 01:04 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 01:17 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 01:19 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 02:01 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 02:10 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 02:11 DEPÓSITO DE VENDAS VENDAS DEPÓSITO INFINITEPAY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - 033 207 10418715 GABRIELA FERREIRA CONDINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ALTAIR BARBETA MORIYASU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - AMANDA RODRIGUES PICCINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ANA CAROL PANTALENA YOSHIMATSU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ANA CAROLINA GARRIDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - AUTO POSTO RODOANEL LE SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - BEATRIZ MELLO ANTONIATE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - BRUNA DIONISIO ALVES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CAP GIRO DIGIT LIBERAวรO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CAP GIRO DIGITAL ESTORNO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CAROLINA G DE O M PARADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CAROLINA GOMES O M PARADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - ASSAI ATACADISTA SUZANO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - AUTO POSTO MACEDO GUARULHOS BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - AUTO POSTO PARQUE SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - CARTÃO DE DÉBITO - AUTO POSTO RAGUEB SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW());
