INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 36/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 37/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 38/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 39/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 4/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 40/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 41/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 42/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 43/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 44/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 45/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 46/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 47/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 48/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 49/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 5/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 50/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 51/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 52/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 53/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 54/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 55/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 56/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 57/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 58/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 59/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 6/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 60/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 7/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 8/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 9/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 06/2021 - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 06/2021 - Parcela 11/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 06/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 06/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 14/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 15/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 16/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 17/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 18/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 2/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 3/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2022 - Parcela 5/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 07/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 13/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 14/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2021 - Parcela 15/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 08/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 09/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 09/2022 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 09/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 09/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 10/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 11/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 11/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 12/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 12/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Abril > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Agosto > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Agosto > PIX: 35.128.190/0001-01 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Dezembro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Fevereiro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Fevereiro > PIX: sac@studio7otica.com (e-mail) -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Janeiro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Julho > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Junho > PIX: 35.128.190/0001-01 (CNPJ) - ref. (Gislene Lima) - 15 atend.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Junho > PIX: 35.128.190/0001-01 (CNPJ) - ref. 01/06 a (Maria Vitória da Silva) - 16 atend.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Maio > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Março > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Novembro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Outubro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 1° Quinz. Setembro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Abril > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Agosto > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Dezembro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Fevereiro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Janeiro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Julho > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Junho > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Maio > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Março > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Novembro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Outubro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSTITUTO VISÃO: 2° Quinz. Setembro > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INT PAG TIT 157000437312', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INT PRE-PAGOXXXXX 1171', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ) > Cód. de barras: 84610000001-3 2017016 2202-3 40610003000-5 0 0470327670-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ) > Cód. de barras: 84640000001-0 30880162202-5 40910003000-9 00475835062-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ) > Cód. de barras: 84660000001-8 28740162202-5 41010003000-7 00477714598-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ) > Cód. de barras: 84680000001-6 28740162202-5 40710003000-3 00472147933-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/318431336 - RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ) > Cód. de barras: 84680000001-6 28740162202-5 40810003000-1 00473999865-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/407801031 - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 003/409666719 - RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001164151 - SUZANO 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001164151 - SUZANO 2 (ref. 12/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001164151 - SUZANO 2 (ref. ago/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001164151 - SUZANO 2 (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001164151 - SUZANO 2 (ref. set/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001174491 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 209/001184802 - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CLARO NET 833/137049882 - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CONECTA 12801 - PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CONECTA 12801 - PERUS - cancelamento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INTERNET CONECTA 12801 - PERUS > Cód. de barras: 75691.43519 01325.659603 49485.090010 4 96680000010493', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INVESTIMENTO DE MARKETING: Thiago Yuri da Silva Yuki', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IPHOME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IR - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 04/2021 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 04/2021 (1° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 04/2021 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 04/2021 (2° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 11/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 11/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 12/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional - 12/2022 (Multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 01/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 01/2023 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 01/2023 - Parcela 7/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 01/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 01/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 01/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 02/2023 - Parcela 10/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 02/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 02/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 02/2023 - Parcela 9/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 02/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 03/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 03/2023 - Parcela 12/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 03/2023 - Parcela 13/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 03/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 03/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 04/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 04/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 10/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 11/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 2/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 24/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 25/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 26/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 27/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 28/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 29/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 3/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 30/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 31/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 32/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 33/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 34/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 35/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 36/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 37/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 38/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 39/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 4/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 40/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 41/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 42/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 43/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 44/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 45/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 46/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 47/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 48/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 49/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 5/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 50/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 51/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 52/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 53/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 54/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 55/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 56/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 57/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 58/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 59/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 6/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 60/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 7/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 8/60', 'juridica', NULL, True, NOW(), NOW());
