INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'PAGBANK - PIX RECEBIDO - CP :08561701-GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGSEGURO S. A.: Compra de maquininha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - EDP BANDEIRANTES: ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - EDP BANDEIRANTES: LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - ENEL : MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - ENEL BANDEIRANTES: ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - ENEL ELETROPAULO METROPOLITANA ELETRICIDADE DE SÃO PAULO S. A.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - ENEL ELETROPAULO METROPOLITANA ELETRICIDADE DE SÃO PAULO S. A. (REF. 11/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE LUZ - ENEL MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE ÁGUA - BRK AMBIENTAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE ÁGUA - ESCRITORIO RGI 0875088899', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE ÁGUA - LOJA SUZANO RGI 00467363/87', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA DE ÁGUA - LOJA SÃO MATEUS RGI 1963968459', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA INTERNET/TELEFONE - CONTA DE TELEFONE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA INTERNET/TELEFONE - TIM SA: ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA INTERNET/TELEFONE - VIVO FIXO: SERVIÇOS MENSAIS (ESCRITÓRIO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO CONTA INTERNET/TELEFONE - VIVO FIXO: SERVIÇOS MENSAIS (ESCRITÓRIO) - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO ESCOLA NICOLLY CHEQUE 1/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO FUNCIONÁRIO - ATELIÊ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO NATH PARA CAMPANHA - PIX ENVIADO - NATHALIA CAROLINA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO PIX - GILBERTO JUNIOR: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO PIX - RECEBIVEIS DE VENDA - CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO PIX - TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGTO PIX - TRANSFERENCIA PIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGUE MENOS: Flogoral Menta Past/8 > Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PANIF E CONF QUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PANIFICADORA 5 QUINAS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PANIFICADORA SILVA LTDA: Bisnaga, mortadela e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PANIFICADORA SILVA LTDA: Margarina e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PANIFICADORA SPRI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAO DE ACUCAR 2380 M', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPALEGUAS PAPELARIA E ARMARINHOS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPALEGUAS PAPELARIA E ARMARINHOS LTDA: Canetas e clipes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPALÉGUAS PAPELARIA E ARMARINHOS LTDA: Papelaria', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPALÉGUAS: Compras de acessórios de decoração para a Black Friday > Rosangela > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 04/01 17:09 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 07/02 18:39 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 08/03 12:05 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 08/03 12:10 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 08/09 12:37 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 22/12 10:46 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 24/03 16:13 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 24/11 13:53 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - 29/12 12:41 CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - ACP PLÁSTICO 0,12 MEMORANDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - BOBINA TERMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - BOBINA TÉRMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CANETA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CANETA ESFÉRICA CRISTAL AZUL BIC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU BAZAR E PAP S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: 3M BL ADES NOTEFIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ACP PLÁSTICO MEMORANDO', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 10/13 (1000 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ACRILEX CORRETIVO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ADELBRAS BLOCO ADES 38X51 4 CORES NEON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ADELBRAS FITA ADESIVA 48X45 PP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: BARBANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: BIC CANETA ESF. CRISTAL MÉDIA AZUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: BLOCO DE RASCUNHO E FOLHA SULFITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: BLOCO DE VALE E RECIBO COM CANHOTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: BOBIBINA TÉRMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: BOBINA TÉRMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: CANETA E CLÍPS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: CANETA MARCA TEXTO E POST-IT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: CANETA RETROP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: CIS GRAMPO 26/6 GALV 1000PC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: COMPACTOR CANETA ESFÉRICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: CRACHÁ E CORDÃO PARA CRACHÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: CREDEAL CADEADO 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: DURACELL PILHA ALC. AA PEQ. 4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: EAGLE GRAMPO GALVANIZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: EAGLE GRAMPO GALVANIZ E JOCCER GRAMPEADOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ENVELOPE BRANCO OF', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ENVELOPE CARTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ENVELOPE KO 17 110X70', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: ENVELOPE SACO BCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: FITA DUPLA FACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: GK CLIPES 50 UNID.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: GRAMPEADOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: MARCA TEXTO E POST-IT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL C/ PLUS A-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL CONTACT TRANSPARENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL SULFITE A4 100 FOLHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL SULFITE A4 100F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL SULFITE A4 100F E PILHA AAA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL SULFITE A4 COLOR AVULSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: PIMACO ETIQUETA E ETIQUETA RED', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: POST-IT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: REPORTE PAPEL SULF A4 100F SENINHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: SD BLOCO VALE SIMPLES 100F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU PAPELARIA E BAZAR LTDA: TEKBOND ADES INSTANT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASA ROLLU SUZANO BRA, N', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CASO ROLLU PAPELARIA E BAZAR LTDA: EAGLE GRAMPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - COMERCIAL MD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - COMPRA DE CRACHÁ (REEMBOLSO ANDREIA LEDO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - CÓPIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - DUPARI COMERCIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - EAGLE GRAMPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - ENVELOPE CARTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - ETIQUETA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - FESTIPEL EMBALAGENS LTDA: TNT METRO LISO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - FITA 3MM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - FITA FIXA FORTE TRANSPARENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - IMPRESSÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - IMPRESSÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - M.E SERV. DE INFO LTDA - ME: XEROX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - MAUAMI BAZAR E PAPELARIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - MEI MAGAZINE LTDA: CALCULADORA, FITAS, GRAMPO, TESOURA E PASTA SANFONADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - MEI MAGAZINE LTDA: ETIQUETA, PAPEL SULFITE, PAPEL A4, PIÇHA AAA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL A4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL DE SEDA 48X60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL SEDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL SULFITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL SULFITE A4 100 FOLHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL SULFITE COPIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PAPEL SULFT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PASTA ABA DE ELÁSTICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - PLASTICO P/COPOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - POST-IT, GRAMPO E GRAMPEADOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - RECIBO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - RECIBO COM CANHOTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SACO DE LIXO E INTERFOLHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SEIJUN YAMAUCHI PAPELARIA - ME: CÓPIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SEIJUN YAMAUCHI PAPELARIA - ME: GRAMPEADOR PARA O ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SOFT PEL PAPELARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SOFT PEL PAPELARIA: FOLHAS (JÚNIOR)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SOFT PEL PAPELARIA: FOTO MASTERPRINT 135G A4 50 FLS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SOFT PEL PAPELARIA: PAPEL FOTO 180G A4 GLOSSY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - SOFT PEL SUZANO BRA, NÃºM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - TAMOIO BL NOTA PROMISSÓRIA 50F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - TEKBOND', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - UNAPEL COMERCIO DE ART S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - UNAPEL COMÉRCIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - VICTORIA SÃO MATEUS LOJAS DE DEPARTAMENTOS LTDA: CANETA CORRETIVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - XEROX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - YAMA PRINT PAPELARIA E GRÁFICA RÁPIDA: 98 CÓPIAS COLORIDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA - YES CAPA PLÁTICA P/ DOC. E CORDÃO PARA CRACHA C/ PRESILHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPELARIA: Sacolas > Cleberson Ribeiro de Jesus > PIX: fa3ebe71-d347-4fe4-9e4d-5d051e7d274d (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAPÉIS - BRUNO FORTINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PARAISO DO REAL: Baldes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PARTE FRANQUIA - Acerto', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARE - VIXEN > > PIX: 15.495.166/0001-01 (CNPJ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARE - VIXEN > IMPLANTAÇÃO DE SISTEMA > PIX: 15.495.166/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARE - VIXEN > PIX: 15.495.166/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARES LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARES LTDA: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARES LTDA: PARCELA 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASSWORD INTERATIVA BI E SOFTWARES LTDA: PARCELA 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASTEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASTELARIA COLONIAL: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PASTELARIA ERENITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAX OPTICAL COMERCIAL LTDA > PIX: 13.694.878/0001-16 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -ASSAI ATACA-10/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -ASSAI ATACA-15/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -ASSAI ATACA-21/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -ASSAI ATACA-31/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -AUTO POSTO -02/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -AUTO POSTO -15/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -AUTO POSTO -17/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -AUTO POSTO -18/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -AUTO POSTO -19/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -CACAU NARDY-23/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -CENTRO AUTO-15/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -CENTRO AUTO-23/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -CHURRASCARI-15/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -DINGO PET -12/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -ESPETINHOS -19/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -FRUTO DOCE -17/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -FRUTO DOCE -19/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -JOSELI APAR-10/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -JOSELI APAR-18/01 -almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -JOSELI APAR-22/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -KELLO MAIS -12/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -LANCHONETE -13/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -MINI EXTRA--14/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -MR CHIPPS -17/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -NO PRECINHO-18/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PADARIA REN-06/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PAG*GoldenP-23/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PAG*LuanaDo-25/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PAG*Patropi-25/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PAG*PortalD-31/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PICANHA NOB-31/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PONTO ESFIH-18/01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -POSTO REDE -17/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -PRINCESINHA-23/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -ST MARCHE -02/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -SUPER MERCA-11/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -SUZURAN BOM-19/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAY -VAREJAO MAR-25/12', 'juridica', NULL, True, NOW(), NOW());
