INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Transferência recebida 18/01 16:08 T.M.C C V O S U LIMIT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transferência recebida18/01 16:07 TMO C V OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transferência recebida18/01 16:08 T.M.C C V O S U LIMIT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transporte da festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transporte festa Nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Transporte para o Mike ir até Mauá', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Troca de braços da cadeira giratória - Reginaldo Donizete', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Troco do mês passado para o cliente - OS 2691: Antônio Alves Borges', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Troco para cliente > OS 1407 - Vera Lucia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER FLASH MOTO: Entrega de chaves do escritório, ref. > Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER FLASH: Entrega de serviço, ref. OS 10981 - ZENILDA MOTA DOS SANTOS CABRAL > Camila Faccin Vieira > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Junior (buscar o carro)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Junior e Nicolas (ida para o mercado)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Junior e Nicolas (retorno do mercado)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Luana Cristina (ida para Rio Pequeno) - (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Luana Cristina (ida para São Mateus) - (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Tatiana Mello (ida para Perus)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UBER: Tatiana e Junior (ida para Mauá)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ULTRAFARMA: ESTOJO PARA LENTE DE CONTATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UNA COMERCIO DE FERR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UNAPEL COMERCIO DE ART S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UNAPEL COMÉRCIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'UNIVERSIDADE ANHEMBI MORUMBI: Giovanna Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'USAFLEX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Uber', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Uber 26/08 (Pq. São Rafael) Wevilly > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Uber para buscar as coisas nos fornecedores', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'V FLEX COMERCIO DE F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - ADIANTAMENTO: DIEGO FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - ARIANE GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - ARIANI DIAS FERNANDES CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - PAGAMENTO DE VALE: ANA CLAUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - PAGAMENTO DE VALE: KETHILYN SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - PAGAMENTO PARA ANA CLAUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - PAGAMENTO PARA CRISTIANE DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - PAGAMENTO PARA KETHILYN SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - PAGAMENTO VALE: ANA CLAUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - TROCO SAMUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO 1/2: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO 1/2: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO 2/2: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO 2/2: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO 1/2: ALESSA BISPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO 2/2: ALESSA BISPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO: FRANCINEIDE SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO: RICARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO: ROGÉRIO (TESTE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO DIVULGAÇÃO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ALESSA BISPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ALESSANDRA BARBOSA LEME (REF. 01/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ALINE DA CRUZ SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ALINE HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ANDREIA PAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ARIANI DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ARIELE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: CRISTIANE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: DIEGO FRANCISCO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: JOCICREIDE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: JOCICREIDE MACEDO (DESCONTO DE LENTES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: KAILANE CRISTILLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: MARIA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: NATHALIA CAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: NATHALIA CAROLINA (DESCONTO DE LENTES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: PAULO CESAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: PAULO CÉSAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: RAYLA ABADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: TAMIRES MACIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: VICTOR CURY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: WEVILLY DE SOUZA LÍBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: YASMIN SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMENTO: ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - VALE ADIANTAMETO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE - ZAINE CORDEIRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Aline Cristina Moreira da Cunha (férias vendida) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ana Cristina Rodrigues Amancio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ana Cristina Rodrigues Amancio > PIX: (11) 9 4132-7245 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ana Paula Aparecida Moreira da Silva Yuki > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Anna Beatriz de Camargo Lorena', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Anna Beatriz de Camargo Lorena > PIX: (11) 9 4079-5920 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariane Diniz', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 05/09 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 07/06 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 07/07 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 07/08 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 07/10 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 08/04 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano (ref. 08/05 - ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Beatriz Silva de Matos Araújo > PIX: (11) 9 6595-4315 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Bruna Dias de Souza > PIX: (11) 9 6088-1210 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Bruno Henrique Simão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Camila Faccin Vieira (ref. 07/04 - ) > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Camila Faccin Vieira > PIX: (11) 9 5485-1322 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Carolina Rodrigues da Silva (auxiliar administrativo, ref. 02/09 - ) > PIX: carolinarodrigues297@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Cleberson Ribeiro de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Dyenifer Nicole Brandão da Rocha (ref. 8 dias trabalhados > 11/08 - ) > PIX: (15) 9 9773-6533 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Débora Lemes Siqueira > PIX: 385.289.258-97 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Eliana Savoia > PIX: (11) 9 4714-9764 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Felipe Roger Miranda > PIX: (11) 9 5805-6343 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Francisca Lindineis Nascimento de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Giovanna Mello', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Giovanna Mello de Camargo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Gislania de Oliveira Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Igor Nascimento Medeiros', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Joana D''arc Elvira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Joana D''arc Elvira > PIX: 239.961.918-80 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Jocicreide Macedo Barbosa Santos (lançamento errado)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: João Paulo Sirassava Guapo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kathleen dos Santos Campos > PIX: kathleendossantoscamposkety@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) ~ MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Keren Anacleto de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kethelyn Miranda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Kethelyn Miranda > PIX: 508.457.918-26 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Lara Silva Wingeter de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Lara da Silva Wingeter de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Letícia Morais Domingos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Luana Cristina Martins Campos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria Cristina de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria Cristina de Jesus (dinheiro de Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria Cristina de Jesus (dinheiro de SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria Cristina de Jesus (dinheiro de Suzano I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria da Conceição Ramos de Moura > PIX: 102.281.264-52 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Maria da Conceição Ramos de Moura Banco', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nathalia Carolina Cardoso Ribeiro Faustino > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (CPF) ~ (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (CPF) ~ (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (CPF) ~ (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: (11) 9 5328- 7646 (CPF) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490,832,378-00 (CPF) Onibua ida e volta para Rio Pequeno e São Mateus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ (SÃO MATEUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ SUZANO 1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ SUZANO 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF) ~ moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicolas Coutinho da Silva PIX: 490.832.378-00', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Nicollas Henrique Souza dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Robson Luiz Alves dos Reis', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Rosangela Aparecida Dejane Felisbino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Rosangela Aparecida Dejane Felisbino (dias trabalhados, ref. 28/07 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Samuel Henrique da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Sandy Cristina da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Stephane Soares Lima', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Thiago Vinicius Andrade Siqueira > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Thiago Yuri da Silva Yuki > PIX: (19) 9 9127-3092 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Thiago Yuri da Silva Yuki > PIX: (19) 9 9127-3092 (celular) ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Thiago Yuri da Silva Yuki > PIX: (19) 9 9127-3092 (celular) ~ (SUZANO II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Thiago Yuri da Silva Yuki > PIX: yukicomercial@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW());
