INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2021 - Parcela 9/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 05/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 06/2021 - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 06/2021 - Parcela 11/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 06/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 06/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 14/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 15/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 16/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 17/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 18/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 2/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 3/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2022 - Parcela 5/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 07/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 13/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 14/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela 15/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2021 - Parcela15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 08/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 09/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 09/2022 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 09/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 09/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 10/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 11/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 11/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 12/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRPJ: Simples Nacional 12/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRRF - RENDIMENTO DO TRABALHO ASSALARIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IRRF - RENDIMENTO DO TRABALHO ASSALARIADO - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ISABELA PRESENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ITA DECORACOES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ITAQUERAO SUSHI H', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ITENS PARA LOJA > Felipe Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 9/13 (1000 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'ITENS PARA LOJA > Nicolas Coutinho > PIX: 490.832.378-00 (CPF) Pilha para loja de Mauá dia 06/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'J. CESAR NEVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JD EVENTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JESSICA - VISION PRIME > PIX: 11981949317 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JINYAO CHEN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JOHNSON & JOHNSON DO BRASIL INDUSTRIA EC: Lentes de contato - Parcela 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JOHNSON & JOHNSON DO BRASIL INDUSTRIA EC: Lentes de contato - Parcela 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JOSE HILTON GONCALVES DOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JOSÉ VITOR DANTAS DE SANTANA: Compra de solares', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JPS SERRALHERIA: Colocação de barra para aumentar a guia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JUROS - COBRANÇA DE I.O.F.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JUROS - COBRANÇA DE JUROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JUROS - JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Jd - Aluguel de copos - pix: 11998158927', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KALLAN CALCADOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KAMIX FOODS IND E', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KANPEK RESTAURANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO - Parcela 1/10 > PIX: 07.019.231/0001-96 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO - Parcela 10/10 > PIX: 07.019.231/0001-96 (CNPJ)-1623,05', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO - Parcela 2/10 > PIX: 07.019.231/0001-96 (CNPJ) -1802,27', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO : ( Acordo Entrada + 10 Parcelas ) PIX: 07019231000196', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO : ( Parcela 10/10 ) PIX: 07019231000196 -1263,06', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSON GO > PIX: 07.019.231/0001-96 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KENERSPN GO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KEXUE XU: Compra de armações', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KI BARATO VARIEDADES: Margarina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KILOUCURA DOCES EIRELI: Bolo, bebida láctea, detergente e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KILOUCURA DOCES EIRELI: Café e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KILOUCURA DOCES EIRELI: Mortadela e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KILOUCURA DOCES EIRELI: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KILOUCURA DOCES EIRELI: Requeijão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KIPRECINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KIT BARATO VARIEDADES: Iogurte, linguiça e salame', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KOFUKO FESTAS: BARBANTE E BEXIGAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KOFUKO FESTAS: Bexigas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KOFUKO FESTAS: Bexigas neon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTD > PIX: 08.450.703/0001-23 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTD: Levantamento de débitos > PIX: 08.450.703.0001/23 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTD: Mensalidade > PIX: 08.450.703.0001/23 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTD: Serviço extra - Maria da Conceição Ramos de Moura > PIX: 08.450.703.0001/23 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTD: Simulação de parcelamento > PIX: 08.450.703.0001/23 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA - PIX: 08.450.703/0001-23 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA- Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 1/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 1/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 10/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 11/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 12/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 13/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 2/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 2/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 3/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 3/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 4/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 4/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 5/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 5/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 6/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 6/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 7/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 7/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 8/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 8/8 - Acordo de Dívida', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KONSEP CONTABILIDADE E CONSULTORIA LTDA: Parcela 9/45 - Acordo de Dívida - Pix: 08.450.703/0001-23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'KORMOCZI EMBALAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Kalunga: Copo descartável, cabo de força e papel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Kamix - festas 16/12 e 18/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Kenerson GO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Kit degustação', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO - 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: 343.720.668-05 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: 343.720.668-05 (CPF) - NUBANK ~ Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: 343.720.668-05 (CPF) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: 343.720.668-05 (CPF) > - desconto de , ref. OS 495 (quebra de lente na montagem)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: 343.720.668-05 (CPF) > - desconto de - ref. OS 3145', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) - (ESTORNO, ref. o fechamento 01/09 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (corte errado da lente., ref. OS 10472)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (corte errado da lente., ref. OS 10568)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (deformou o modelo de ½ par de lente, ref. OS 10750)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (eixo girado do par de lentes, ref. OS 00-11370)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (eixo virado na mont., ref. OS 6955)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (lente quebrada na mont., ref. OS 6946-1), (eixo virado na mont., ref. OS 6952) e (eixo virado na mont., ref. 695', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (lente quebrada na montagem, ref. OS 1001)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (lente quebrada na montagem, ref. OS 4490 e 9933 - parcela 1/2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (lente quebrada na montagem, ref. OS 4607)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (lente quebrada na montagem, ref. OS 9933 - parcela 2/2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (lente quebrada na montagem, ref. OS 9935)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (linha de montagem torta de ½ par de lente., ref. OS 10365-1)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (quebra de três ½ pares de lentes, ref. OS''s 11335, 11351 e 11385)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LABORATÓRIO THC MONTAGEM E CONSERTO: THIAGO CARVALHO > PIX: labthc@outlook.com (e-mail) > - * desconto de (quebra de ½ par de lentes, ref. OS 11589)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LALAMOVE TECNOLOGIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LANC REST RIO MIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LANCHONETE E REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LANCHONETE MEA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LANCHONETE: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LASONIC SOLUÇÕES (Manutenção micro-ondas SUZANO 2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LASONIC SOLUÇÕES INTELIGENTES LTDA: Conserto da cafeteira - MAUÁ > PIX: 16.550.193/0001-94 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LASONIC SOLUÇÕES INTELIGENTES LTDA: Conserto da cafeteira - PERUS > PIX: 16.550.193/0001-94 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LED IN BRASIL ARTIGOS DE ILUMINAÇÃO LTDA: Adesivo para recado e bloco adesivo neon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 0-11978', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 12000', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 12019', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 12020', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 12029', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 12030', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. OS 4729', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES & CIA EXPRESS LTDA > PIX: 33.814.649/0001-03 (CNPJ) - ref. Tatiana Mello', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - ALMOÇO EQUIPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - ARCASIGN C VISUAL LT ME: LOGO - PARCELA 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - CHEQUE COMPENSADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - COLORAÇÃO: DAYANE VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - DESCONTO/ABATIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - LENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - NEW LENTES: COMPRA DE LENTES DE CONTATO (SITE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - NEW LENTES: LENTES DE CONTATO (SITE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - PAGAMENTO DE DIFERENÇA: SÓBLOCOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - PROTESTO: JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - SOLÓTICA: COMPRA DE LENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - SOLÓTICA: COMPRA DE LENTES DE CONTATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - SOLÓTICA: COMPRA DE LENTES DE CONTATO - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - SOLÓTICA: COMPRA LENTES DE CONTATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - STÚDIO 7: MONTAGEM & CONSERTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - SÓ BLOCOS: COMPRA DE LENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - VALOR DAS CUSTAS: PROTESTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - ZEISS - DEJURIS CONS EMPRESARIAL LTDA - 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - ZEISS - DEJURIS CONS EMPRESARIAL LTDA - 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LENTES - ZEISS - DEJURIS CONS EMPRESARIAL LTDA - 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LETÍCIA UNIFORMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LEVE MAIS E PAGUE MENOS: Biscoito e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LEVE MAIS E PAGUE MENOS: Mortadela e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LEVE MAIS E PAGUE MENOS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LIDIA PALMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'LILIAN NUNES: ARMÁRIO - LOJA', 'juridica', NULL, True, NOW(), NOW());
