INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Vanessa Santana Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Vitória Regina Nunes da Conceição', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Wevilly de Souza Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Wevilly de Souza Fernandes Líbano - Descontar no salário', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Wevilly de Souza Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ADIANTAMENTO: Érika de Oliveira Gomes > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ALIMENTAÇÃO/REFEIÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ALIMENTAÇÃO/REFEIÇÃO (provisório - Rio Pequeno)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE ALIMENTAÇÃO/REFEIÇÃO - Provisórios (lojas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE REFEIÇÃO: Nicolas Coutinho da Silva (ajuda de custo) > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE REFEIÇÃO: Nicolas Coutinho da Silva (ajuda de custo) > PIX: 490.832.378-00 (CPF) - não veio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE REFEIÇÃO: Nicolas Coutinho da Silva (ajuda de custo) > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TATI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE (valor retirado por Taty e Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - ALINE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - ARIANE GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - ARIANI DIAS FERNANDES CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - ARIELLI APARECIDA FELICIANO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO CRIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ALESSANDRA BARBOSA LEME - SUZANO (REF. 22/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ALESSANDRA BARBOSA LEME - SÃO MATEUS (REF. 13/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ALESSANDRA BARBOSA LEME - SÃO MATEUS (REF. 18/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ALESSANDRA BARBOSA LEME - SÃO MATEUS (REF. 26/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ARIANI DIAS - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: EMERSON WILLIAM - SÃO MATEUS (REF. 27/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: FLÁVIO OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: FRANCINE VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: FRANCINEIDE DUARTE - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: KAILANE CRISTILLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: LARISSA DIAS - MAUÁ - REF. 06/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: LARISSA DIAS - MAUÁ - REF. 30/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: MIRIAM SANCHES (REF. 02/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: RICARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: RICARDO - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: TAMIRES SOARES - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 05/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 06/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 08/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 09/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 10/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 13/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 21/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 22/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 24/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 27/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CONDUÇÃO: ÊNIO MASCARENHAS (REF. 28/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CRIS DA SEMANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - CRISTIANE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - DIFERENÇA VALE TRANSPORTE: PAULO CÉSAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - KAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE COMISSÃO: JOCICREIDE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇAO: PAULO CÉSAR - BRASLAB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: APARECIDA NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ARIANI DIAS - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ARIANI DIAS E KAILANE CRISTILLY - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ARIANI DIAS, NATHALIA CAROLINA E PAULO CÉSAR - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: BRUNA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: EDSON PEREIRA (01/12 A 04/12)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: FELIPE ROGER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: KAILANE CRISTILLY - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: KAROLINY MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: KELLY CRISTINA (01/10 A 02/10)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: LARISSA DIAS - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: LARISSA E ZAINE - DIVULGAÇÃO NOS BAIRROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: LUANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: LUANA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: PAULO CÉSAR - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: RAYSSA KAROLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ZAINE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ZAINE SIQUEIRA (07/10 A 09/10)', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 13/13 (816 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE CONDUÇÃO: ZAINE SIQUEIRA - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE VALE TRANSPORTE: ANA CLAUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE VALE TRANSPORTE: CRISTIANE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE VALE TRANSPORTE: JÉSSICA THAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE VALE TRANSPORTE: KETHILYN SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE VALE TRANSPORTE: MARIA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO DE VALE TRANSPORTE: PEDRO DONIZETE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAGAMENTO VALE TRANSPORTE: CRISTIANE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAMELA GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - PAULO CESAR PALERMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - RECEBIVEIS DE VENDA - CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - TIELLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE (COM INTEGRAÇÃO - 04/02 A 28/02): YASMIN SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE (SEM INTEGRAÇÃO - 28/01 A 03/02 ): YASMIN SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE DIVULGAÇÃO: SAMUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE DIVULGAÇÃO: VITÓRIA CARMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ADRIANA GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: AGATHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALDENIR PAULA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESANDRA BARBOSA LEME (REF. 01/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESANDRA BARBOSA LEME (REF. 04/07 A 07/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESSA BISPO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESSA BISPO (PERÍODO 15/02 A 19/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESSA BISPO (PERÍODO 25/01 A 29/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESSA BISPO (PERÍODO 31/01 A 03/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESSANDRA BARBOSA LEME (REF. 01/08 A 06/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALESSANDRA BARBOSA LEME (REF. 11/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE DA CRUZ SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE DA CRUZ SANTOS (REF. 10/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE DA CRUZ SANTOS (REF. 11/06 A 20/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE DA CRUZ SANTOS (REF. 21/06 A 02/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE (REF. 05, 06 E 08/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE (REF. 14/09 A 17/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE (REF. 19/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE (REF. 20/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE (REF. 27/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE (REF. 29/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE DOS SANTOS (REF. 01/09 A 05/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE DOS SANTOS (REF. 16/08 A 24/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ALINE HENRIQUE DOS SANTOS (REF. 31/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANA MARIA (CONDUÇÃO 31/03 A 01/04)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANA ROSA (REF. 14/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANA ROSA (REF. 18/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANDREIA PAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANDREIA PAES (REF. 26/07 A 29/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANDRESSA (DIVULGAÇÃO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ANNE KELLY (REF. 22/09 A 01/10)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: APARECIDA NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ARIANI DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ARIELE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ARIELE ARAÚJO (PERÍODO 17/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ATENISTA ARAÚJO LOPES (REF. 28/05 A 30/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: CRISTIANE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: DENILSON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: DIEGO FRANCISCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EMERSON WILLIAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EMERSON WILLIAM (REF. 12/07 A 30/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ENIO (23/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ENIO (REF. 16/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ENIO (REF. 17/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ENIO (REF. 18/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ENIO (REF. 20/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ENIO (REF. 22/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EVELINE GIANETTI RIBEIRO (REF. 11/07 A 12/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EVELINE GIANETTI RIBEIRO (REF. 15/07 A 16/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EVELINE GIANETTI RIBEIRO (REF. 25/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EVELINE RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: EVELYN HILDA (PERÍODO 17/03 A 19/03)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: FELIPE ROGER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: FRANCINEIDE DUARTE (ADIANTAMENTO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: JOCICREIDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: JOCICREIDE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: JOÃO VITOR (REF. 01/09 A 05/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: JOÃO VITOR (REF. 02, 03 E 05/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: JOÃO VITOR (REF. 24, 25 E 26/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: JÉSSICA VICTÓRIA (DIVULGAÇÃO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: KAILANE CRISTILLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: KAILANE CRISTILLY (DIFERENÇA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: KELLY SIMÕES (REF. 28/07 E 29/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: LARISSA DIAS (SUZANO E MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: LUANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: MARIA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: MATHEUS RAFAEL NASCIMENTO FERREIRA (REF. 07/06 A 13/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: MATHEUS RAFAEL NASCIMENTO FERREIRA (REF. 14/06 A 15/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: MATHEUS RAFAEL NASCIMENTO FERREIRA (REF. 28/05 A 30/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: PAULO CÉSAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: RAQUEL RONCONI (CONDUÇÃO 05/04 A 08/04)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: RAYLA ABADE (PERÍODO 10/01 A 15/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: RAYLA ABADE (PERÍODO 17/01 A 22/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: RAYLA ABADE (PERÍODO 24/01 A 27/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ROBERTO (REF. 09/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ROBERTO (REF. 10/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ROBERTO (REF. 11/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ROBERTO (REF. 15/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: Raquel (ref. 25/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: SAMUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: SUZILÉIA (REF. 20/07, 21/07 E 22/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: TAMIRES MACIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: THAYSSA ROBERTA (REF. 09/09 E 10/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: THAYSSA ROBERTA (REF. 12/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: THAYSSA ROBERTA (REF. 13/09 E 14/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: THAYSSA ROBERTA (REF. 15/09 A 17/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: THAYSSA ROBERTA (REF. 19/09 A 24/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: THAYSSA ROBERTA (REF. 26/09 A 01/10)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: WILLIAM DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: WILLIAM DE SOUZA (REF. 03/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: YASMIN SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VALE TRANSPORTE - VALE TRANSPORTE: ZAINE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW());
