INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA EMPRESA/EMPREGADOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA EMPRESA/EMPREGADOR - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CONTRIBUIÇÃO PREVIDENCIÁRIA EMPRESA/EMPREGADOR - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COPO DESCARTÁVEL - Luana > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CORA SOCIEDADE DE CREDITO DIRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CORANTE TINTAS LOJA MATRIZ: Aplicador de massa grande, cimento queimado e crepe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CORREIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CORRENTES DE METAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CORRENTES PÉROLAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'COTAÇÃO: Capinha, estojos e flanelas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP SEGURADOS - CONTRIBUINTES INDIVIDUAIS - 11%', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP SEGURADOS - CONTRIBUINTES INDIVIDUAIS - 11% - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP SEGURADOS - CONTRIBUINTES INDIVIDUAIS - 11% - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - INCRA', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 4/13 (1000 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'CP TERCEIROS - INCRA - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - INCRA - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SALÁRIO EDUCAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SALÁRIO EDUCAÇÃO - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SALÁRIO EDUCAÇÃO - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SEBRAE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SEBRAE - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SEBRAE - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SENAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SENAC - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SENAC - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SESC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SESC - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CP TERCEIROS - SESC - TMC COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CRISTINA FLORES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CRÉDITO ANTECIPAÇÃO - VALOR ANTECIPADO NO DIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 04/2021 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 04/2021 (1° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 04/2021 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 04/2021 (2° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 11/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 11/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 12/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional - 12/2022 (Multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 01/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 01/2023 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 01/2023 - Parcela 7/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 01/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 01/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 01/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 02/2023 - Parcela 10/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 02/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 02/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 02/2023 - Parcela 9/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 02/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 03/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 03/2023 - Parcela 12/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 03/2023 - Parcela 13/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 03/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 03/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 04/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 04/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 10/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 11/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 2/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 25/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 26/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 27/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 28/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 29/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 3/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 30/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 31/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 32/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 33/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 34/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 35/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 36/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 37/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 38/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 39/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 4/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 40/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 41/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 42/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 43/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 44/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 45/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 46/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 47/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 48/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 49/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 5/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 50/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 51/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 52/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 53/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 54/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 55/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 56/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 57/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 58/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 59/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 6/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 60/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 7/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 8/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2021 - Parcela 9/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 05/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 06/2021 - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 06/2021 - Parcela 11/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 06/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 06/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 14/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 15/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 16/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 17/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 18/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 2/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 3/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2022 - Parcela 5/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 07/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - 12/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 12/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 13/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 14/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2021 - Parcela 15/23 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 08/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 09/2022 - Parcela 4/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 09/2022 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 09/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 09/2023 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 10/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 11/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 11/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 12/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CSLL: Simples Nacional 12/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CZC BRASIL INF. OPTICA LTDA - ZEISS VISION (Lens Wipes - flanelas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cabo de força (ESCRITÓRIO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Café escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Caixa em dinheiro (Suzano II)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 1/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 1/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 1/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 1/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 10/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 10/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 10/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 10/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 10/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 11/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 11/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 11/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 11/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 11/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 12/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 12/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 12/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 12/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 12/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 13/13', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 13/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 13/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 13/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 14/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 14/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 14/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 15/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 15/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 15/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 16/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 16/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 16/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 17/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 17/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 17/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 18/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 18/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 18/30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 19/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Capital de Giro - Parcela 19/24', 'juridica', NULL, True, NOW(), NOW());
