INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 07/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 08/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 11/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 11/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 1/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 2/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 3/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 4/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 5/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 6/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 7/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - ICMS: SIMPLES NACIONAL - PARCELA 8/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: IMPLES NACIONAL - PARCELA 1/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: IMPLES NACIONAL - PARCELA 2/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 01/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 04/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 05/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 06/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 07/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 08/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 11/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 11/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 1/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 2/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 3/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 4/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 5/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 6/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 7/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - INSS: SIMPLES NACIONAL - PARCELA 8/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: IMPLES NACIONAL - PARCELA 1/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: IMPLES NACIONAL - PARCELA 2/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 01/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 04/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 05/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 06/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 07/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 08/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 11/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 11/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 1/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 2/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 3/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 4/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 5/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 6/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 7/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRPJ: SIMPLES NACIONAL - PARCELA 8/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRRF: SICALC CONTRIBUINTE - 01/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRRF: SICALC CONTRIBUINTE - 01/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRRF: SICALC CONTRIBUINTE - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - IRRF: SICALC CONTRIBUINTE - 03/2022 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - MUNICIPIO DE SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PAGAMENTO PARA CAMBRAZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: IMPLES NACIONAL - PARCELA 1/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: IMPLES NACIONAL - PARCELA 2/5 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 01/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 04/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 05/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 07/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 08/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 11/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 11/2021 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 1/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 1/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 2/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 2/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 3/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 3/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 4/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 4/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 5/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 5/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 6/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 6/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 7/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 7/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 8/23', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL - PARCELA 8/23 (JUROS/MULTAS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL -02/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PIS: SIMPLES NACIONAL -03/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PROTESTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PROTESTO: BRASLAB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PROTESTO: JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - PROTESTO: TAXA PARA PIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - SICALC CONTRIBUINTE: IRRF - REMUN SERV PRESTADOS POR PJ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - SIMPLES NACIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - SIMPLES NACIONAL - 09/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - SIMPLES NACIONAL - 10/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - SINDICATO DOS EMPREGADOS NO COMERCIO D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E FISCALIZAÇÃO DE ANÚNCIOS - PARCELA 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO): PARCELA 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO): PARCELA 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPOSTOS - TAXA DE LICENÇA E FISCALIZAÇÃO DE FUCIONAMENTO (ALVARÁ DE FUNCIONAMENTO): PARCELA 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'IMPÉRIO DO BOLO MAUÁ: Bolo recheado', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INOVAR MAT CONTRUÇAO: Astra, engate e veda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - CONTRIBUIÇÃO PREVIDEMCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - CONTRIBUIÇÃO PREVIDENCIÁRIA DESCONTA SEGURADO-EMPREGADO/AVULSO: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - CP SEGURADOS - CONTRIBUINTES INDIVIDUAIS - 11%', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - CP SEGURADOS - CONTRIBUINTES INDIVIDUAIS - 11%: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 02/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 02/2022): JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 04/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 04/2021): JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 05/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 05/2021): JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 08/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 08/2021): JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 10/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - GPS: GUIA DA PREVIDÊNCIA SOCIAL (COMPETÊNCIA 10/2021): JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - JUROS/MULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Naciona 09/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 04/2021 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 04/2021 (1° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 04/2021 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 04/2021 (2° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 11/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 11/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 12/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional - 12/2022 (Multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 01/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 01/2023 - Parcela 6/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 01/2023 - Parcela 7/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 01/2023 - Parcela 8/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 01/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 01/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 02/2023 - Parcela 10/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 02/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 02/2023 - Parcela 9/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 02/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 03/2023 - Parcela 11/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 03/2023 - Parcela 12/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 03/2023 - Parcela 13/18', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 03/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 03/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 04/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 04/2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 1/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 10/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 11/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 2/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 23/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 26/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 27/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 28/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 29/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 3/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 30/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 32/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 33/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 34/60', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'INSS: Simples Nacional 05/2021 - Parcela 35/60', 'juridica', NULL, True, NOW(), NOW());
