INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11116', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11192', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11195', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11196', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11197', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11207', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11211', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 3/13 (1000 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11218', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11227', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11243', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11247', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11247 (diferença de valores)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11254', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11256', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11259', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11264', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11266', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11269', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11270', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11270 - 2°', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11278', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11288', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11289', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11384', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11429', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11438', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11450', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11452', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11465', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11466', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11467', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11533', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11545', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11547', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11552', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11560', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11561', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11643', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11644', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11645', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11649', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11650', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11655', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11699', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11721', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11746', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11747', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11751', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11756', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11774', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11801', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11818', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11821', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11832', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11833', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11902', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11910', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11922', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11928', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11934', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 11937', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 3818', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 3819', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 3824', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 4766', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 4792', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 4814', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 4830', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 4832', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 4851', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 6949', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 6952', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 6956', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 6966', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS 6971', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10345, 10558, 10567, 10568, 10570, 10572 e 10573', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10467, 10776 (meio par), 10952, 10955, 10956, 10957 e 10958', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10551, 10554, 10559, 10560, 10561 e 10562', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10553, 10568/1, 10581, 10583 e 10592', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10598 e 10600', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10610, 10611, 10616, 10624, 10626, 10627, 10630 e 10631', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10617, 10618, 10634 e 10635', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10643, 10650, 10651, 10652 e 10653', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10658 e 10659', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10663, 10664, 10669 e 10671', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10672 e 10674', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10678 e 10679', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10685, 10704, 10707, 10710, 10712, 10715 e 10728 (10679)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10722, 10732, 10737 e 10738', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10723, 10852, 10853, 10862, 10867, 10869, 10870, 10871, 10872, 10873 e 10876', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10725 e 10726', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10757, 10765-1, 10766, 10829, 10830, 10831, 10833, 10834 e 10841', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10764, 10768, 10769, 10770, 10776, 10777, 10780, 10783, 10784, 10785, 10786, 10794, 10797, 10798, 10799, 10801, 10802, 10803, 10804 e 10809', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10816, 10818 e 10822', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10880, 10894 e 10902', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 1090 e 1091', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10904, 10907, 10914, 10921, 10924, 10925, 10936, 10940, 10942 e 10947', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10930, 11020 e 11070', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10941, 10977, 10988, 10997, 10998 e 11016', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 10966, 11060, 11064, 11068 e 11069', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11004, 11014, 11023. 11029 e 11031', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 1102 e 1103', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11022, 11150, 11170, 11171, 11172, 11173, 11176 e 11177', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11042, 11049, 11054 e 11058', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11047, 11048, 11050, 11114, 11115, 11124, 11128, 11129, 11130, 11131 e 11147', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11073, 11079 e 11120', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11074, 11078, 11080, 11082, 11086, 11087, 11088, 11089, 11090, 11091, 11093, 11096 e 11099', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11140 e 11172', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 11157, 11177 (diferença), 11179, 11180 e 11181', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 4756, 4820, 4821 e 4825', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 4759, 4837 e 4838', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 4772, 4773 e 4774', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 4802 e 4813', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 4821 e 4849', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. OS''s 4856 e 4860', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASLENTES - CHAMP BRASIL COMERCIO LTDA > PIX: nubank@champbrasil.com.br (e-mail) - ref. taxa de entrega', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASMED MEDICINA OCUPACIONAL LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASMED MEDICINA OCUPACIONAL LTDA - GUAIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASMED MEDICINA OCUPACIONAL LTDA >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRENO JÚNIOR IMÓVEIS - Clínica', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRENO JÚNIOR IMÓVEIS - Loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BURGER KING: WHOPPER Q', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Balões festa Dalila -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Bolo loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Bonecos da festa -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CABO DE INTERNET', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CACAU SHOW', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CACAU SHOW: Tabletes de chocolate para clientes antigos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAFÉ DA MANHÃ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAFÉ DA MANHÃ CASA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAMBRAZ - CÂMARA DE ARBITRAGEM MEDIAÇÃO: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAMERA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CANCELAMENTO OS - Cliente: Maria Aparecida da Silva 1/3 - PIX: 099.807.948-01', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CANCELAMENTO OS - Cliente: Maria Aparecida da Silva 2/3 > PIX: 099.807.948-01 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CANCELAMENTO OS - Cliente: Maria Aparecida da Silva 3/3 > PIX: 099.807.948-01 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CANCELAMENTO: OS 7285 - Wang Chunying', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAPINHA PARA CELULAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARIMBO + CARTÃO FIDELIDADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARIMBO 14X38', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARNÊS - CARNÊS LANCASTER DEZ E NOV/20', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARRETO RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARRO - ASTRA: Caio Augusto Santana de Oliveira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTAO VISA ELECTRON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTÃO DE CREDITO COMPRA 25', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTÃO DE TODOS - Mauá', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTÃO DE TODOS - Perus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTÃO DE TODOS - Rio Pequeno', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTÃO FIDELIDADE: Lojas > Alecio dos Santos > PIX: (11) 9 4537-0793 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CARTÃO INDICAÇÃO: Indicou, ganhou! - lojas > Andreza Ashlay > PIX: (11) 9 9760-1399 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CAS SERVICOS DE I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA BONITTA: Pano de prato e pano de chão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA DAS ANTENAS: Fonte para o telefone', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA DE CARNES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA DE SUCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA PERUS LAR E CONSTRUÇÃO: Parafuso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: ACP PLÁSTICO MEMORANDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Adelbras fita adesiva 48x45 TP QUALITAPE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: BOBINA TÉRMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Balão liso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Barbante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Bobina térmica', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Bobina térmica > Jocicreide > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: CHIP TIM TURBO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: CRACHÁ E CORDÃO PARA CRACHÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Caneta Piloto e Caneta Branca', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Clipes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Cola', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Compra de CHIP (Érika - Telemarketing)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: ENVELOPE CARTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: ENVELOPE SACO BCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Eagle Grampo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Eagle grampo e post-it', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Envelope carta', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Fio de Nylon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Fio de nylon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Folha sulfite (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Folha sulfite > Jocicreide > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Folha sulfite > Nicolas Coutinho > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Grampo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Grampos > Jocicreide > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: PAPEL SULFITE A4 COLOR AVULSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Papel color e papel crepom', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Papel contact (escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Pilhas Panasonic AAA Palito', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Pilhas pequenas AA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Post-it', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Recibo comercial', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Saco PP adesivo transparente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Sacolas K Natural', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CASA ROLLU PAPELARIA E BAZAR LTDA: Saquinho plástico', 'juridica', NULL, True, NOW(), NOW());
