INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'DARF (Contribuição de Segurados - 1099)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF - Parcela 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - (IRRF - 0561)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 1/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 10/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 13/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 2/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 3/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 4/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 5/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 6/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF IR - parcela 9/22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF MÁRCIA TAKIUTTU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF MÁRCIA TAKIUTTU (ref. nov/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF MÁRCIA TAKIUTTU (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF PEDRA MIECA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF PEDRA MIECA (ref. nov/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF PEDRA MIECA (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF VINÍCIUS TAKIUTTU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF VINÍCIUS TAKIUTTU (ref. nov/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF VINÍCIUS TAKIUTTU (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAS - Simples Nacional 02/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAS - Simples Nacional 05/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAS - Simples Nacional 06/2023 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAS - Simples Nacional 07/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAS - Simples Nacional 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DATACITY SERVICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DCTF - ref. dez/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DCTF - ref. dez/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DDU DUTRA DRIVE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - 13/12 12:21 LUAN ENFEITES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - BALÕES DECORAÇÃO LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - DECORAÇÃO LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - J. CESAR NEVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - LUAN ENFEITES SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - MIDORI PAISAGISMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - QUINTAL DAS PLANTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DECORAÇÃO - WELLINGTON JORDAO DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DELFINA DIAS VELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DENILSON ELETRICISTA, Manutenção da porta da loja > PIX: 851.330.433-68 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEPOSITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEPOSITO BARUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESCOBRIR - Conciliação - PIX - ENVIADO - 11/03 13:17 PEDRO PAULO SOARES DE SOUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESCONTO COMPRA EM LOJA: Felipe Roger Miranda > parcela 1/4 (ref. OS 1091 - Cecília (esposa) > )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESCONTO COMPRA EM LOJA: Felipe Roger Miranda > parcela 2/4 (ref. OS 1091 - Cecília (esposa) > )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESCONTO COMPRA EM LOJA: Felipe Roger Miranda > parcela 3/4 (ref. OS 1091 - Cecília (esposa) > )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESCONTO COMPRA EM LOJA: Felipe Roger Miranda > parcela 4/4 (ref. OS 1091 - Cecília (esposa) > )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - 10/09 08:44 QUALICLINICA POPULAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - 22/12 10:26 CLINICA PAIOL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACERTO: ANA BEATRIZ (REF. AOS DIAS TRABALHADOS 11/04 A 14/04)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACERTO: ATENIS DE ARAÚJO LOPES - NICE (REF. AOS DIAS TRABALHADOS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACERTO: GIOVANNA MONTEIRO (REF. O DIA TRABALHADO 17/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACERTO: LAURA DIAS (REF. O DIA TRABALHADO 19/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACERTO: LAURA DIAS (REF. O DIA TRABALHADO 23/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACERTO: PAULO CÉSAR PALERMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACORDO 1/3: ZAYNE CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACORDO 2/3: ZAYNE CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ACORDO 3/3: ZAYNE CORDEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ADIANTAMENTO: ALESSANDRA BARBOSA LEME (REF. 12/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - COMISSÃO: ANA ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - COMISSÃO: RAISSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO EXTERNA: AMANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO EXTERNA: LEANDRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO FREELANCE: AIUMY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ALANI LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ALESSANDRA BARBOSA LEME (REF. 28/06 E 29/06)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: CRIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: DENILSON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: EMILY VITÓRIA LIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: FELIPE ROGER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: FRANCIANE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: FRANCIANE VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: GIOVANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: GRAZIELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: JOÃO VITOR (REF. A DIFERENÇA DE PAGAMENTO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: JOÃO VITOR (REF. OS DIAS TRABALHADOS 24, 25 E 26/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: JOÃO VITOR (REF. OS DIAS TRABALHADOS 29/08 A 05/09 + COMISSÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: KAROLYNI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: LAINE SILVA VITOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: LUANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: LÍVIA SILVA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: MARCELA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: MONIQUE SOUZA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: NAYARA CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: NICOLLAS S. OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: PEDRO DONIZETE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: RAISSA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: SAMUEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: SARA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: SUZILEIA SANTOS (REF. A 02 DIAS TRABALHADOS - VALE TRANSPORTE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: TAMIRES MACIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: VITÓRIA CARMIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ÉRICA GERONE SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ÊNIO MASCARENHAS (REF. 16/08 A 20/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ÊNIO MASCARENHAS (REF. 22/08 A 25/08 + VALE TRANSPORTE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ÊNIO MASCARENHAS (REF. A 07 DIAS TRABALHADOS + VALE TRANSPORTE DE 01 DIA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - DIVULGAÇÃO: ÊNIO MASCARENHAS (REF. A 21/09 A 28/09 )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - ENTREGA PARA MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - EXAME ADMISSIONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCE: EDSON PEREIRA (01/12 A 04/12)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: ADEMIR (REFERENTE A 03 DIAS TRABALHADOS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: ALINE HENRIQUE (REF. A 02 DIAS TRABALHADOS - 20/08 E 22/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: ANA ROSA (DIVULGAÇÃO, REF. 13/08 A 18/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: ANNE KELLY (DIVULGAÇÃO E COMISSÃO - REF. 26/07 E 27/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: BIANCA DE ARAÚJO (DIVULGAÇÃO - REF. 02/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: FERNANDA BRITO MENDONÇA (AUXÍLIO NA LOJA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: IAGO DE JESUS OLIVEIRA (REF. A 01 DIA TRABALHADO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: JOCICREIDE BARBOSA (REF. 15/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: JÉSSICA (REF. A 01 DIA TRABALHADO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: JÉSSICA (REF. A MEIO PERÍODO TRABALHADO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: KELLY SIMÕES (DIVULGAÇÃO, REFERENTE AOS DIAS TRABALHADOS: 28/07 E 29/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: LAURA DIAS (AUXILIAR - MEIO PERÍODO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: LUCAS CORNÉLIO ( DIVULGAÇÃO REF. 14/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: LUCAS CORNÉLIO (VENDEDOR REF. 08/07 E 09/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: MICHELLE VICTÓRIA (REF. 16/09 - DIA TRABALHADO + CONDUÇÃO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: MIRIAM SANCHES (REF. 01/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: MIRIAM SANCHES (REF. 02/09 E 03/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: MIRIAM SANCHES (REF. 29/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: NEEMIAS FELIPE (DIVULGAÇÃO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: ROBERTO (DIVULGAÇÃO, REF. 09/08 A 15/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: Raquel Silva Lima (ref. 23/08 a 25/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: SUZICLEIDE (DIVULGAÇÃO, REFERENTE AOS DIAS TRABALHADOS: 20/07 A 22/07)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: THAYSSA ROBERTA LIMA (REF. A UM DIA TRABALHADO NA LOJA 15/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - FREELANCER: WILLIAM DE SOUZA (DIVULGAÇÃO - REF. 03/08 A 05/08)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO DE CONDUÇÃO: NICOLLAS (22/10)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO DE EXAME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO PARA CRISTIANE DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO PARA JESSICA THAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO PARA JOCICREIDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO PARA PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO PARA RAFAEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PAGAMENTO SEMANAL: FELIPE MIRANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - PRESTAÇÃO DE SERVIÇO SR. PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - SALÁRIO DIVULGAÇÃO: BEATRIZ ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - SALÁRIO DIVULGAÇÃO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - SALÁRIO: RAYLA ABADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - TESTE: DÉBORA (DIVULGAÇÃO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - TESTE: JHULLYA V. SARAIVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - TESTE: QUEREN (AUXILIAR OPERADOR DE CAIXA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - TESTE: QUEREN (AUXILIAR OPERADOR DE CAIXA) - VALE TRANSPORTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DESPESAS FUNCIONÁRIOS - TODA MODA FEMININA: CALÇA JEANS - KAILANE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DETETIZAÇÃO DA LOJA: Cláudio José da Silva > PIX: 084.758.598-01 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - A FESTA PROVENÇAL: DEVOLUÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - DEVOLUÇÃO CLIENTE CONSULTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - DEVOLUÇÃO DE SINAL - OS 4521: NAOKO SATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - DEVOLUÇÃO DE TROCO: 2019: GILSON MOREIRA DA TRINDADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - DEVOLUÇÃO PARA CLIENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - DEVOLUÇÃO PARA CLIENTE: MARTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - DEVOLUÇÃO PARA CLIENTE: MÁRCIA ZULEIDE FARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - EMPRÉSTIMO: PAULO CÉSAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - GARANTIA DEVOLUÇÃO DO DIN 2469', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - REEMBOLSO MARIA JOSÉ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - REEMBOLSO: DIEGO FRANCISCO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO - REEMBOLSO: KÁTIA REGINA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DEVOLUÇÃO PIX RECEBIDA - Pix errado - Maria das Dores Silva Costa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA BRASIL 267', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Aline Cristina Moreira da Cunha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Wevilly de Souza Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIA DO COMERCIÁRIO: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: COLORAÇÃO > PIX: 388.772.378-30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > > PIX: 388.772.378-30 (diferença a pagar) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30 (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30 (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30 > Parcela 1/2 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30 > Parcela 2/2 >>', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30 > ref. >> MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: MONTAGENS & COLORAÇÃO > PIX: 388.772.378-30 > ref. >> MOEDAS ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIEGO JESUS GUEDES: Montagens', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFAL - ref. 10/2023', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA 1/3 DAS FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA DAS TAXAS CARTÃO DE CRÉDITO- CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA DAS TAXAS CARTÃO DE CRÉDITO- CREDZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA DAS TAXAS CARTÃO DE CRÉDITO- PAGBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA DAS TAXAS CARTÃO DE CRÉDITO- SUMUP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA MEDIA VALOR FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA SALÁRIO MATERNIDADE: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIFERENÇA SALÁRIO MATERNIDADE: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIGITAL CELULARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Aline Cristina Moreira da Cunha (diferença de salários) ~ (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Aline Cristina Moreira da Cunha (diferença de salários) ~ (moedas do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Ariani Dias Fernandes Líbano (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Eliana Savoia (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Jocicreide Macedo Barbosa Santos (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Larissa Dias Fernandes Cardozo (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Maria Elizabeth Pereira do Nascimento (diferença de salários)', 'juridica', NULL, True, NOW(), NOW());
