INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'OPTITEX INDÚSTRIA E COMÉRCIO DE ESTOJOS E BRINDES: COMPRA DE ACESSÓRIOS - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTITEX INDÚSTRIA E COMÉRCIO DE ESTOJOS E BRINDES: COMPRA DE ACESSÓRIOS - PARCELA 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTITEX INDÚSTRIA E COMÉRCIO DE ESTOJOS E BRINDES: COMPRA DE ACESSÓRIOS - PARCELA 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTITEX INDÚSTRIA E COMÉRCIO DE ESTOJOS E BRINDES: COMPRA DE ACESSÓRIOS - PARCELA 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOAL HOYA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Bruna Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Bruna Moura - Parcela 1/2 > PIX: bruna.lou.moura@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Bruna Moura - Parcela 2/2 > PIX: bruna.lou.moura@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Bruna Moura > PIX: bruna.lou.moura@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Bruna Moura > PIX: bruna.lou.moura@gmail.com (e-mail) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO - 1° QUINZ. DEZEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO - 2° QUINZ. DEZEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO - 2° QUINZ. SETEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 1° QUINZ. ABRIL (PARCELA 1/2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 1° QUINZ. ABRIL (PARCELA 2/2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 1° QUINZ. FEVEREIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 1° QUINZ. JANEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 1° QUINZ. MARÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 2° QUINZ. FEVEREIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 2° QUINZ. JANEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO 2° QUINZ. MARÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO- 1° QUINZ. NOVEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO- 1° QUINZ. OUTUBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: EDUARDO- 2° QUINZ. NOVEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Abril > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Agosto - PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Agosto > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Dezembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Fevereiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Fevereiro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Janeiro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Julho > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Junho > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Maio > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Março', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Março > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Novembro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Novembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Outubro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 1° Quinz. Setembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Abril > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Agosto > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Dezembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Fevereiro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Janeiro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Julho > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Junho > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Maio > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Março', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Março > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Novembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Outubro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Outubro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Setembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Eduardo 2° Quinz. Setembro > PIX: 226.063.238-66 (CPF) / (11) 9 4717-6553 (celular) -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos > PIX: 41.832.948/0001-90 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos > PIX: 41.832.948/0001-90 (CNPJ) - (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos > PIX: 41.832.948/0001-90 (CNPJ) - diferença paga - (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos > PIX: 41.832.948/0001-90 (CNPJ) - diferença ref. 14/08 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos > PIX: 41.832.948/0001-90 (CNPJ) >> MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Guilherme Santos > PIX: 41.832.948/0001-90 (CNPJ) >> MOEDAS ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Maely Vasconcelos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Maely Vasconcelos da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Maurício', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Tales (ref. - campanha) > PIX: (11) 9 5193-1717 (celular ~ esposa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Tatiane P. Araujo > PIX: 220.137.678--62', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Yasmin dos Santos > > PIX: 529.978.598-40 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Yasmin dos Santos de Oliveira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOMETRISTA: Yasmin dos Santos de Oliveira - PIX: 529.978.598-40', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOAY LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > BANCO: Bradesco | Agência: 3369 | Conta Corrente: 56456-7 I CNPJ: 68.571.041/0001-71 > ref. OS 11005', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > BANCO: Bradesco | Agência: 3369 | Conta Corrente: 56456-7 I CNPJ: 68.571.041/0001-71 > ref. OS 11006', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 01028- ID pedido: 14850238', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 03788- ID pedido: 148566225', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 03790 - ID pedido: 14889258', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 03804 - ID pedido: 14904501', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 10017 - ID pedido: 14927980', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 10018 - ID pedido: 14876695', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 10058 - ID pedido: 14889043', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 10059 - ID pedido: 14928117', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 3459 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 4102 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 4144 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 4148 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 4632 - ID pedido: 14868903', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 4633 - ID pedido: 14869086', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 635 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8639 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 865 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8653 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8663 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8664 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8684 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8692 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8775 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 879 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8827 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8829 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8830 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8859 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8860 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8863 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8864 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8874 - ID pedido: 13563849', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8899 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8907 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8913 - ID pedido: 13592372', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8925 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8927 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8936 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8947 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8954 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTOTAL HOYA LTDA > ref. OS 8959 -', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ORION REAL LTDA: Rodinho de pia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ORION REAL: Balas e biscoitos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICA E RELOJOARIA ALVORADA LTDA: Solda', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICA E RELOJOARIA ALVORADA LTDA: Troca de mola', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICA FREITAS: Montagem', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICA PARA TODOS > PIX: oticaparatodos32@gmail.com (e-mail) > ref. OS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICA STUDIO 7 > PIX: 35.128.190/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICAS FREITAS: OS 1308', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OTICAS FREITAS: Passagem', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OZ MATERIAIS PARA CONSTRUÇÃO ME: Tinta para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Oferta', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Outros investimentos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E CONFEITARIA PERUS LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E CONVENIENCIA PERUS LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: Margarina e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS E PAGUE MENOS LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: Baguete de frios e sonho', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: Café, lustra-móveis e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: Filtro de papel e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS E PAGUE MENOS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA E MERCADO LEVE MAIS PAGUE MENOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA FANTASIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA FANTASIA: Bolacha, bombons, cookies e pão de mel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA FANTASIA: Margarina e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA FANTASIA: Pão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA FANTASIA: Pão francêS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA FANTASIA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA L M P M: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA PERUS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA PIZZARIA E SELF SERVICE ANA CLAUDIA LTDA: Pão francêS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA PIZZARIA E SELF SERVICE ANA CLAUDIA LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA PIZZARIA E SELF SERVICE ANA CLAUDIA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA RENASCER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA RENASCER: Pão francês > Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA SANTA HELENA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA SANTA HELENA: Pão francês > Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA SKINA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PADARIA: Pão integral', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG* ADRIANA PRESTES DE MORAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG* JOSUE BATISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*ADECARCOMESERVAU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*ADRIANAPRESTESDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*AQUAPRIME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*BELLAMISS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*BENJAMIMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*CASSIOGONZALESDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*CENTRALDASCORES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*CLEITONRIBEIROTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*CLINICAODONTOLOG', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*CRIATIVACAMISETA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*DANIELLEFARIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*DONAALICE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*EDVALDOMANOELDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*EGNESTACIONAMENT', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*ESQUADRIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*FAMILIAK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*FERNANDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*GOLDENPARK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*JOSUEBATISTADEAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*JULIANATAVEIRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*LINCOLNCARDOSORE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*LUCASHENRIQUEBAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*MEGAESQUADRIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*NOVOSABOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*QUITANDATAKEU', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*RAMONACESSORIOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*RENATAKELLYRODRI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*REQUINTEBRECHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*RNCELL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*ROBSONFANTINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*ROSEMAREDEMORAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*SERGIOSHIGUEO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*SERGIOSHIGUEOHIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAG*TIAGOTESTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO DE BOLETO - BCO SANTANDER (BRASIL) S.A.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO DE BOLETO - BOLETOBANCÁRIO.COM TECNOLOGIA DE PAGAM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO DE EXTINTORES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO PARA DOUGLAS FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO PARA MERCADO PAGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO PARA NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'PAGAMENTO PARA ZECA RAÇÕES', 'juridica', NULL, True, NOW(), NOW());
