INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9828, 9830, 9834 e 9836', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9830', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9852', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9855, 9860 e 9861', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9899, 9900 e 9902', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9932, 9935, 9948 e 9951', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 993558 (2° ped), 9970 e 9973', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9981', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS 9994', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 010995, 10939, 11100, 11119, 11125 e 11138', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10192, 10196 e 10212', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10199 e 10955', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10205 e 10209', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10318 e 10319', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10323, 10359 e 10384', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10328 e 10331', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10338, 10354 e 10367', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10357 e 10358', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10364 e 10414', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10377 e 10382', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10465, 10529 e 10533', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10480 e 10486', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10510, 10511, 10527 e 10530', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10517 (0002) e 10523', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10536, 10549 e 10569', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10547 e 10548', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10587, 10588 e 10594', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10589, 10590 e 10601', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10619 e 10620 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10619 e 10620 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10642 e 10661', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10644, 10645 e 10657', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10645, 10648, 10662 e 10665', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10688, 10692 e 10693', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10703, 10709 e 10734', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10713 e 10714', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10716 e 10717', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10736 e 10745', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10746 e 10754', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10762, 10767, 10781 e 10787', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10788 e 10797', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10798, 10814 e 10817', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10812 (Vanda) e 10821 (10812 - Luciano)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10835 e 10839', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10897, 10898, 10912 e 10915', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10901, 10927, 10938 e 10995 (11007 - original)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10911 e 10932', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10926, 10933, e 10937', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10950, 10973, 11012, 11032 e 11033', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10967, 10972, 10981, 10982, 10990, 10991, 10992 e 10993', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 10979, 11025 e 11164', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 1101 e 1104', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 11034, 11035, 11036, 11040 e 11065', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 1107 e 1108', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 11077 e 11102', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 11127, 11132, 11143 e 11153', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 11148, 11184 e 11186', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 3831 e 3833', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4706 e 4709', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4735, 4740 e 4743', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4763 e 4764', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4785, 4787 e 4791', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4803, 4804 e 4826', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4807 e 4811', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4817 e 4827 (04640)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4820, 4823, 4834 e 4835', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4846 e 4847', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STYLE PLUS > PIX: 43.849.253/0001-47 (CNPJ) - ref. OS''s 4850, 4852, 4853 e 4854', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'STÚDIO 7: Montagem & Consertos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUCO: Tatiana e Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUMUP - PIX RECEBIDO - CP :08561701-GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUMUP - PIX RECEBIDO - CP :18236120-T. M COMERCIO VAREJISTA DE OTICA SOCI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUMUP - PIX RECEBIDO INTERNO - 00019 0298638037 GIGI C V O LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPEMERCADO VERAN: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO ASSAI: Utencilios para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO ASSAÍ (Filtro de café, biscoito, bala, emtre outros utencilios para a loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO ASSAÍ (Filtro de café, biscoito, bala, emtre outros utencilios para a lojas - QR CODE PIX ENVIADO - ASSAI ATACADISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO ASSAÍ: Compra de utencilios para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO ASSAÍ: Pacote de folha sulfite, 3 café, 2 alcool,', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO DIA: Pipocas de microondas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: 2 Açucares, 4 cafés, detergente, filtro de papel, sabonete, desinfetante e 2 biscoitos bauduco', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: 2 Café Caboclo, papel higiênico e pão francês, Lanche da Nicolly', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Alcool, Café, papel higiênico e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Café e multiuso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Café, detergente e desinfetante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Café, leite integral e papel higiênico (café do escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Cloro, pão, requeijão, manteiga e suco da Nicolly', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Itens para a loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Itens para a loja > Nicolas Coutinho da Silva > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Itens para as lojas > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Itens para o escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Itens para o escritório > Mike Rodrigues Gomes > PIX: (11) 9 4588-8760 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Multiuso, detergente e água sanitária', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Papel higiênico, filtro de papel bolacha rechada e café', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Pão francês, lanche da Nicolly e Frios', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO NAGUMO: Água sanitária e álcool líquido', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Achocolatado, Leite Integral, Mussarela, Pão francês e Presunto', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Café em pó', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Coca-cola', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Margarina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Margarina > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Margarina e pão francês > Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Margarina e pão francês > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Pão francês > Ariani Dias Fernandes Líbano > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Pão francês > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SANTA FÉ: Pão francês > Thiago Vinicius Andrade Siqueira > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SHIBATA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO SHIBATA: Pão francês > Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO TENDA: Café, papel A4 e sacola > Mike Rodrigues > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERA LTDA: Itens para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN LTDA: Milho de pipoca', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Achocolatado, bolo de abacaxi, maionese, pão de forma e sardinha enlatada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Açúcar', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Biscoito, pão de queijo e suco (Café especial para o dia das mães, ref. 13/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Bolo e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Bolo frape, leite integral, maionese e pão de forma', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Café', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Café > Nicolas Coutinho > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Café e desinfetante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Café e papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Café e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Café em pó e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Coca cola 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Copo descartável e papel toalha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Desinfetante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Desinfetante e detergente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Desinfetante e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Desinfetante, esponja e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Detergente e esponja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Detergente líquido', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Filtro de papel > Mike Rodrigues Gomes > PIX: (11) 9 4588-8760 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Filtro de papel e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Leite integral', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Leite integral, miojo, mortadela, pão francês e refresco em pó', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Leite integral, mortadela e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Margarina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Margarina e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Margarina e rosquinha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Margarina, pão de leite e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Milho de pipoca, refrigerante coca-cola e guaraná antártica', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Papel higiênico e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão de leite e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão de queijo congelado', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão francês e Lanche da Nicolly', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão francês e papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão francês e pão integral', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão francês e refresco em pó', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Pão francês, papel higiênico, copos e biscoito', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Refrigerante Coca+Fanta Guaraná 2L e Refrigerante Coca+Fanta Laranja 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Rosquinha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Saco para lixo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Água e pipocas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO VERAN: Água sanitária, papel higiênico e pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADO: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCADOVERAN: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUPERMERCAODO VERAN: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZ01 SUZANO SP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZANCOPI COPIAS E IMPRESSOES LTDA-ME: Tags de sacolas > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZANMI BAZAR E PAPELARIA LTDA: Folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZURAN BOMBONIERE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZURAN BOMBONIERE LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZURAN BOMBONIERE LTDA: Sacolas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZURAN BOMBONIERE LTDA: Sacolas papel kraft', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZURAN BOMBONIERE: Sacolas > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SUZURAN: Sacolas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA - Parcela 1/3 > PIX: 30.576.013/0001-74 (CNPJ - Espeed) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA - Parcela 2/3 > PIX: 30.576.013/0001-74 (CNPJ - Espeed) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA - Parcela 3/3 > PIX: 30.576.013/0001-74 (CNPJ - Espeed) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10005, 10054, 10071 e 10083', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1001, 1002, 1011 e 1012.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10040', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10043 (coloração)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10043, 10065, 10069, 10070 e 10076', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10048 e 10052', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1005', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10068 e 10085', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10084', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10089', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1013', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10138, 10142 e 10145', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10156', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1024 e 1026', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1027', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1029, 1030, 1031 e 1032.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 10301', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 1040', 'juridica', NULL, True, NOW(), NOW());
