INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'RESCISÃO: Mike Rodrigues Gomes - Acordo 2/7 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Mike Rodrigues Gomes - Acordo 3/7 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Mike Rodrigues Gomes - Acordo 4/7 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Mike Rodrigues Gomes - Acordo 5/7 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Mike Rodrigues Gomes - Acordo 6/7 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nathalia Carolina Cardoso Ribeiro Faustino - Acordo 1/2 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nathalia Carolina Cardoso Ribeiro Faustino - Acordo 2/2 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 1/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 10/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 2/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 3/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 4/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 5/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 6/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 7/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 8/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicolas Coutinho da Silva - Acordo 9/10 > PIX: analiviaxavier072@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Nicollas Henrique Souza dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 1/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 10/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 11/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 12/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 2/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 3/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 4/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 5/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 6/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 7/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 8/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rogério Aparecido de Morais - Acordo 9/12 > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 1/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 10/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 11/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 12/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 13/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 2/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 3/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 4/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 5/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 6/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 7/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 8/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Rosangela Aparecida Dejane Felisbino - Acordo 9/13 > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Samuel Henrique da Silva - Acordo 1/4 > PIX: 492.256.288-54 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Samuel Henrique da Silva - Acordo 2/4 > PIX: 492.256.288-54 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Samuel Henrique da Silva - Acordo 3/4 > PIX: 492.256.288-54 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Samuel Henrique da Silva - Acordo 4/4 > PIX: 492.256.288-54 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Sandy Cristina da Silva Santos - Acordo 1/3 > PIX: (11) 9 77543226 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Sandy Cristina da Silva Santos - Acordo 2/3 > PIX: (11) 9 77543226 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Sandy Cristina da Silva Santos - Acordo 3/3 > PIX: (11) 9 77543226 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Stephane Soares Lima - Acordo 1/1 > PIX: 505.510.598-42 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Vanessa Mendes da Silva - Acordo 1/6 > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Vanessa Santana Ribeiro - Acordo 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Vanessa Santana Ribeiro - Acordo 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Vanessa Santana Ribeiro - Acordo 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 1/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 2/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 3/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 4/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 5/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 6/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 7/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Wevilly de Souza Fernandes Líbano - Acordo 8/9 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Yasmin dos Santos - Acordo 1/3 > PIX: (11) 9 8973-0715 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Yasmin dos Santos - Acordo 2/3 > PIX: (11) 9 8973-0715 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Yasmin dos Santos - Acordo 3/3 > PIX: (11) 9 8973-0715 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 1/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 10/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 11/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 12/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 13/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 14/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 2/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 3/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 4/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 5/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 6/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 7/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 8/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Zaine de Lima Siqueira - Acordo 9/14 > PIX: 275.783.178-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 1/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 2/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 3/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 4/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 5/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 6/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 7/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESCISÃO: Érika de Oliveira Gomes - Acordo 8/8 > PIX: 481.332.818-06 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RESTAURO ÓTICA: CONSERTO ÓCULOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RETIRADA DA TATY (Vale transporte para ir para as lojas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RFB-DARF CODIGO DE BARRAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RGO SILVA JUNIOR. C: SAMUEL HEN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RIZZO DECOR EIREL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIA LTDA: COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIA LTDA: COMPRA DE ARMAÇÕES - PARCELA 1/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA - Parcela 1/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA - Parcela 1/7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA - Parcela 3/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA - Parcela 4/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA - Parcela 5/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ROB SOL INDUSTRIAL LTDA - Parcela 6/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RODOANEL LESTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RONILDO SOUZA: BANNERS PARA A LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RPG COMERCIO DE ALIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'RPO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Recarga Celuar - INT PRE PAGOXXXXX 1171', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Recebiemnto Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Recebimento Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Receituário - PIX ENVIADO - CP :10573521-PIX MARKETPLACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Remoção de entulho', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Retirada de moedas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Retirada de moedas (antiga gestão)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Retirada de moedas (verificando, pois está faltando )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Retirada família', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Retiradas de moedas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Retiradas de moedas (SÃO MATEUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Rolinho para pintura das peças', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'S L PANIFICACAO E CONVENIENCIA LTDA: Saco de entulho', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'S L PANIFICAÇÃO E CONVENIÊNCIA LTDA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'S L PANIFICAÇÃO E CONVENIÊNCIA: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - CLÍNICA PERUS RGI 1038479522', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA MAUA RGI 06001601037027800', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA MAUÁ )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA PERUS RGI 0111589720', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA PERUS RGI 0111589720 - não é nossa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA RIO PEQUENO RGI 0874132747', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA RIO PEQUENO RGI 0874132747 > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA RIO PEQUENO RGI 1963881886', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA RIO PEQUENO RGI 1963881886 (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SUZANO )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SUZANO 2 RGI 0046782494', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SUZANO RGI 0046736387', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SUZANO RGI 0046736387 (ref. maio/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SUZANO RGI 0046736387 (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SÃO MATEUS RGI 1956067867', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABESP - LOJA SÃO MATEUS RGI 1956067867 (ref. set/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SABORES DA TERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SACOLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SACOLAO DIRETAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SACOLAO DO MINEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SACOLAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - ACORDO 2/3: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - ADIANTAMENTO SALÁRIO: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - ADIANTAMENTO SALÁRIO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - PAGAMENTO DE SALÁRIO: CRISTIANE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - PAGAMENTO DE SALÁRIO: KETHILYN SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - PAGAMENTO DE SALÁRIOS: CRIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - PAGAMENTO DE SALÁRIOS: NATALY VARGES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - PAGAMENTO PARA KETHILYN SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO ( João vitor 24/08 á 05/09 )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO 2/2: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO DIVULGAÇÃO: EMILY VITÓRIA LIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO DIVULGAÇÃO: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO DIVULGAÇÃO: ROGÉRIO (TESTE)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO DIVULGAÇÃO: TAMIRES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: ANA CLÁUDIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: ANA MARIA (DIAS TRABALHADOS 31/03 A 01/04)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: ARIANI DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: ARIELE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: FRANCINEIDE DUARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: LARISSA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: MARIA CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: TAMIRES MACIEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALARIO - SALÁRIO: YASMIN SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALDANHA LANCHES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALGADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ACORDO 1/3: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ACORDO 3/3: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ACORDO: KAILANE CRISTILLY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ARIANE GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ARIANI DIAS FERNANDES CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - ARIELLI APARECIDA FELICIANO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - COMISSÃO DIVULGADORA ARIANI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Ana Paula Aparecida Moreira da Silva Yuki > PIX: 375.938.028-09 (CPF) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Ana Paula Aparecida da Silva Yuki > PIX: 375.938.028-09 (CPF) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Felipe Roger Miranda > PIX: 408.160.988-83 (CPF) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Kathleen dos Santos Campos > PIX: kathleendossantoscamposkety@gmail.com (e-mail) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Kayllaine Pereira Alves de Araújo - Parcela 1/3 > PIX: 426.663.838-81 (CPF) - ref. mai - ago/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Kayllaine Pereira Alves de Araújo - Parcela 2/3 > PIX: 426.663.838-81 (CPF) - ref. mai - ago/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Kayllaine Pereira Alves de Araújo - Parcela 3/3 > PIX: 426.663.838-81 (CPF) - ref. mai - ago/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF) - ref. 03/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Larissa Dias Fernandes Cardozo > PIX: larissadiss766@gmail.com (e-mail) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Luana Cristina Martins Campos > PIX: luanabraz0912@gmail.com (e-mail) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF) - ref. > FERIADO (aniversário de Mauá)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Thiago Vinicius Andrade Siqueira - Parcela 1/3 > PIX: fenixdrideex@gmail.com (e-mail) - ref. mai - ago/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Thiago Vinicius Andrade Siqueira - Parcela 2/3 > PIX: fenixdrideex@gmail.com (e-mail) - ref. mai - ago/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Thiago Vinicius Andrade Siqueira - Parcela 3/3 > PIX: fenixdrideex@gmail.com (e-mail) - ref. mai - ago/2025', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'SALÁRIO - HORA EXTRA: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail) - ref. > FERIADO', 'juridica', NULL, True, NOW(), NOW());
