INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11841', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11861', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11862', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11863 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11863 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11867', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11884', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11903 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11903 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11924', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11925', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 11943', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VISION PRIME > PIX: 47.392.457/0001-52 (CNPJ) - ref. OS 3689', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO CELULAR 00000159786774 - PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2627 3921 - PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2627 3921 - PERUS (cancelamento)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2669 9797 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 1194 - SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 1194 - SUZANO (NUBANK - Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 4176 - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 6825 - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 6833 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 6833 - ESCRITÓRIO (NUBANK - Junior)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2677 9985 - SUZANO 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2678 1991 - RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO FIXO E INTERNET 8999 2678 1991 - RIO PEQUENO (PIX) Roberto - 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO TELEFONE FIXO 8999 2669 9797 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIVO TELEFONE FIXO 8999 5983 0874 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIXEN - SISTEMA LJ MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIXEN - SISTEMA LJ RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIXEN - SISTEMA LJ SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIXEN - SISTEMA LJ SUZANO 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIXEN - SISTEMA LJ SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VIZION PRIME :Parcela 03/03', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'VT referente os dias trabalhados, período 24/07-)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Vale Maria Cristina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Vale Transporte Cleberson', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Ventilador', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'WBL GRAFICA E EDITORA LTDA: Adesivos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'WELLINGTON JORDAO DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'WEVILLY DE SOUZA FERNANDES LÍBANO: Pagamento de Consulta Oftalmologista', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'WILLIAN SAIRESDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'XEROX (cópia de receitas) > Larissa Dias > PIX: larissadiss766@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Xerox de Receituário - PIX ENVIADO INTERNO - 00019 0192739891 LARISSA DIAS FERNANDES CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'YAPAY PAGAMENTOS ONLINE LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'YHVH', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'YOU COM FL 040097', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'YUUKIBOX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'YUZENSEIKO PAPELARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Yampa +Lucro Mensal', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Yampa +Lucro Mensal 2024', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Yasmin recepcionista - pix: 240.904.838-24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ZAP CLOUD - INTERLIGACAO COM WHATSAPP (PARA INFORMAR CLIENTES)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ZEISS VISION > PIX QR Code > ref. OS 3674', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ZEISS VISION > PIX QR Code > ref. OS''s 9512', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ZEISS VISION > PIX QR Code > ref. OS''s 9513', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Zapier - Integração de Software', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Zapier - Integração de Software - diferença ficou no cartão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ajuste almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ajuste almoço loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'almoço - BURG KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'combustivel - COMPRA CARTAO - NO ESTABELECIMENTO MARCO ZERO REVENDEDOR SANTANA D', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'comida - PIX ENVIADO - JENNIFER TAUANY SIMOES DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de 2 plaquetas de silicone', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de gelo em guarulhos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de gelo em suzano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de pneus para o carro - PIX ENVIADO - CP :60701190-VAGNER NUNES DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de pães na padaria santa helena', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de solares de brinde - yao', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de solares de brinde - yao (17 solares valor 5,00 reais cada)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra de solares de brinde - yao (90 solares valor 5,00 reais cada)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra mercado livre 87334564725', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compra no mercado livre 68631202626', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras de lentes - PIX: 305760130001/74 - PIX ENVIADO - ESPEED IMPORTACAO E EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras de material de construção para calçada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras de solares para a rede', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 65383204679', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 67439876420', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 70514146103', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 73645509382', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 74063621282', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 75286504930', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 76087882620', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 78776380776', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 80044005895', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 80645238599', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 81631725638', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 83175880250', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 83702200789', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras mercado livre 86539603514', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras no mercado livre 68290729412', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras no mercado livre 74763494839', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras no mercado livre 81332415946', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'compras no mercado para festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'corte de cabelo - QR CODE PIX ENVIADO - JEFERSON MITSUO TAKEUTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'descobrir a diferença de valores', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'descobrir esta falta de dinheiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'descobrir este valor de diferença', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'descobrir está diferença de valores', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'descobrir o que aconteceu', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'dia trabalhados freelance - PIX ENVIADO - CLEBERSON RIBEIRO DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'dia trabalhados freelance - PIX ENVIADO - Esther Barbosa - Chave pix celula (54) 95766-8817 referente ao dia 13/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'dia trabalhados freelance - PIX ENVIADO - Esther Barbosa - Chave pix celula (54) 95766-8817 referente ao dia 26/04 27/04 e 30/04', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'dinheiro em caixa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'dinheiro em conta', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'eduardo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'entrada de 30% do valor total da festa - Eliana Santos Mourão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'frete Conciliação - QR CODE PIX ENVIADO - PIX MARKETPLACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'lanche para curso - COMPRA CARTAO - NO ESTABELECIMENTO TOQUE DE MESTRE SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'mercado para festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'mãe da taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pagamento Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pagamento cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pagto VT Cleberson para Trabalhar - PIX ENVIADO - CLEBERSON RIBEIRO DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pagto da franquia de mauá', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pagto estacionamento para compra de solares', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pagto funcionarios das festas (', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'parcelamento do cartão nubank - entrada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pedágio - COMPRA CARTAO - NO ESTABELECIMENTO SPMAR SAO PAULO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pix - COMPRA CARTAO - NO ESTABELECIMENTO JAPALLU REST E PIZZ SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'pro labore', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'recebimento Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'recebimento cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'reecbimento cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'resistencia e lamapada para o escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'retirada de moedas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'semana trabalhados freelance - PIX ENVIADO - CLEBERSON RIBEIRO DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'separação das moedas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'troco de compras de material de construção', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'vendas e entrada em dinheiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'vendas e entradas em dinheiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÁGUA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÁGUA - COMPRA ÁGUA LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÁGUA - PAGAMENTO DE ÁGUA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÁGUAS PERUÍBE LTDA ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICA OPÇÃO: Montagens & Consultas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS BELLARTE > > PIX: 510.168.468-60 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS BELLARTE > PIX: 510.168.468-60 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS BELLARTE > PIX: 510.168.468-60 (CPF) B', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS BELLARTE: CONSERTOS, MONTAGENS OU SOLDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS CENTER: Passagem, ref. OS > Ariani Dias (estorno) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS DINIZ: Lentes de contato', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS JRL > PIX: 42.149.655/0001-76 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS JRL > PIX: 51.766.595/0001-21 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 05/06-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 12/06-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 15/05-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 19/06-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 22/05-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 26/06-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS KING - ref. 29/05-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS MESSIAS - ref. 22/05-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS MESSIAS - ref. 29/05-', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS OPÇÃO : CONSERTOS, MONTAGENS OU SOLDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS RAAH: Passagem', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ÓTICAS REINO DOS ÓCULOS: Montagem > PIX: (11) 9 9284-3371 (celular) - ref. OS 6971', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ 2° RENEGOCIADO: OPTOTAL HOYA LTDA >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ Banco Nubank - AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular)AGUINALDO ANJOS - LOST INFORMÁTICA > Parcela 2/3 > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ GUIA CANCELADA PELA PREFEITURA: TAXA DE LICENÇA E FISCALIZAÇÃO DE FUNCIONAMENTO - Parcela 2/3 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ GUIA CANCELADA PELA PREFEITURA: TAXA DE LICENÇA E FISCALIZAÇÃO DE FUNCIONAMENTO - Parcela 3/3 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ Lançamento a maior (ERRADO) - ENEL 0049320513 - LOJA RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ Não foi localizado em nenhum banco p/ conciliação - AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ Não foi localizado em nenhum banco p/ conciliação - AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular)AGUINALDO ANJOS - LOST INFORMÁTICA > PIX: 11) 9 7468-1969 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 15/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 16/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 17/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 18/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 19/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 20/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 21/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 22/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 23/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 24/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 25/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 26/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 27/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 28/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 29/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 30/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 31/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 32/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 33/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 34/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 35/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 36/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 37/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 38/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 39/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 40/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 41/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 42/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 43/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 44/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 45/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 46/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 47/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 48/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 49/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 50/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '⚠ RENEGOCIADO - ACORDO: ACERTO FRANQUIA > Parcela 51/54 > PIX: 39.406.028/0001-69 (CNPJ) >', 'juridica', NULL, True, NOW(), NOW());
