INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 53/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 54/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 55/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 56/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 57/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 58/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 59/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 6/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 60/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 61/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 62/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 63/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 64/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 65/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 66/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 67/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 68/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 69/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 7/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 70/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 71/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 72/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 73/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 74/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 75/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 76/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 77/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 78/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 79/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 8/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 80/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 81/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 9/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '4 Custos Variáveis', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '4 PILHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '4 galões de água', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '4.2.3 Fornecedores de Lentes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '4.4.3 Gastos com Médicos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5292: JOAQUIM JOSÉ DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5302, LETÍCIA CAETANO COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5410: PAULINO FRANCISCO DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5469: SAMUEL DE MELO FERRAZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5529: JOSÉ ADIJACIR DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5534: HIDEKI EGUCHI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5544: DANIEL SANTOS BARRETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5575: ROBERTO ANTÔNIO JULIÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5666: VILMA BALBINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5716: MARIA DA CONCEIÇÃO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5810: FRANCISCO ALVES MARIANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5812: CARLOS ALBERTO GABRIEL DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5902: CLAÚDIO PEDRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5907: SIZUME AKIYAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5908: THAYSSA ROBERTA LIMA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5939: MARINA MARQUES DE MOURA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5967: SANDRA REGINA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '5981: FÁBIO BATISTA SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6.1.8 SAÚDE DOS OLHOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6064: ANILTON FIGUEIREDO DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6106: STEFFANY APARECIDA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6136: JORGE YAMAGUCHI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6143: ANA MARIA VICENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6158: JOÃO SANTANA DE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6162: ANILTO FIGUEIREDO DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6162: ANILTON FIGUEIREDO DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6265: EVA BENEDITA DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6335: ELZA TEREZINHA DE SOUZA SANTOS DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6364: MARA REGINA DE ALMEIDA BIZZI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6394: CATARINA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6398: EUNICE HIROSE KOIDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6401: ALUÍSIO SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6407: LUZIA MARTINS JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6419: PEDRO HOMERO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6446: IRENE MARIA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6460: MARIA APARECIDA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6461: VALDINEIA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6495: EMERSON LIMA DAS NEVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6548: ELAINE CRISTINA APARECIDA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6600: DERNIVAL DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6608: MARCOS MASSAYUKI TAKATORI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6636: MASAKO MUNEMOTO TAKIKAWA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6648: JOÃO HORÁCIO EVANGELISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6648: JOÃO HORÁCIOB EVANGELISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6652: SILNAVA MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6653: VANDERLEIA DAS GRAÇAS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6669: JOSÉ NETO MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6671: LEIDE JESUS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6674: ELENI MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6675: RAFAEL MELLO ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6681: PORFÍRIO NOGUEIRA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6687: CAMILA DE SOUZA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6711: RENILDA ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6714: GEOVANIO DE OLIVEIRA CALIXTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6720: JULIANO VICENTE VIVEIROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6724: RAYME BENEDICTO MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6725: MARCELO HENRIQUE DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6726: RAYSSA DIAS SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6727: MARIA MADALENA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6731: GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6744: ROBERTO CARLOS DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6747: SARA CAETANO VIANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6749: ANTÔNIO MARIA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6752: RENATO MIRANDA DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6761: NIVALDO BATISTA NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6763: MARIA DO CÉU TOMAZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6764: MARCOS VINIUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6766: VANDILSON RAMOS DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6769: MÔNICA DA SILVA PESSOA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6772: AUGUSTA EUZÉBIO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6774: MARIA PAULA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6784: SANDRA PRAVITZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6786: FABRÍCIA DE JESUS PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6787: APARECIDA PAULA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6795: JOANA FRANCISCA EVANGELISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6802: LUCAS GABRIEL FRACAROLE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6806: MARIA DO PERPÉTUO SOCORRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6813: RITSUKO ROSA KITAGAWA WATANABE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6816: MARIA CRISPINA EVANGELISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6818: MARIA APARECIDA DA NEVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6825: ERIKA SANTOS NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6827: ARNO BECK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6832: MARCOS ROBERTO DEODATO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6835: SHIRLEI DA SILVA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6852: MARIA DAS GRAÇAS PINTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6853: LUANA APARECIDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6854: EDILON DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6859: IVONETE CRUZ DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6860: CARLA FERNANDES NUNES BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6865: ROSIMEIRE DE JESUS CASSIMIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6866: ROSILEIDE SOUZA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6868: EUNICE FERRAZ FRANCO CAPELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6869: SIMONE IGNÁCIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6875: JOÃO ECRÉDIO GONÇALVES DE MATOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6877: IVALDO CARVALHO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6881: EDVÂNIA RODRIGUES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6886: ADEMAR BARROS BEZERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6887: ZENAIDE SANTOS ROSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6905: IVANETE DA SILVA VILLARROEL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '6906: EDVALDO LEAO BONI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '7005: MÁRIO AKIRA TIBA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '7019: NILTOON DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '7023: CECI FÉLIX FARIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '857: NEUZA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '873: JURACY PAULO LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '879: CELSO CASTILHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '914: MARIO TADEU DE ASSUNÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '987: JANETTI QUIRINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'A P NOVO OURO NEGRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ABERTURA CNPJ: GI - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ABERTURA CNPJ: GI - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ABERTURA CNPJ: GI - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ABERTURA CNPJ: GIGI - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ABERTURA CNPJ: GIGI - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ABERTURA CNPJ: GIGI - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACAI EXPRESS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACERTO FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACESSÓRIOS - MELLO COMERCIO E INDUSTRIA DE PRODUTOS OPTICOS LTDA: COMPRA DE EQUIPAMENTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACF EMPORIO DO REAL UTILIDADES DOMESTICAS LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACF EMPORIO DO REAL UTILIDADES DOMESTICAS LTDA: Biscoito e pão de forma', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACF EMPORIO DO REAL UTILIDADES DOMESTICAS LTDA: Papel folha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACF EMPORIO DO REAL UTILIDADES DOMESTICAS LTDA: Água sanitária e café em pó', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACF EMPORIO DO REAL UTILIDADES DOMESTICAS LTDA: Água sanitária, cola +corre e desinfetante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Parcela 1/4 > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Parcela 2/4 > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Parcela 3/4 > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Ana Paula Aparecida Moreira da Silva Yuki - Parcela 4/4 > PIX: 375.938.028-09 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Ariani Dias Fernandes Líbano - Parcela 1/2 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Ariani Dias Fernandes Líbano - Parcela 2/2 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 1/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 10/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 2/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 3/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 4/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 5/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 6/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 7/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 8/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Larissa Dias Fernandes Cardozo - Parcela 9/10 > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Mike Rodrigues Gomes - Parcela 1/2 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Mike Rodrigues Gomes - Parcela 2/2 > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Vanessa Mendes da Silva - Parcela 1/4 > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Vanessa Mendes da Silva - Parcela 2/4 > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Vanessa Mendes da Silva - Parcela 3/4 > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Vanessa Mendes da Silva - Parcela 4/4 > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Wevilly de Souza Fernandes Líbano - Parcela 1/2 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO - RESCISÃO: Wevilly de Souza Fernandes Líbano - Parcela 2/2 > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 1/4: GIGA+ FIBRA 4716778 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 1/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 2/4: GIGA+ FIBRA 4716778 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 2/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 3/4: GIGA+ FIBRA 4716778 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 3/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 4/4: GIGA+ FIBRA 4716778 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 4/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 5/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 6/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 7/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO 8/8: SABESP - ESCRITÓRIO SUZANO RGI 0685311252', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO > ALUGUEL & FRANQUIA > Rio Pequeno - Loja (ref. dez/2024 e jan/2025) > parcela 1/134 > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO > ALUGUEL & FRANQUIA > Rio Pequeno - Loja (ref. dez/2024 e jan/2025) > parcela 10/134 > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ACORDO > ALUGUEL & FRANQUIA > Rio Pequeno - Loja (ref. dez/2024 e jan/2025) > parcela 100/134 > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW());
