INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 08/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 08/2025) - GIOVANNA COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 08/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 09/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 09/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 09/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 09/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 09/2025) - GIOVANNA COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 09/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 10/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 10/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 10/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 10/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 10/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 10/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2023) - Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 11/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 12/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 12/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 12/2023) - Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 12/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 12/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 12/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Festa - Buffet', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Festa bárbara - 18/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Flores para festa do dia 13/07 - pix: 11917086262', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Folha Sulfite > Thiago Vinicius Andrade Siqueira > PIX: fenixdrideex@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Folha de Pagamento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Franquia Mauá', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Franquia Suzano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS - NATHALIA CAROLINA CARDOSO: REFERENTE A 30 DIAS DE FÉRIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS - SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Aline Cristina Moreira da Cunha (ref. 11/09 - ) > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Aline Cristina Moreira da Cunha (ref. 15/04 - ) > Parcela 1/2 > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Aline Cristina Moreira da Cunha (ref. 15/04 - ) > Parcela 2/2 > PIX: 537.903.908-10 (CPF) ~ (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Aline Cristina Moreira da Cunha (ref. 15/04 - ) > Parcela 2/2 > PIX: 537.903.908-10 (CPF) ~ (moedas escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Aline Cristina Moreira da Cunha > PIX: 537.903.908-10 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 1/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 2/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 3/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 4/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Ariani Dias Fernandes Líbano - Parcela 5/5 > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Jocicreide Macedo Barbosa Santos - Parcela 1/2 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Jocicreide Macedo Barbosa Santos - Parcela 2/2 > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 1/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 2/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 3/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FÉRIAS: Nathalia Carolina Cardoso Ribeiro Faustino - Parcela 4/4 > PIX: 463.593.658-98 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GABRIELLE DA SILV - PEUGEOT 206', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CNPJ GI COMERCIO > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CNPJ GIGI COMERCIO > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CNPJ GIOVANNA COMERCIO > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CNPJ TM COMERCIO > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CNPJ TMO COMERCIO > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CPF Giovanna Mello > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > E-CPF Tatiana Mello > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAINEN CERTIFICADORA > PIX: 43.467.415/0001-82 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GALÃO DE ÁGUA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GANHA TODOS CASHBACK E INTERMEDIAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GARE ICMS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GARE ICMS (ref. 01/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GARE ICMS (ref. 02/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GAROTA DE SUZANO: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - CEMEAP - EXAME ADMISSIONAL: ALINE CRISTINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - CEMEAP - EXAME DEMISSIONAL: SAMUEL HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - CENTRO MÉDICO CLUBE DS - SICOOB', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - CENTRO MÉDICO CLUBE DS - SICOOB (ACERTO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - CENTRO MÉDICO CLUBE DS - SICOOB (DIFERENÇA)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - CONSULTA OFTALMMOLOGISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO - 1° QUINZ. DEZEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO - 2° QUINZ. DEZEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO - 2° QUINZ. SETEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 1° QUINZ. ABRIL (PARCELA 1/2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 1° QUINZ. ABRIL (PARCELA 2/2)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 1° QUINZ. FEVEREIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 1° QUINZ. JANEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 1° QUINZ. MARÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 2° QUINZ. FEVEREIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 2° QUINZ. JANEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO 2° QUINZ. MARÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO- 1° QUINZ. NOVEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO- 1° QUINZ. OUTUBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: EDUARDO- 2° QUINZ. NOVEMBRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: GLEICE APARECIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: GUILHERME SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: LAUDICEIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: MAELY VASCONCELOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: MARKO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - OPTOMETRISTA: MAURÍCIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - PAGAMENTO PARA CLÍNICA CLUBE DS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - PAGAMENTO PARA FREELANCE CLÍNICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - PAGAMENTO PARA OPTO EDUARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - QUALY SUPORTE EMPRESARIAL: EXAME ADMISSIONAL - ALDENIR PAULA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - QUALY SUPORTE EMPRESARIAL: EXAME ADMISSIONAL - ALINE DA CRUZ SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - QUALY SUPORTE EMPRESARIAL: EXAME ADMISSIONAL - EMERSON WILLIAM DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - QUALY SUPORTE EMPRESARIAL: EXAME ADMISSIONAL - ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - QUALY SUPORTE EMPRESARIAL: EXAME DEMISSIONAL - ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GASTO COM MÉDICOS - ÓTICA INARÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GELADEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GELADEIRA > Vagner > PIX: (11) 9 6611-6826 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GELADEIRA CONSUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GIFT LAND ARTIGOS PARA PRESENTES LTDA: Bexigas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GIGA+ FIBRA 4716778 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILBERTO DE CAMAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Entrada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 1/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 10/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 11/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 12/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 2/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 3/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 4/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 5/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 6/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 7/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 8/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GILSON PROPAMAX (LOTÉRICA) - Parcela 9/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GLOBAL GPS SEGURANÇA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GLOBAL TRACK - GPS (CARRO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GOLFETTO COMERCIO DE BOLOS LTDA: Bolo de laranja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GONÇALVES PADARIA E MERCEARIA: Pão francês > Carolina Rodrigues da Silva > PIX: carolinarodrigues297@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GONÇALVES PADARIA E MERCEARIA: Pão francês > Mike Rodrigues Gomes > PIX: (11) 9 4588-8760 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GOOGLE INTERNET LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GPS: Guia da Previdência Social (competência 06/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GPS: Guia da Previdência Social (competência 10/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GPS: Guia da Previdência Social (competência 11/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GPS: Guia da Previdência Social (competência 11~12/2022, ref. 13° salário)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GPS: Guia da Previdência Social (competência 12/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRATIFICAÇÃO DE NATAL: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DAS ARMAÇÕES E ESTOJOS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DAS ARMAÇÕES, Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DAS ARMAÇÕES: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DE ARMAÇÕES: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DE ESTOJOS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DE FLANELAS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DE LIMPA LENTES: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DE SAQUINHO SOLAR: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DOS ESTOJOS E FLANELAS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAVAÇÃO DOS ESTOJOS: Magno dos Reis > PIX: (11) 9 1614-8650 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAXA DAS PORTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GRAXA NAS PORTAS - William > PIX: (11) 9 7176-5828 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GUIA DE RECOLHIMENTO - Fundo Especial de Despesa - FEDTJ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GUIA DE RECOLHIMENTO - Fundo Especial de Despesa - FEDTJ > CO-EXECUTADA Sônia Maria Peracini', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'GUIA DE RECOLHIMENTO - Fundo Especial de Despesa - FEDTJ > CO-EXECUTADO Paulo de Oliveira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Galões de água', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Gelo festa nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'H FARIA CEREAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'H O T BIJUTERIA PRESENTES EIRELI ME: Brindes para o dia das mães', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HAJA LUZ ELÉTRICA: Troca de capacitor, lubrificação e alinhamento das portas > PIX: (11) 9 4758-2162 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HASHI EXPRESS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HASTEN MARKETING E PRODUÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HI CHICKEN FOODS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HIPER D AVO SUZANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 1/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 2/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 3/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 4/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 5/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 6/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 7/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Bruna Giovanna Cardoso > Parcela 8/8 > PIX: 436.984.648-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Rodrigo da Silva Caineli > Parcela 1/2 > PIX: (11) 9 4077-0091 (celular) - ref. Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Rodrigo da Silva Caineli > Parcela 1/2 > PIX: (11) 9 4077-0091 (celular) - ref. Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Rodrigo da Silva Caineli > Parcela 1/2 > PIX: (11) 9 4077-0091 (celular) - ref. Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Rodrigo da Silva Caineli > Parcela 2/2 > PIX: (11) 9 4077-0091 (celular) - ref. Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Rodrigo da Silva Caineli > Parcela 2/2 > PIX: (11) 9 4077-0091 (celular) - ref. Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HONORÁRIOS: Rodrigo da Silva Caineli > Parcela 2/2 > PIX: (11) 9 4077-0091 (celular) - ref. Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HORET FRUT VIDA: Coentro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HORTFRUTI OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HOS STA MARIA DE SUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HOSPITAL DO CELUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HOSPITAL DO CELULAR: CHIP TIM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HOSPITAL DO CELULAR: PELÍCULA DE VIDRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HYPE MÍDIA - Trafégo pago', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HYPE MÍDIA - Trafégo pago - Pix email: contato@hypemidia.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'HYPE MÍDIA - Trafégo pago - Pix email: diretoria@hypemidia.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Hospital dos Óculos >Plaquetas RayBan > Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Hype Mídia - Parc. 1/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 04/2021 (1° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 04/2021 (1° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 04/2021 (2° parte)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 04/2021 (2° parte) - Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 09/2022 >', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 11/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 11/2022 (Juros/Multas)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 12/2022', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional - 12/2022 (Multa)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ICMS: Simples Nacional 01/2023', 'juridica', NULL, True, NOW(), NOW());
