INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 8/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '1° ACORDO: OPTOTAL HOYA LTDA - Parcela 9/32', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2 CARIMBOS CARTÃO FIDELIDADE - GIGI COMERCIO VAREJISTA DE OTICA LTDA > PIX: 51.837.184/0001-80 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2 pacotes de papel glossy fino para panfletos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2/2 - Pagamento mesas e cadeiras festa nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2/2 pagamento Bárbara Ambiel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2026: MONICA LAURINDO MARQUES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2122', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2154: VARDETE HENRIQUE AFONSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2162', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2173', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2174', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2176', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2177', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2180', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2181', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2207: MARIA RODRIGUES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2221: JOSÉ ALVES SOBRINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2273: FERNANDA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2304: NARIA MARIA GRABALOS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2352: MARIA LILIANA MEDEIROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2362: DANILO GABRIEL SILVA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '24/12 12:16 FINAMIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2437: JOSÉFA AMÉLIA DE ALMEIDA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '25 DE MARÇO : Cordão tecido (15 unidades )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '25 DE MARÇO : DEZENA - Cordão silicone (15 unidades )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '25 DE MARÇO : Flanela microfibra', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '25 DE MARÇO :Óculos de segurança (04 unidades)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '25 DE MARÇO: Estojos ( 50 unidades )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '25 DE MARÇO: Porta serviços ( 50 unidades )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2555: JOSÉ SÉRGIO CONCEIÇÃO DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2556: ELIANE DE SALES SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2582: GIOVANNA MARIA DA SILVA BRAGA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2595: VALÉRIO SANTOS DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2713: VINÍCIUS BAPTISTA DE VASCONSELOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2721: JOSÉ ZEZITO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2728: JUDITE BARBOSA SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2735: GUILHERME CALEBE MESQUITA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2771: NOELI IARA DOS SANTOS DA SILVA ROSÁRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2803: MARIA DAS GRAÇAS MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2814: JOSÉ AGOSTINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2842: MARIA ELIVETE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2845: SILVANA DE PAULA SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2846: MARIA SALETE VIEIRA SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2847: SOLANGE DE PAULA SOUZA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2848: CLEYDIANE COSTA CARDOSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2850: ARQUIMEDES DE JESUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2855: PAOLA BARRETO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2858: PRISCILA RAMOS DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2859: GILBERTO EVANGELISTA DA SILVA PIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2896: ELISABETE APARECIDA SILVESTREIM DA LUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2899: MARIA JOSÉ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2907: FRANCISCA CLEUDE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2912: ELIENE CABRAL DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2925: ELVIO MENDONÇA ERENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2944: EDINALVA MOREIRA DOS SANTOSQ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2964: VANDA MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2965: EDNEIDE DOS SANTOS TAVARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2973: MARCILENE APARECIDA RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2982: FÁBIO BIANCO TEIXEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2983: VALQUIRIA CAMPOS DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2984: MARIA ELIZABETH PEREIRA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2986: ANA MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2988: ELIANE DE SALES SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2989: JANILEIDE NASCIMENTO TENÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2990: MARIA JOSÉ DE ARAÚJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2992: KAREN SUKOUSKI BERTOLINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2995: FRANCISCO HENRIQUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2K CONSERTOS - KENNETH THYAGO SAKAMOTO - > PIX: (11) 9 1357-6019 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2K CONSERTOS - KENNETH THYAGO SAKAMOTO > PIX: (11) 9 1357-6019 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2K CONSERTOS - KENNETH THYAGO SAKAMOTO > PIX: 301.771.888-39 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 1/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 10/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 11/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 12/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 13/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 14/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 15/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 16/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 17/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 18/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 19/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 2/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 20/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 21/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 22/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 23/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 24/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 25/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 26/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 27/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 28/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 29/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 3/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 30/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 31/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 32/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 33/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 34/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 35/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 36/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 37/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 38/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 39/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 4/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 40/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 41/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 42/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 43/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 44/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 45/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 46/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 47/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 48/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 49/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 5/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 6/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 7/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 8/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: COLÉGIO INTEGRADO LUMBINI: Nicolly Mello de Camargo - Parcela 9/49 > PIX: 00.875.904/0001-60 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 1/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 10/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 11/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 12/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 13/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 14/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 15/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 16/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 17/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 18/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 19/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 2/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 20/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 21/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 22/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 23/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 24/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 3/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 4/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 5/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 6/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 7/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 8/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° ACORDO: OPTOTAL HOYA LTDA - Parcela 9/24', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '2° VIA BILHETE ÚNICO: Wevilly de Souza Fernandes Líbano > PIX: 453.302.308-88 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '30 ENVELOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3002: FRANCISCA CLEUDE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3013: ROSÂNGELA LEME PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3040: CILENE LOPES SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO 1/3: SABESP - LOJA SUZANO 2 RGI 0046782494', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO 2/3: SABESP - LOJA SUZANO 2 RGI 0046782494', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO 3/3: SABESP - LOJA SUZANO 2 RGI 0046782494', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 1/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 10/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 11/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 12/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 13/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 14/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 15/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 16/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 17/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 18/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 19/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 2/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 20/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 21/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 22/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 23/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 24/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 25/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 26/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 27/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 28/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 29/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 3/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 30/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 31/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 32/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 33/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 34/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 35/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 36/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 37/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 38/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 39/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 4/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 40/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 41/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 42/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 43/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 44/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 45/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 46/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 47/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 48/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 49/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 5/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 50/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 51/81', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), '3° ACORDO: OPTOTAL HOYA LTDA - Parcela 52/81', 'juridica', NULL, True, NOW(), NOW());
