INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'DISSÍDIO: Maria Elizabeth Pereira do Nascimento > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Maria da Conceição Ramos de Moura (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Rogério Aparecido de Morais (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Rogério Aparecido de Morais > PIX: ro.gerio.morais@hotmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Rosangela Aparecida Dejane Felisbino (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Rosangela Aparecida Dejane Felisbino > PIX: 116.378.698-51 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Vanessa Mendes da Silva > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Wevilly de Souza Fernandes Líbano (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Zaine de Lima Siqueira (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Zaine de Lima Siqueira (diferença de salários) - descontar na rescisão indireta, valor depositado a mais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DISSÍDIO: Érika de Oliveira Gomes (diferença de salários)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DIVINO DOUTOR: Clínica São Vito LTDA > PIX: 19.320.052/0001-73 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCERIA AGDA MARTINS ANDRADE: Pão francês > Kayllaine Pereira Alves de Araújo > PIX: 426.663.838-81 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCERIA AGDA MARTINS ANDRADE: Pão francês > PIX: 296.874.578-64 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - AVCB - NATANEL BRUNETTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - CARTORIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - CARTÓRIO: PROTESTO TM', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - CARTÓRIO: REGISTRO E RECONHECIMENTO DE FIRMA - PROCURAÇÃO (TMO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - CREA-SP (VISTORIA AVCB)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - DARE-SP (VISTORIA AVCB)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - LIVRO ÓPTICO: VIVIAN MARIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - MUNICÍPIO DE MAUÁ: TAXA VIGILÂNCIA SANITÁRIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - PORTO SEGURO CAPITALIZAÇÃO S/A', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOCUMENTAÇÃO EMPRESA - PREFEITURA MUNICÍPIO DE MAUÁ: TAXA REFERENTE A RÚBRICA DE LIVROS DE 200 FOLHAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DOUGLAS SANTOS: BATIDA DO CARRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DROG SAO PAULO FL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DROGARIAS BIFARMA 16', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DROGASIL 2290', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DROGASIL 2291', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DSAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DSAO > PIX: 52.135.712/0005-45 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DSAO > PIX: 52.135.712/0005-45 (CNPJ) > Parcela 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DSAO > PIX: 52.135.712/0005-45 (CNPJ) > Parcela 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DUPARI COMERCIAL EIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DUPARI COMERCIAL EIRELI: ENVELOPE, PASTA OF E PASTA SANFONADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DUPARI COMERCIAL EIRELI: SUPER SACO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DannyRô Doces', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Depósito Online 7827-28-SOP-BARUERI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Depósito bancário', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Depósito em Dinheiro- TEC DEPOSITO DINHEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Descartáveis festas 16 e', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Descobrir esta diferença de valores', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Devolução de PIx, pago em duplicidade: Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença - FRANQUIA > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença das taxas dos cartões', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença de VT : Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença de VT : Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença de VT : Rogério Aparecido de Morais', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença de VT : Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Diferença de VT: Aline da Cruz dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Dinheiro em caixa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Dinheiro em caixa (antiga gestão)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Dinheiro em caixa (escritório - Thiago Yuri)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Dinheiro em caixa - by: loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Dinheiro em caixac', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Dinheiro em ciaxa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Doces festa 18/12 - Bárbara', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Doces festa Bárbara - 18/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Doces para festa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Doces para os personalizados Nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Débito de cessão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Débito à vista - Taxas Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'E.S.A BOOMBAS: Limpeza e higienização de reservatório de água limpa e dedetização de áreas comuns', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EBCT: TABLET´S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ECOPISTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTE 0089498160 - LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTE 0089498160 - SUZANO MATRIZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2 (ref. abr/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2 (ref. dez/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2 (ref. fev/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2 (ref. jan/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2 (ref. mar/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0033609799 - LOJA SUZANO 2 (ref. nov/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0150111320 - ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0150111320 - ESCRITÓRIO (BANCO NUBANK - Giovanna)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDP BANDEIRANTES 0150111320 - ESCRITÓRIO (ref. 12/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDSON CANTISANI OTICA (ÓTICAS DINIZ): Estojo lente de contato', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EDUARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EFETIVA PREMIUM CERTIFICADO DIGITAL LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ELETR HIDRAUL SUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ELETRICA PARA ESCRITÓRIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ELETRO HIDRAULIC SUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ELETRO HIDRAULICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ELETRO HIDRAULICA LTDA: Compra de mercadoria para manutenção do escritorio', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ELETRO HIDRAULICA SUZANO LTDA: Disjuntor (escritório)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EMBALATUDO: Aplique e máscaras de carnaval (Decoração para loja)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EMBALATUDO: Papel sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EMISSÃO DE DOC - LIDIOMAR CARC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EMPREENDIMENTOS PAGUE MENOS S.A FARMÁCIAS PAGUE MENOS: ESMALTE CHOICES BEAUT INCOLOR 10ML', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EMPÓRIO DO REAL: Água sanitária, desinfetante e filtro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 0049320513 - LOJA RIO PEQUENO > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 0049320513 - LOJA RIO PEQUENO PIX) Roberto - 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 110059964 - PESSOAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 110059964 - PESSOAL GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 200396315- LOJA RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 200396315- LOJA RIO PEQUENO (ref. dez/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 200396315- LOJA RIO PEQUENO (ref. mar/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 202819444 - LOJA SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 202819444 - LOJA SÃO MATEUS (ref. out/2022)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 203698123 - LOJA PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 25642171 - LOJA MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 27362119 - LOJA PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 69186502 - PESSOAL TATIANA MELLO DE CAMARGO (ref. DEZ/2020)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 69186502 - PESSOAL TATIANA MELLO DE CAMARGO (ref. NOV/2020)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 69186502 - PESSOAL TATIANA MELLO DE CAMARGO (ref. OUT/2020)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENEL 69186502 - PESSOAL TATIANA MELLO DE CAMARGO (ref. SET/2020)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENGRAXE - PORTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENGRAXE - PORTA (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 1/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 1/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 10/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 11/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 2/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 2/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 3/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 3/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 4/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 4/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 5/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 5/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 6/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 6/11 - 2° parte', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 6/6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 7/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 8/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA DE COMPRA: Compra da loja - Óticas Taty Mello: Parcela 9/11', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA: PASSWORD INTERATIVA BI E SOFTWARE - VIXEN > PIX: 15.495.166/0001-01 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTRADA: VIXEN - SISTEMA LJ RIO PEQUENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGA: Erick Araújo (motoboy - ref. 01-11)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGA: Erick Araújo (motoboy - ref. 05-11)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGA: Erick Araújo (motoboy - ref. 08-11)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGAS - 5979: MAGNÓLIA APARECIDA BRAGUEROLI DELARA - ENVIO DE SERVIÇO VIA CORREIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGAS - ENTREGA DO ÓCULOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGAS - ENTREGA MOTOBOY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGAS - ENVIO DO ÓCULOS P/CLIENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGAS - PAGAMENTO DA ENTREGA DA ARMAÇÃO ATITUDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENTREGAS - UBER: WEVILLY DE SOUZA LÍBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ENVELOPES PARA CERTIFICADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EQUIPAMENTOS: Thiago Yuri da Silva Yuki > ref. televisão/raspeberry (RIO PEQUENO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EQUIPAMENTOS: Thiago Yuri da Silva Yuki > ref. televisão/raspeberry - Parcela 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EQUIPAMENTOS: Thiago Yuri da Silva Yuki > ref. televisão/raspeberry - Parcela 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESKALA 318', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESPEED IMPORTAÇÃO E EXPORTAÇÃO EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESPEED IMPORTAÇÃO E EXPORTAÇÃO EIRELI - PIX: 305760130001/74', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTAB N002614051080000', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTACIONAMENTO PARA COMPRA DE ARMAÇÕES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO BOMBOM: Maria Elizabeth Pereira do Nascimento - PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE (troco) - Iracelo Alves Feitosa (MAUÁ) > PIX: 265.951.008-35 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE (troco) - Jesilene Silvia Soares (PERUS) > PIX: 188.702.908-75 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE (troco) - Joyce Nailê da Silva Serra (SUZANO) PIx: 11937294471', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE (troco) - Nair Aparecida de Souza Ramos (MAUÁ) > PIX: souzanair853@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE (troco) - parc. 6/6: Janet Dias Santos (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE - parc. 1/5: Aparecida Gonzaga Souza > PIX: (11) 9 9787-1463 (celular) I Banco: Santander I Agência: 3809 I Conta: 01099337-6 > Cancelamento da OS: 7856 - Jenifer Gonzaga ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE - parc. 2/5: Aparecida Gonzaga Souza > PIX: (11) 9 9787-1463 (celular) I Banco: Santander I Agência: 3809 I Conta: 01099337-6 > Cancelamento da OS: 7856 - Jenifer Gonzaga ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE - parc. 3/5: Aparecida Gonzaga Souza > PIX: (11) 9 9787-1463 (celular) I Banco: Santander I Agência: 3809 I Conta: 01099337-6 > Cancelamento da OS: 7856 - Jenifer Gonzaga ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE - parc. 4/5: Aparecida Gonzaga Souza > PIX: (11) 9 9787-1463 (celular) I Banco: Santander I Agência: 3809 I Conta: 01099337-6 > Cancelamento da OS: 7856 - Jenifer Gonzaga ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE - parc. 5/5: Aparecida Gonzaga Souza > PIX: (11) 9 9787-1463 (celular) I Banco: Santander I Agência: 3809 I Conta: 01099337-6 > Cancelamento da OS: 7856 - Jenifer Gonzaga ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE FRANQUIA: Gilvanilda Ventura dos Santos > Banco: Caixa Econômica I Agência: 0642 I Conta: 000851716806-0 I CPF: 286.129.078-10', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Bruna Beatriz de Paula > PIX: 476.324.988-69 (CPF) > Reembolso: 4714', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Cristian Jacinto Alves > PIX: 087.875.188-21 (CPF) > Cancelamento da OS: 6932 ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Cynhtia Souza Leite dos Santos > Reembolso: 10944, 10945 e 10946 (AUT: 690326 I Dígitos do cartão: 3258)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Edilene Santos Mangueira > PIX: 686.703.464-00 (CPF) > Erro de cobrança de carnê', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Ingrid Ramos Correia Cruz > PIX: 429.024.038-01 (CPF) > Cancelamento da OS: 8877 & 9155', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Junior Pinheiro de Souza', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Leonardo de Lima Marques > PIX: (11) 9 8405-6594 (celular) > Reembolso: 4820', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Maria Cecília P. de Moraes > PIX: 088.679.748-90 (CPF) > Reembolso: 3823 (AUT: 290902 I Dígitos do cartão: 7641)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Maria Claudia Reis Chehbi > PIX: 324.794.628-46 (CPF) > Cancelamento da OS: 801 ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Maria Nazareth de Oliveira > PIX: (11) 9 6203-9096 (celular) > Cancelamento da OS: 8015 ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Maria Nazareth de Oliveira > PIX: (11) 9 6203-9096 (celular) > Cancelamento da OS: 8226 ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Marli Ferreira Franco > PIX: (11) 9 7729-2751(celular - Waldir Rodrigues Bio) > Cancelamento da OS: 943', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Neimar Pereira dos Santos > Reembolso: 10734 (AUT: 842590 I Dígitos do cartão: 9221)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Simone Ramos Britto Silva > PIX: (11) 9 9834-3733 (celular) > Cancelamento da OS: 3779 ()', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO CLIENTE: Vanessa Rodrigues Sales > PIX: (11) 9 9474-7136 (celular) > Cancelamento da OS: 396 - Vanessa Rodrigues Sales', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO PARA CLIENTE: Jandira Marques da Silva - OS (confirmar)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO PARA CLIENTE: Rosa do Nascimento Dias de Oliveira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO PIX ENVIADO - WEVILLY DE SOUZA LIBANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: (Jocicreide Macedo Barbosa Santos transferido duas vezes)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: Ariani Dias Fernandes Líbano ( Chocolate Twix)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: Maria Elizabeth Pereira do Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: Nathalia Carolina Cardoso Ribeiro Faustino (ref. às parcelas de set~nov/2023 em aberto)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: Thainá Gabriel Ferreira da Silva', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: Wevilly de Souza Fernandes Líbano (Chocolate Prestígio)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ESTORNO: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'EXPRESS > PIX: 30.576.013/0001-74 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Elisabete balões - pix: 1198426-2567', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Entrega de Serviços as Lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estacionamento - COMPRA CARTAO - NO ESTABELECIMENTO FERNANDO AUGUSTO DE AL SAO PAUL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno - 2173', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno - ASSAÍ ATACADISTA: Alcool, copo descartável (água), copo descartável (café) e papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno - Diferença das taxas dos cartões', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno - IMPOSTOS - TAXA DE FISCALIZAÇÃO DE ESTABELECIMENTO E FISCALIZAÇÃO DE ANÚNCIOS - PARCELA 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno - TAXA DE VENDAS CARTÃO - TAXA DE PARCELAMENTO E DA CIELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno Estorno para cliente (Bruno passou o valor a mais no cartão do cliente)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno de débito - Lojas Renner Fl', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estorno para cliente (Bruno passou o valor a mais no cartão do cliente)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Estrela para cadeira giratória - Reginaldo Donizete', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F D I BAZAR LTDA ME (Café especial para o dia das mães, ref. 13/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F D I BAZAR LTDA ME: Biscoitos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F D I BAZAR LTDA ME: COLHER PARA CAFÉ', 'juridica', NULL, True, NOW(), NOW());
