INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - RODOANEL OSASCO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - ROSENI CERQUEIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SANTA HELENA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SUMUP SOL PAGAM ANTECIPAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SUMUP SOL PAGAMENT DÉBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SUMUP SOL PAGAMENT DЙBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SUMUP SOL PAGAMENT DЩBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SUMUP SOL PAGAMENT DיBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - SUMUP SOL PAGAMENT DษBITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - T. M C V O S U LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TAR DOC/TED ELETRิNICO - COBRANวA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TAR PACOTE ITAU DEZ 22', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TARIFA ADIANT DEPOSITANTECOBR PARC REF A', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TARIFA ADIANT DEPOSITANTECOBRANЗA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TARIFA CAP GIRO DIGITAL - COBRANวA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TARIFA PACOTE DE SERVIЗOSCOBRANЗA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TARIFA PACOTE DE SERVIวOS - COBRANวA REFERENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TARIFA PIX ENVIADO - TAR. AGRUPADAS - OCORRENCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TED 237 7750PAULO CESAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TED TRANSF.ELETR.DISPONIV - 341 6253 02348108585 JOCICREIDE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TED-CRЙDITO EM CONTA290 0000 48781194000136 GI COMERCIO VA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TED-CRษDITO EM CONTA - 290 0000 48781194000136 GI COMERCIO VA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERENCIA RECEBIDA: 033 207 10418715 GABRIELA FERREIRA CONDINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA ENVIADA - GILBERTO DE CAMARGO SILVA JR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - ADRIANA APARECIDA BRAZ DA SILVA - •••.543.428-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 692462418-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - ALESSANDRA FELIX SILVA - •••.966.388-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 89703751-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - ANA FLÁVIA FERREIRA DE CASTRO SANTOS - •••.360.548-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 43803036-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - BIANCA DE OLIVEIRA SANTOS NUNES - •••.877.601-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 796809132-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - CLEUSA DAMASCENO HELADIO - •••.439.678-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 99611042-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - EDECARLO PAULO DE FREITAS - •••.111.968-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 57123384-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - EDUARDA CINDRA BARBOSA - •••.332.268-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 74955493-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - EZEQUIAS LEONARDO DA SILVA - •••.683.698-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 43131553-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - JAQUELINE APARECIDA DA SILVA MIRANDA - •••.163.478-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 523982118-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - JOSE FERREIRA DA SILVA - •••.940.634-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 96496628-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - JOÃO CARLOS DA SILVA - •••.078.219-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 39057054-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - KAROLINE VITÓRIA DE OLIVEIRA SANTOS - •••.724.708-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 92362219-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - KATIA DE OLIVEIRA - •••.169.778-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 5140197-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - KETTELYN LIMA DOS SANTOS - •••.535.085-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 10153470-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - LAÍS FLORENTINO DA SILVA - •••.917.738-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 77866538-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - LUCIANO BITTENCOURT TEIXEIRA - •••.160.838-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 344629592-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - LUÍS FERNANDO XAVIER CARRARA - •••.443.436-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 521580815-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - MARCELA DA COSTA SIQUEIRA - •••.877.558-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 29392889-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - MARCIA REGINA TEIXEIRA - •••.226.178-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 21335839-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - MARIA EDUARDA CAMPOS KIELMANN - •••.305.458-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 49144375-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - MIRIAN MAYARA DE SOUZA SILVA - •••.683.098-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 90775611-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - NATALI DOS SANTOS MENEZES - •••.931.538-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 98622952-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - NATALIA SANCHES VIANA - •••.878.659-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 66211951-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - PATRÍCIA PAULINO DOS SANTOS - •••.263.188-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 33376252-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - PAULO HENRIQUE SECCATO - •••.635.188-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 92445755-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - RICARDO VIEIRA DA SILVA - •••.132.908-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 37827725-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - RITA DE CASSIA CARDOSO LANDIM - •••.451.048-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 42189703-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - RODOLFO HENRIQUE CLAUSING FERREIRA - •••.689.378-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 8228537-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - RONIELIA DA SILVA - •••.575.418-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 29014069-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - SABRINA CARMO DE MEDEIROS - •••.426.618-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 27040288-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - SANDRA FERNANDES - •••.230.248-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 35623181-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - SANDRA MARIA MALTA - •••.518.858-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 86479306-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - SEVERINA TRAJANO FERREIRA - •••.337.658-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 29411058-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - SIDILAINE APARECIDA DE PAULA - •••.137.438-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 97096473-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - SIRLEI BUENO BORGES - •••.135.428-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 37597558-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - TALITA DANIELLE MACHADO PEREIRA - •••.880.698-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 900243-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - TALITA DE FREITAS GOMES - •••.445.558-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 27487325-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - TATIANA MELLO DE CAMARGO - •••.876.768-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 84487388-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - TIAGO JORGE DOS SANTOS - •••.610.878-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 709165570-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - ULISSES ROBERTO DOS SANTOS - •••.964.158-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 452857594-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA - VALÉRIA MARTINS DE OLIVEIRA BRAGA - •••.311.068-•• - NU PAGAMENTOS - IP (0260) AGÊNCIA: 1 CONTA: 69724004-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ADRIANA APARECIDA BRAZ DA SILVA - •••.543.428-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 2871 CONTA: 756018613-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ADRIANO DA SILVA CHAIME - •••.925.338-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 7526 CONTA: 278437-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ADRIANO MARINO - •••.667.808-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 100 CONTA: 408309-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - AGATHA SABRINA SIQUEIRA DA CUNHA - •••.321.498-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 2028718-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ALEX DA COSTA SILVA - •••.335.918-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 350 CONTA: 1057783-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ALEXIA A O SAUL - •••.684.878-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 6710 CONTA: 43311-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ALEXIA VITORIA DA SILVA APPARECIDO - •••.132.128-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 32384888-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ALUIZIO NOGUEIRA PESSANHA JUNIOR - •••.720.038-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 1083095-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ALUIZIO NOGUEIRA PESSANHA JUNIOR - •••.720.038-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 2871 CONTA: 592212666-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ANA FLAVIA FERREIRA DE CASTRO SANTOS - •••.360.548-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 1184292469-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ANA LUCIA CUSTODIO DA SILVA - •••.706.004-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 6253 CONTA: 78079-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ANDERSON SILVA FREITAS ALVES - •••.150.518-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 759 CONTA: 42247-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ANDREA MOSCA CINTRA - •••.279.408-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 17938929-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ARI JOSE DOS REIS - •••.514.718-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 557 CONTA: 388456-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - AUCLECIR ANTONIO DE SOUSA OLIVEIRA - •••.696.668-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 908 CONTA: 759279315-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - AUZILENE LIMA PEREIRA - •••.470.288-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 2017741-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - BRUNA DOS SANTOS NUNES - •••.547.348-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 9605 CONTA: 3638-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - CARLA C G VALDO - •••.666.248-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 6710 CONTA: 107523-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - CARLOS MONTEIRO FILHO - •••.276.868-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 3005 CONTA: 752184081-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - CLAUDIA EUNICE PURGATO DA SILVA - •••.202.788-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 14320902-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - DEBORA BRAGA MOLINARI - •••.609.568-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 642 CONTA: 577005786-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - DEBORA LIMA MAGALHAES - •••.072.938-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 100 CONTA: 623630-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - DIEGO SILVA VIANA - •••.261.498-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 718 CONTA: 123245-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - DIEGO SILVA VIANA - •••.261.498-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 4912971306-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - DIRCE GABRIELLE RIBEIRO SILLOS - •••.517.218-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 197 CONTA: 1092807-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - DYENIFER NICOLE BRANDÃO DA ROCHA - •••.320.588-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 122214034-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - EDILSON CASTILHO TAVARES - •••.131.878-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 7428 CONTA: 34346-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - EDILSON DA CONCEICAO DELGADO - •••.257.378-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 3357 CONTA: 753348318-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - EDSON ALVES DE OLIVEIRA - •••.073.328-•• - PAGSEGURO INTERNET IP S.A. (0290) AGÊNCIA: 1 CONTA: 2028683-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ELEN PEREIRA ARAUJO DE MOURA - •••.082.628-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 6253 CONTA: 87301-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ELIANA APARECIDA FARIAS DOS SANTOS - •••.257.528-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 112657413-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ELIANE ODILIA DA CRUZ - •••.379.738-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 2871 CONTA: 752244456-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ELIZA DE PAES - •••.252.678-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 100 CONTA: 265261-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ELIZANDRA DIAS FERREIRA MONTEIRO - •••.208.878-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 67540312-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - EMANUEL DELLANGELICA COSTA - •••.811.308-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 30941978-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ENALDA PEREIRA DE ARAUJO - •••.952.358-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 8573 CONTA: 26166-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - FERNANDA LEANDRO CAMPOS - •••.675.008-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 718 CONTA: 87319-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - GABRIEL HENRIQUE TAVARES ADAIR - •••.185.998-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 2031220-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - GENI CARLOS RANGEL - •••.369.647-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 3146 CONTA: 14376-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - GILMAR LOPES MARINHO - •••.684.088-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 2812208-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - GILSON TELES GOMES - •••.446.298-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 6453 CONTA: 12332-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - GIOVANNA SOUZA - •••.462.278-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 6882 CONTA: 82564-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - GRAZIELA SOUZA BRITO - •••.632.488-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 642 CONTA: 851357721-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - IRIS ROCHA SANTOS DAS NEVES - •••.403.085-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 8657926164-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - J.C.A CONSTRUCOES LTDA - ME - 19.050.964/0001-72 - BCO BRADESCO S.A. (0237) AGÊNCIA: 1711 CONTA: 36417-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JANAINA APARECIDA DE OLIVEIRA - •••.970.628-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 197 CONTA: 1094264-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JANE PEREIRA ANGELO - •••.984.228-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 642 CONTA: 758447285-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JAYNE DE SOUSA ALVES - •••.635.368-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 2011786-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JEANE CRISTINA SANTOS LIMA - •••.400.898-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 8072949229-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JEOVANAH MYLENA PESSOA CORREA - •••.708.538-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 14044878-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JESSICA MARIA DOS SANTOS - •••.831.348-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 1039 CONTA: 2556-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JOICE APARECIDA DA SILVA MIRANDA - •••.652.918-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 928 CONTA: 849164377-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JOICE RABELO DAMA - •••.153.168-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 3880 CONTA: 944909588-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - JOSICLEIA DE JESUS DOS ANJOS - •••.398.828-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 2022038-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - KARINA LIMA SANTOS - •••.997.908-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 6351727674-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - KATIA DE OLIVEIRA MOURA - •••.169.778-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 7160 CONTA: 656551-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - KAUE DE PAES SIMPLICIO - •••.326.058-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 1198588928-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - KETTELYN ARAUJO DE OLIVEIRA DA - •••.229.278-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 6253 CONTA: 69194-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LARISSA RANIELLE RIBEIRO DE BARROS - •••.910.938-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 17866630-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LAURA DIAS FERNANDES CARDOZO - •••.812.998-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3620 CONTA: 2023557-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LEANDRO LOPES - •••.270.798-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 7423 CONTA: 19154-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LEIDIANA ALVES CAVALCANTE - •••.207.978-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 3925 CONTA: 595666-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LEONILDA SIQUEIRA DA SILVA - •••.015.299-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 36191127-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LETICIA GHIORZI BRANDAO - •••.418.546-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 9395 CONTA: 3898-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LONDES LINS DA SILVA - •••.184.378-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 7829 CONTA: 14760-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LUCIANA BARBARA ROCHA JESUS - •••.182.358-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 6253 CONTA: 66227-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LUCIANE FARIA DE ALMEIDA - •••.066.908-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 17314847-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LUCIANO BITTENCOURT TEIXEIRA - •••.160.838-•• - 99PAY IP S.A. AGÊNCIA: 1 CONTA: 13602640-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - LUIZ RAPHAEL FAVERO DE SOUZA - •••.114.748-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 42230578-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARCELO NUNES DA COSTA - •••.530.218-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 1480 CONTA: 72636-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARCIA DE ALCANTARA BODO PIRES - •••.413.876-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 1365 CONTA: 30559-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARCIA OLIVEIRA FIGUEREDO - •••.565.398-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 100 CONTA: 751763-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARCIA TAKIUTI MIURA - •••.409.048-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 7428 CONTA: 50055-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARCIO ANTONIO DE SOUZA - •••.134.188-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 7482 CONTA: 16487-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARCOS ANTONIO DO NASCIMENTO - •••.132.938-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 4562 CONTA: 1093372-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARIA CLAUDIA DA SILVA SALES - •••.862.348-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 3210 CONTA: 754019457-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARIA JOSE SOUZA DE OLIVEIRA - •••.422.188-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 100 CONTA: 410340-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARIA MESSIAS B DOS SANTOS - •••.947.068-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 6253 CONTA: 6242-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARILENE AGOSTINHO M OLIVEIRA - •••.267.698-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 239 CONTA: 36664-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MARILU CANDIDA JACOB PEREIRA - •••.852.118-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 93546424-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MAURA ALICE FREITAS - •••.741.918-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 407 CONTA: 53796-9', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MAURO ROBERTO AMARO DE MELLO - •••.102.648-•• - BCO SANTANDER (BRASIL) S.A. (0033) AGÊNCIA: 3970 CONTA: 1000835-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MICHAEL BRUNO FELIPE R SILVA - •••.897.948-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 2847 CONTA: 34334-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - MICHELE PAIXAO DOS SANTOS - •••.560.068-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 17526611-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - NATALIA FERNANDES DA COSTA FUDUGLI - •••.456.428-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 100896268-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - NELSON ANISIO SOARES - •••.692.994-•• - BCO MERCANTIL DO BRASIL S.A. (0389) AGÊNCIA: 166 CONTA: 1061778-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - PALOMA DOMINIQUE FERNANDES DOS SANTOS - •••.712.888-•• - PAGSEGURO INTERNET IP S.A. (0290) AGÊNCIA: 1 CONTA: 39033767-3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - PAULO FELIPE ANDRADE SIQUEIRA - •••.488.718-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 5030343848-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - PAULO VICTOR VAZ DA SILVA - •••.801.618-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 25446681-8', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - RAISSA MILENA SIQUEIRA DA SILVA - •••.581.258-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 13235052-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - RENAN LOURENCO SILVA - •••.018.188-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 3005 CONTA: 583402932-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ROGERIO FAUSTINO DA SILVA - •••.036.938-•• - BCO BRADESCO S.A. (0237) AGÊNCIA: 3929 CONTA: 207425-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ROSANE Q DA SILVA - •••.950.468-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 6710 CONTA: 901495-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ROSENIR RODRIGUES DA SILVA - •••.074.578-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 642 CONTA: 848647609-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ROSILENE BUENO FERNANDES - •••.951.228-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 6710 CONTA: 47008-2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ROSILENE BUENO FERNANDES - •••.951.228-•• - PICPAY (0380) AGÊNCIA: 1 CONTA: 14603886-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - ROSINEIDE DA SILVA FREITAS - •••.407.808-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 6175206707-7', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - RUBIA VALERIA BATISTA - •••.767.798-•• - MERCADO PAGO IP LTDA. (0323) AGÊNCIA: 1 CONTA: 5288023082-6', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - SANDRA MARIA MALTA - •••.518.858-•• - BCO DO BRASIL S.A. (0001) AGÊNCIA: 6710 CONTA: 48889-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - SIMONE QUIRINO DOS SANTOS - •••.068.418-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 2847 CONTA: 52740-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - SONIA APARECIDA SANTOS BATISTA - •••.486.788-•• - CAIXA ECONOMICA FEDERAL (0104) AGÊNCIA: 642 CONTA: 758448863-4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - STEPHANINI LOPES DA SILVA - •••.094.268-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 7968 CONTA: 21716-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - VERONICE UMBELINA DOS ANJOS - •••.821.355-•• - NEON PAGAMENTOS S.A. IP (0536) AGÊNCIA: 655 CONTA: 19733685-0', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - VITORIA NHOQUE JACINTO - •••.762.408-•• - BANCO INTER (0077) AGÊNCIA: 1 CONTA: 33756999-1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - TRANSFERÊNCIA RECEBIDA PELO PIX - VITORIA NHOQUE JACINTO - •••.762.408-•• - ITAÚ UNIBANCO S.A. (0341) AGÊNCIA: 142 CONTA: 65994-5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL CREDITO AMEX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL CREDITO ELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL CREDITO MASTERCARD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL CREDITO VISA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL DEBITO ELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL DEBITO MASTERCARD', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL DEBITO VISA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - DISPONIVEL PIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - VENDAS - PLANO DE RECEBIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - lanche nicolly', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - mercado livre', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - salgados kamix', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação -almoço erenito', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação -salgados tati', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Confirmar o PIX!!!! SALÁRIO: Geovana Silva Novaes (ref. 5 dias trabalhados em Perus - 18/08, 19/08, 21/08, 26/08 e ) > PIX: 575.129.258-01 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conserto de porta de Mauá - 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Consertos das cadeiras giratórias do escritório/lojas - Reginaldo Donizete > PIX: (11) 9 7684-1836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Consulta para a cliente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Corrediça Telescópica P/ Gaveta Reforçada 45cm 4 Pares 45 Kg 1 unidade - para o Suzano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Crédito parcelado - Recebimento Venda - Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Crédito parcelado - Taxas Venda - Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Crédito parcelado loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Crédito à vista - Recebimento Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Crédito à vista - Taxas Cielo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'CÓPIA DE CHAVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Cópias da chave do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'D D PARK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAMSP - Documento de Arrecadação do Município de São Paulo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DAMSP - Documento de Arrecadação do Município de São Paulo (ref. 06/2025)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'DARF (Contribuição da Previdência - 1082)', 'juridica', NULL, True, NOW(), NOW());
