INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'ASSADOS & CIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSADOS VILA FIGUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAI ATACADISTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAI ATACADISTA: Itens para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Alcool, copo descartável (água), copo descartável (café) e papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Compra de itens para a loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Compra de utensílios para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Itens para as lojas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Itens para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Itens para loja > PIX: 4541adc2-aa91-42c3-9d7f-1bc5112d5e89 (chave aleatória) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Itens para loja > PIX: 517.291.608-32 (CPF) - Giovanna Mello de Camargo > NUBANK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ASSAÍ ATACADISTA: Itens para o escritório (reunião de alinhamento)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ATACADAO 048 AS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ATACADAO 054 AS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ATACADO ESPERANCA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AV JACU PESSEGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AWZ COMERCIO DE ALIMENTOS EIRELE: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AYOAGI COMÉRCIO DE MATERIAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AZELOPES MONTAGENS OPTICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Abertura da loja (chave quebrou)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Acerto Dispensa: Miriam Ferreira Sanches', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Acerto Dispensa: Stefany Rayne Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Adiantamento VALE TRANSPORTE: Luana', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Adiantamento para Cleberson', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Adiantamento: Samuel Henrique da Silva (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Almoço - 22/12 14:22 LOJA DE CONVENIENCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Almoço - COMPRA CARTAO - NO ESTABELECIMENTO LANCHONETE E RESTAURA MAUA BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Almoço - COMPRA CARTAO - NO ESTABELECIMENTO PADARIA DAS MARIAS SAO PAULO BR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Almoço Taty - QR CODE PIX ENVIADO - IFOOD.COM AGENCIA DE RESTAURANTES ONLINE S.A.', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Almoço taty e giovanna', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Aluguel de máquina', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Aluguel de pos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Amauri Toalhas - festa nautika', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Ana Fabrícia - pix: 11943322847', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Ariane - pix: felicianoariane12@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Arielli - pix: arielliarruda007@gmail.com', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Artigos para festas 16 e 18/12', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Assaí - COMPRA CARTAO - NO ESTABELECIMENTO ASSAI ATACADISTA SUZANO BRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'AÇOUGUE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B K DUQUE BANDEIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: Parcela 4/4 > PIX: 42.969.995/0001-43 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: QUALIPACK - PARCELA 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: QUALIPACK - PARCELA 1/3 - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: QUALIPACK - PARCELA 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: QUALIPACK - PARCELA 1/4 - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'B S C INDUSTRIA E COMERCIO DE ESTOJOS LTDA: QUALIPACK - PARCELA 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BAFFS PERUS: Pão de queijo (Café especial para o dia das mães, ref. 13/05)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BALÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BALÃO DE CORAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BALÃO MÁGICO: Acessórios para a decoração do carnaval > Maria Elizabeth > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BALÃO MÁGICO: Copo descartável', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BALÃO MÁGICO: GUARDANAPO E VELA GLITTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BALÕES: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BATIDA DO CARRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BAZAR KO FUKO LTDA: Bexiga', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BAZAR KOFUKO LTDA: Bexigas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BAZAR KOFUKU LTDA: Bexiga', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BB Rende Fácil', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BELINHA BABY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BELLEU DEPOSITO DE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BERGAMINI CONSTRUÇÃO EIRELI-ME: Broca aço rápido 1,5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BERGAMINI CONSTRUÇÃO EIRELI-ME: Cimento e tijolo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BERGAMINI CONSTRUÇÃO EIRELI-ME: Cotovelo LL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BERGAMINI CONSTRUÇÃO EIRELI-ME: Fita veda rosca e tubo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BERGAMINI CONSTRUÇÃO: Cimento e gesso', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BETEL7 MATERIAL DE CONSTRUÇÃO LTDA: Arame', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BG LESTE ALIMENTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIANCO MATERIAIS PARA CONSTRUÇÃO EIRELI: Durepoxi', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIG BOB E BIG BOB COMBO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIG KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIG MAC', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIG MAC: BIG KING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIOCLINIC CLINICA E', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BIZON SALGADOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLANCO MATERIAIS DE CONSTRUÇÃO EIRELI: Joelho, luva, tubo pvc, gesso, areia e adesivo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLOCO DE RECIBO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLUE OPTICAL - GOLD OPTICAL COMERCIO LTDA > PIX: 42.132.573/0001-19 (CNPJ) - ref. OS 11076', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLUE OPTICAL - GOLD OPTICAL COMERCIO LTDA > PIX: 42.132.573/0001-19 (CNPJ) - ref. OS 11527', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLUE OPTICAL - GOLD OPTICAL COMERCIO LTDA > PIX: 42.132.573/0001-19 (CNPJ) - ref. OS 11527 (diferença de valor)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLUE OPTICAL - GOLD OPTICAL COMERCIO LTDA > PIX: 42.132.573/0001-19 (CNPJ) - ref. OS 11528', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BLUE OPTICAL - GOLD OPTICAL COMERCIO LTDA > PIX: 42.132.573/0001-19 (CNPJ) - ref. OS 11528 (diferença de valor)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BMP UTILIDADES DOMESTICAS S. A.: Pilha zinco AA e pilha zinco carvão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BOBINA TERMICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BOBINAS TERMICAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BOLD BIJU: Lixa', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BOLO FERRERO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BOM PALADAR: Almoço equipe', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BOMBOM AMOR CARIOCA (Brinde dia do cliente) PIX: 116.378.698-51 (CPF) Rosangela', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONGOSTO HORTIFRUTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO POR ALVO ALCANÇADO: Érika de Oliveira Gomes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Aline da Cruz Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Ariani Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Emerson William da Silva Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Jocicreide Macedo Barbosa Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Larissa Dias Fernandes Cardozo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Maria Elizabeth Pereira Nascimento', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Mirian Ferreira Sanches', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Yasmin dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO ref. 08/12 a 10/12: Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Aline da Cruz Santos (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Ariani Dias Fernandes Líbano (ref. ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Ariani Dias Fernandes Líbano (ref. 05/07 - ) > PIX: (11) 9 8018-0836 (celular) ~ (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Bruno Henrique Simão (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Diego Francisco dos Santos', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Eliana Savoia (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Eveline Gianetti Ribeiro', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Francisca Lindineis Nascimento de Souza (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Gislania de Oliveira Silva (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Jocicreide Macedo Barbosa Santos (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Jocicreide Macedo Barbosa Santos (ref. ) > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Jocicreide Macedo Barbosa Santos (ref. 05/07 - ) > PIX: (11) 9 8018-0836 (celular) ~ (PERUS)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Lara Silva Wingeter de Souza (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Larissa Dias Fernandes Cardozo (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Larissa Dias Fernandes Cardozo (ref. ) > PIX: larissadiss766@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Maria Elizabeth Pereira do Nascimento (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Maria Elizabeth Pereira do Nascimento (ref. ) > PIX: 542.980.671-49 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Maria Elizabeth Pereira do Nascimento (ref. 23/01-28/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Nicolly Mello (ref. ida para a casa dos avós > )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Rogério Aparecido de Morais (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Vanessa Santana Ribeiro (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Wevilly de Souza Líbano (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Yasmin dos Santos (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Yasmin dos Santos (ref. 23/01-28/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO: Zaine de Lima Siqueira (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BONIFICAÇÃO:TATY', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BR FARMÁCIA LTDA: Adoçante', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRAGA LUBRIFICANTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASALAB PRODUTOS OTICOS EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 00-11370', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11487', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11488', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11488 (diferença - Aplicação de AR)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11488 (diferença de montagem)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11494', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11499', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11507', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11513', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11523', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11529', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11536', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11536 (diferença p/ rebaixameto de borda)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11539', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11540', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11542', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11543', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11548 (11340 - diferença tratamento transitions)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11554', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11556', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11557', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11580', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11592', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11593', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11605', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11607', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11612', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11615', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11617', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11622', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11632', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11633', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11638', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11647', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11662', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11663', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11665', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11670', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11681', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11685', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11686', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11691', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11695', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11705', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11706', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11711', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11712', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11716', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11719', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11720', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11723', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11725 (diferença - Aplicação de AR)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11734', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11735', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11742', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11768', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11776', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11795', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11799', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11804', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11805', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11806', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11820', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11834', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11852', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'BRASCOR - EDUARDO SUENAGA > PIX: (11) 9 3047-3110 (celular) - ref. OS 11853', 'juridica', NULL, True, NOW(), NOW());
