INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOCICREIDE MACEDO BARBOSA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JODENILSON SANTOS SAMPAIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOICE RABELO DAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JORGE ALVES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JORGE AMANCIO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOSE BELO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOSE CARLOS DE FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOSE LOURENCO FINCO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOSEFA GOMES DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOSÉ RICARDO CEZAR JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOZELI SILVA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JOÃO PEDRO PAIVA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JULIANA DE OLIVEIRA A LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JULIO CESAR JARDIM DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JUSSARA CARVALHO F JANUARIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - JUSTINO MASCARENHAS OLIVEIRA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - KAIO GABRIEL BARBOSA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - KAUE VICTOR FOURNIER VICENTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LARISSA DIAS FERNANDES CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LARISSA MARIA SILVA CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LARISSA MOURA NEPOMUCENO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LARISSA SEGURA DE SOUSA BRAGA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LAURA DIAS FERNANDES CARDOZO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LAURO MARQUES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LEANDRO VATEZECK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LEONILDA MARTINS MOREIRA 39910846861', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LETICIA DE OLIVEIRA SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LETÍCIA MARIA DA SILVA RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LILIANE COELHO DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LUANA CRISTINA MARTINS CAMPOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LUIS ROBERTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LUISA BATISTA DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LUIZ BATISTA NETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LUIZ CARLOS DA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - LUIZA DIANA ARRAIS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAGALI MARQUES DE MACEDO MENDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAGNALVA DA SILVA DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAGNO FIGUEIREDO DE BRITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARCO ANTONIO DE ATAIDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARCO ANTONIO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARCOS ANTONIO DA SILVA KOSE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARCOS ROGERIO BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA ARAÚJO COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA CLARA BARROS DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA CLAUDIA REIS CHEHBI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA DE JESUS SOUSA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA DO CARMO LOPES DA SILVA SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA ELIZABETH P NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA ELIZABETH PEREIRA DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA ILDA ARAUJO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA JOSE FRANCISCO DE ANDRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA LUCIA DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA MADALENA DE SA TELES DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIA NEUZA SANTOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARILU CANDIDA JACOB PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARINEIA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARINEIA DE SOUZA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARIO NEZMAH DE MELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARISA DE ARAUJO BATISTA DA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MARY HELLEN AMANCIO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MATEUS TEIXEIRA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAURILIO SANTOS AUGUSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAX APARECIDO ALVES REZENDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAYARA ESTEVES SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAYCON MONTEIRO DE MACEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MAYME SANTOS DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MICHELE FABIAN TORELLI DO NASCIMENTO BEZERRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MIGUEL JESUS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MIGUEL PEZZUOL COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MILEIDE CRISTINA ABADIA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MIRIAN BOMFIM DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MONETI APARECIDA FERREIRA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MONIQUE FERREIRA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MYRELLY APARECIDA DE AZEV', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - MÔNICA MAGALHÃES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NADIR DE JESUS PEREIRA DOS PASSOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NATALIA DI BELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NATHALIA DOS REIS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NEMESIO DE JESUS DURANS JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NEUSA MARIA BELLI PASSARELLI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NICOLAS COUTINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NIVALDA RABELO DAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - NOEL RORIZ DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ODAIR APARECIDO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ORECIO DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - OSVALDO ANJOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - OZENI PEREIRA DA CRUZ SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PABLO RIBEIRO FAUSTINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PALOMA DOMINIQUE FERNANDES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PATRICIA BORGES FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PATRICIA DOS SANTOS VIEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PATRICIA HOMAN LEMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PATRICIA PACIFICO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PAULA ROCHA ABADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PAULO ALEXANDRE DE CERQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PEDRO AUGUSTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PEDRO AUGUSTO CAVALCANTI PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PEDRO BRITO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PEDRO EDUARDO DE ASSIS ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - PEDRO HENRIQUE DE PAULA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - QUEREEN SANTOS DE MELLO SARMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RAFAEL SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RAQUEL FERNANDES LINDOLFO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - REGIANE FELICIANO SIRQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - REGINALDO MAGALHAES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - REINALDO ROMAGNOLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RENAN RODRIGUES PAWLOVSKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RENATA LOPES COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RITA DE CÁSSIA ALVES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROBERT LAHUERTA BARBOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROBERTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROBERTO MORAIS COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RODRIGO BISPO RAMOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROGERIO MARQUES ARANTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RONAILLY LOUREIRO DA PAIXÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RONIELIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSANA GLESIA RODRIGUES LEITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSANA GLESIA RODRIGUES LEITE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSANA MABEL DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSANGELA GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSANGELA MENDES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSANGELA PAIVA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSELY JUSTINIANO ESCALANTE DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROSEMEIRE SILVA DE LIMA DUARTE 292669658', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ROZILEIDE BRITO RIBEIRO DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RUBIA SANTOS DE MORAES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - RUIVALDO CAETANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SABRINA DA SILVA CAMPOS ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SABRINA XAVIER DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SAMUEL DE BARROS RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SANDRA CASAGRANDE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SANDRA CRISTINA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SANDRA GORETTE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SANDRA MARIA PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SEBASTIAO PEREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SERGIO ROBERTO DE SOUZA AGUIAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SHEILA DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SHIRLEI FACUNDE VITURIANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SILENE LEITE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SILVIA MARIA ALVES DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SILVIO GERALDO SILVA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SIMONE IGNACIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SIMONE QUIRINO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SOLANGE SANTOS DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SONAI MARIA DE HOLANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - STEFANY APARECIDA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - STEPHANIE ALVES GOMES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - SUNAMITA R S FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - TALITA DO NASCIMENTO LIMA TOLEDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - TAWANI SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - TAYNARA CRISTINA DOS SANTOS PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THAINARA DE JESUS RIBEIRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THAMIRES RODRIGUES DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THAMIRES SANTOS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THAYMARA CRISTIANE DE MEDEIROS COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THIAGO JOSE MOREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THIAGO YURI DA SILVA YUKI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - THONY GUSTAVE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - TIAGO TEIXEIRA DE MELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - UEIDI DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - UILSON RODRIGUES DE CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - ULISSES ROBERTO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - USACRED', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VAGNER PIRES DE CAMPOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VAGNER RIBEIRO COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VALDIR ALVES DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VALDIVO PEREIRA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VALERIA CRISTINA BUENO DELA TORRE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VALTER DE ALMEIDA PINTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VANESSA GOMES DE SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VANESSA MENDES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VANIA SANTOS ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VANUZA TEIXEIRA SOUSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VERGILIO VERTULLO FILHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VERONICE DOS SANTOS AGUIAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VERÔNICA DA SILVA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VITÓRIA NHOQUE JACINTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VITÓRIA REGINA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VIVIAN DANTAS FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VIVIAN DANTAS SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VIVIANE DE JESUS CARMO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - VIVIANE MARIA ALVES LERIN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WALLACE OLIVEIRA PIRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WELLINGTON FEITOSA DE ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WERMENSON ARAUJO MIRANDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WESLEY DE PAULA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WESLEY DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WILFRED FLERIVAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WILFRID FLERIVAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WILSON APARECIDO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - QR CODE PIX RECEBIDO - WILSON BORGES DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE BILHETE ÚNICO - BILHETE ÚNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE CARTÃO PRÉ-PAGO - MASTERCARD FINAL 6092', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE CELULAR - TIM - (11) *****-1171', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE CELULAR - TIM - (11) *****-2141', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE CELULAR - TIM - (11) *****-3897', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE CELULAR - TIM - (11) *****-5739', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RECARGA DE CELULAR - TIM - (11) *****-9791', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - REND PAGO APLIC AUT MAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - RENDIMENTO DA CONTA - RENDIMENTO LÍQUIDO SOBRE DINHEIRO EM CONTA', 'juridica', NULL, True, NOW(), NOW());
