INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: MORTADELA, PÃO FRANCÊS E REQUEIJÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PALITO DE DENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PANO SACO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PAPEL HIGIÊNICO E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PAPEL HIGIÊNICO E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PAPEL HIGIÊNICO PERSONAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS (REEMBOLSO EMERSON WILLIAM - REF. 19/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS E MARGARINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS E PAPEL HIGIÊNICO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS E REFRIGERANTE KUAT 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS E SACO DE LIXO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: PÃO FRANCÊS, REFRESCO EM PÓ E SAPONÁCEO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRI PEPSI 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE COCA COLA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE COCA COLA 2L ZERO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE DOLLY GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE FANTA 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE FANTA GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE FANTA UVA 2L E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE FRUTUBA GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE KUAT GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE PEPSI 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: REFRIGERANTE SPRITE 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: TEMPERO S. MANA BICARBONATO 80G', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA E DETERGENTE EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA, DESINFETANTE E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA, DESINFETANTE, PEDRA SANITÁRIA E SABÃO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA, DESINFETANTE, PÃO FRANCÊS E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA, MARGARINA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA, MORTADELA, MUSSARELA E PÃO FRANCÊS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - SUPERMERCADO VERAN: ÁGUA SANITÁRIA, PÃO FRANCÊS, PRESUNTO COZIDO E REFRESCO EM PÓ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - TENDA ATACADO AS: INSET AERO RAID BASE ÁGUA BEM. ECO 4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - YOSHIE NEIDE KITANO KIMOTO: AÇÚCAR REFINADO E DESINFETANTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - YOSHIE NEIDE KITANO KIMOTO: DOLLY GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - YOSHIE NEIDE KITANO KIMOTO: GUARANÁ 2L', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - YUUKIBOX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ÁGUA SABORIZADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO - ÁGUA TÔNICA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO CASA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO DO DOCE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO KILOUCURA EIRELI: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO LEVE MAIS E PAGUE MENOS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO LEVE MAIS PAGUE MENOS LTDA: Detergente', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO LEVE MAIS PAGUE MENOS: Pão francês', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO LEVE MAIS PAGUE MENOS: Álcool, biscoito e café', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCADO LIVRE, Lâmpada e tonner', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCEARIA FUKUMARO: Pão francês > Mike Rodrigues Gomes > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MERCEDES DA*MSN REST', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'METERIAL DE CONSTRUÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIKEY PAPELARIA E BAZAR LTDA: Balão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIKEY PAPELARIA E BAZAR LTDA: Bexigas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIKEY PAPELARIA E BAZAR LTDA: Ecolapis 1205, caneta piloto, caneta compactor, sacolar kraft', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIKEY PAPELARIA E BAZAR LTDA: Fitilho', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIMA PERFUMARIA LTDA: Aroma, papel higiênico e saco de lixo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIMA PERFUMARIA LTDA: Chá e papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIMA PERFUMARIA LTDA: Cola super bonder', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIMA PERFUMARIA LTDA: Folha sulfite', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIMA PERFUMARIA LTDA: Papel higiênico', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MINAS DE PRESENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MITIKASU FERRAGENS: Arame', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MITIKASU FERRAGENS: Enforca gato', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIX OPTICAL C. A. OPTICOS EIRELI - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIX OPTICAL C. A. OPTICOS EIRELI - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MIX OPTICAL C. A. OPTICOS EIRELI - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Douglas de Moraes Costa > PIX: 454.179.818-26 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Gabriel Prado > Jocicreide Macedo Barbosa Santos > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Jhonathan Nunes dos Santos > PIX: jhol2019nunes@gmail.com (e-mail) - ref. OS 2040', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: OS''s - ref, 9962', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Pedro Henrique Carvalho Romão > PIX: (11) 9 8297-7830 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Pedro Henrique Carvalho Romão > PIX: (11) 9 8297-7830 (celular) - ref. OS 10435', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Rafael Santos > PIX: rrrig.santos@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: SYGMA LABORATORIO OPTICO LTDA > PIX: 30.576.013/0001-74 (CNPJ - Express) - ref. OS 3779', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGEM: Óticas Vênice (ref. OS 4848) > PIX: 42.041.916/0001-30 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 02 MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 03 MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 09 MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 1 PASSAGEM E 2 SOLDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 1420', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 2 MONTAGENS 1 CONCERTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - 3 MONTAGENS 1 BALGRIFE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - BELLART', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - BELLART 03 MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - BELLART 04 MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - BELLARTE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - DIEGO JESUS GUEDES: MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - GLOBAL PAYMENTS BRASIL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - LABORATÓRIO BLESSING: MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - LUIZ FELIPE: MONTAGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - MONTAGEM LANCASTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - PAGAMENTO PARA ADRIANO JÚNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - PAGAMENTO PARA BRUNO EDUARDO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - PAGAMENTO PARA PAULINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - PAULO COLORAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - SOLUTIONS EYE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - STÚDIO 7: MONTAGEM & CONSERTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - ÓCULOS BACANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - ÓTICA INARÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS - ÓTICAS BELLARTE: CONSERTOS, MONTAGENS OU SOLDAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MONTAGENS: Pedro Henrique Romão', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MOTOBOY: José Roberto (ref. 03/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MOTOBOY: José Roberto (ref. 10/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MOTOBOY: José Roberto (ref. 13/01)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MOTOBOY: José Roberto (ref. 24/02)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MP *BARRACAFEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MP *SUZANART', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MSL AGROPECUARIA DISTRIBUICAO: Confraternização - Gerentes', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MUNDIAL LJ 15', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MUNDIAL VARIEDADES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Manutenção do portão da loja de Suzano: Luiz - PIX ( Celular) (11) 99874-3936', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Manutenção do portão do escretório: Luiz - PIX ( Celular) (11) 99874-3936', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Maria José da Silva > PIX: 11964309450', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Material elétrico para escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Material elétrico para escritório - PIX ENVIADO - CP :18236120-GIOVANNA CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Mercado Livre - PIX ENVIADO - CP :10573521-PIX MARKETPLACE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Meta Anúncios - PIX ENVIADO - CP :25021356-DEMERGE BRASIL FACILITADORA DE PAGAME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Microsoft 365 - Office', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÉDIA LICENÇA MATERNIDADE: Ariani Dias Fernandes Líbano', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - ANA LÚCIA PINHEIRO YOUSSEF', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - ARCASIGN C VISUAL LT ME: LOGO - PARCELA 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CAMPANHA - SAÚDE DOS OLHOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CAMPANHA - SAÚDE DOS OLHOS (REF. VENCIMENTO DO DIA 28/09)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CAMPANHA - SAÚDE DOS OLHOS: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CAMPANHA - SAÚDE VISUAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CAMPANHA PARA ARRECADAÇÃO DE CLIENTES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CAMPANHA: SAÚDE VISUAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - CF - KIWIFY: MARKETING', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - GOOGLE - MEU NEGOCIO - MARCELO ROBERTO P', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - HASTEN MARKETING E PRODUÇÕES: CAMPANHA - SAÚDE DOS OLHOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - HASTEN MARKETING E PRODUÇÕES: CAMPANHA - SAÚDE DOS OLHOS : JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - MARKETING DIGITAL - REDES SOCIAIS: DANIELA E MARIA EDUARDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO DE REDES SOCIAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PABLO DESIGN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA 360 IMPRIMIR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA FACEBOOK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA GOOGLE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA MARCELO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA PABLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA PABLO DESIGN', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA REDES SOCIAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - PAGAMENTO PARA ST FER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - REDES SOCIAIS: LEONARDO SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - REDES SOCIAIS: LEONARDO SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - REDES SOCIAIS: LEONARDO SILVA - REF. 12/2021', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'MÍDIAS SOCIAIS - THE ONE GRÁFICA E MOLDURAS: MARKETING - BANNERS 40X80', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'N M OTSUKA PAPELARIA E PRESENTES LTDA: Durex', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'N W COMERCIO DE EMBALAGENS E DESCARTAVEL: Saco de lixo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAGAMI SUSHI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAGUMO: Desinfetante e filtro de papel', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAGUMO: Itens para a loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAMBU IMOVEIS LTDA - ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAMBU IMOVEIS LTDA - ME (IPTU)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAMBU IMOVEIS LTDA - ME (taxa bancária)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAMBU IMÓVEIS LTDA - ME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NASCIMENTO DISTRIBUIDORA E AVIAMENTOS LT: Compra de armações', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAVARRO LTDA: Compra de solares', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAVARRO LTDA: Saquinhos de solar', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NAZARET CAMILO GAMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NC COMÉRCIO DE EQUIPAMENTOS CONTRA INCÊNDIO LTDA ME EXTINCHAMAS: Parcela 1/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NC COMÉRCIO DE EQUIPAMENTOS CONTRA INCÊNDIO LTDA ME EXTINCHAMAS: Parcela 2/2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NC Extinchamas (troca dos extintores)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'ND SERVICOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NDC AUTOMAÇÃO E ELETRICA: Manutenção em CFTV, troca de câmeras, troca de fontes e mão de obra > PIX: (11) 9 5829-0507 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NECESSAIRE LANCASTER > PIX: 500.404.305-10 (CPF) < 1/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NECESSAIRE LANCASTER > PIX: 500.404.305-10 (CPF) < 2/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NECESSAIRE LANCASTER > PIX: 500.404.305-10 (CPF) < 3/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NECESSAIRE LANCASTER > PIX: 500.404.305-10 (CPF) < 4/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NECESSAIRE LANCASTER > PIX: 500.404.305-10 (CPF) < 5/5', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NETPARK', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NETPARK - ESTACIONAMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NEW LENTES: Compra de lentes de contato (site)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NEW VERSION: Cabo para caixa de som', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NO PRECINHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NO PRECINHO: Bombons (sonho de valsa e ouro branco)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NO PRECINHO: Mortadela', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NO PRECINHO: Pão tradicional', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NOTAS FISCAIS - NOTAS FISCAIS TIRADAS NO CNPJ DA LANCASTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'NOVO MILENIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Nagumo: Coador de café, Papel higiênico e Pão > Nicolas Coutinho > PIX: 490.832.378-00 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Nylon', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OBENTO DO JAPA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OBENTO DO JAPA: Almoço', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OFICIAL DE REGISTRO CIVIL P. N. I. TUTE - procuração Junior TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OFTAMED CLINICA DE OLHOS EIRELI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OFTAMED CLINICA DE OLHOS EIRELI > PIX: 08.687.560/0001-78 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OFTCENTER: Compra de lentes de contato (site)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OGGI SORVETES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OKA DO ACAI SORVETES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OKINAWA MATERIAIS PARA CONSTRUÇÃO: Gesso, selador e tinta - Francisco Hélio Nogueira Arcanjo > PIX: (11) 9 8211-8927 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OKINAWA MATERIAIS PARA CONSTRUÇÃO: Tinta - Francisco Hélio Nogueira Arcanjo > PIX: (11) 9 8211-8927 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPOTAL HOYA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTITEX INDUSTRIA E COMERCIO DE ESTOJOS - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTITEX INDUSTRIA E COMERCIO DE ESTOJOS - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'OPTITEX INDUSTRIA E COMERCIO DE ESTOJOS - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW());
