INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROSANE SOUZA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROSEMEIRE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROSIANE PEREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROSIMEIRE APARECIDA DA SILVA QUINTINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ROSINEIDE FERREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-RUTH PEREIRA BORGES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SABRINA BARBOSA DA ROCHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SAMANTA ROSA CANDELARIA MENDES ANTONI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SANDRA CRISTINA LEITE SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SARANA DA SILVA PINHEIRO BERTOLLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SELMA MARIA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SILVANO DA CRUZ ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SONIA MARIA PIRES ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-STEFEN VINCE GONÇALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-STEPHANI ALVES FERNANDES DE PAULO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SUELLEN EVELIN DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-SÉRGIO AQUINO RODRIGUES SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-T. M COMERCIO VAREJISTA DE OTICA SOCI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-TAMILES DE ARAUJO BELCHIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-TATIANA MELLO DE CAMARGO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-TAYNARA CRISTINA DOS SANTOS PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-THAIS EDUARDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-THALITA GABRIELLY LOPES MORAIS LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-UBALDO FERREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VALDINEI VIEIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VALÉRIA CRISTINA BARBOZA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VALÉRIA OLIVEIRA PORTELLA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VANDERLEA VIANA CORRÊA TORRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VANESSA BARBOSA DE ANDRADE CAMPOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VANESSA CRISTINA SILVA FEITOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VANESSA CRISTINE CHAGAS DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VINÍCIUS AUGUSTO GOMES DIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VITOR ROCHA DE ALCÂNTARA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-VITÓRIA LIANDRO DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-WELLINGTON BARBOSA DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-WESLEY SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-YASMIM NARDES DE FREITAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-YASMIN DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-YVONETE DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ZAINE DE LIMA SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :18236120-ZENITA CAETANO MARINI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-DANIELLE PEDROSO GRANSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-DOUGLAS IMPERIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-MARIA TEREZINHA ZACARIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-MARIO MIRANDA DOS REIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-MIRIAN MADEIRA DOMINGUES DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-ROSINEIDE BEZERRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :20855875-VIVIANI DOS SANTOS LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-ALEX ALVES ANACLETO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-ANA CLAUDIA SOARES DA SILVA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-ANA CLEIA VIEIRA GONCALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-BARBARA DE SOUZA SCHUMACHER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-BRUNO RAMALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-CAROLINE NETTO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-CLAUDEMIR SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-DAIANA CRISTINA RODRIGUES DE CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-DAVI WILLIAN DE MENDONCA GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-DEBORA LUIZA OLIVEIRA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-DEJAIR BENEDITO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-DIOGO FERREIRA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-EDNA ALBUQUERQUE DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-EMILY BEATRIZ NASCIMENTO RIBEIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-ESTER KAMILLY CORREA TORRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-FABIO REGO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-GEISA APARECIDA VENTURA DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-LUIZ FELIPE DE CASTRO GAIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-LUZILENE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-MARCIO HENRIQUE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-MARCOS VINICIUS LOPES DE SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-MARIA DA CONCEICAO XAVIER DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-MARIA DAS DORES DA SILVA COSTA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-MELQUISEDEQUE MELQUIADES DE LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-MIRIAN MADEIRA DOMINGUES DA CRUZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-PALOMA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-PAMELA SANT ANNA JARDIM BARROS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-REGINALDO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-RENILDA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-RICARDO CONEGO CARLOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-RITA DE CASSIA SOARES SOUZA LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-ROSINEIDE FERREIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-SABRINA EDUARDA TELES PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-SARAH KOSHIYAWA REIS DE SOUZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-SARAH VICTORIA DOS SANTOS GARCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-TATIANE ALVES DOS SANTOS SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :22896431-TATIANE MARQUES DO NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :24313102-JULIANO PATRICK TOPAZIO ANASTACIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :24313102-STEPHANE SOARES LIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :24313102-VIVIANE DE FREITAS NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :30306294-GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-ALINE CLEMENTE SEBASTIAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-ANDREA MARIA NUNES DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-ARIELI CRISTINA DEL GAUDIO DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-BEATRIZ DE LIMA FERRARI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-CARLOS ROBERTO PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-CLAUDICEIA SOARES DAS NEVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-CLEAMADTER REFRIGERAÇÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-CRISTIANE RODRIGUES FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-ELAINE XAVIER DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-FERNANDA PEDREIRA DE FARIAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-GILSON GARCIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-JACKSON BARBOSA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-JOSEMRE SOARES RODRIGUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-JOSILDO MIGUEL ARAUJO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-KINA SHOP', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-LARISSA MOURA MOISES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-LILIAN AKEMI ENDO LOSSASO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-MARCELO ALVES VASQUES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-MARIANA RESENDE DE NOVAIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-RICARDO TAVARES GALVAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-ROSEMEIRE DE SOUZA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-RUTE FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-SANDRA FARIAS DE FREITAS SANTIS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-STEFANY APARECIDA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-THAYNARA NATACHA ALVES DE SALES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :31872495-VALDINÉIA MOLINA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :33264668-GILBERTO DE CAMARGO SILVA JUNIOR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :33264668-NICOLAS COUTINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :35810871-YASMIN VITORYA JESUS NASCIMENTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :36272465-JANET DIAS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :37880206-DENAS REPRESENTACOES LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :37880206-DNA ANIMAL BANHO E TOSA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :47074323-GABRIEL HENRIQUE CAVALCANTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :59285411-LARISSA DE SOUZA ALIBERTI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :59285411-LUCILENE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :59285411-MARIA DAS DORES AUGUSTA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-AIALA MACEDO DA CONCEICAO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ALESSANDRA FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ALESSANDRA GORETE MOURA TORRES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ALEXANDRE CARVALHO QUEIROZ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ALEXSANDRO PEQUENO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ALINE CRISTINA F ANDRADE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ANDREA M N DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ANTONIO BARBOSA GUEDES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ANTONIO CARLOS D P ALBARELLO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ANTONIO DOMINGOS TAVARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ARIANA MONTEIRO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ARTHUR MARQUES NEUTON', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-BENEDITA APARECIDA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-CAMILA RODEIGUES BARBALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-CICERA REJANE S O DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-CLAREONICE FATIMA S PEREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-CLAUDIO KATSUHIRO SAMESIMA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-DAIANE DOS SANTOS FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-DAIANE OLIVEIRA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-DENISE DOS SANTOS OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-DOMENICA L R FELISBINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-EDMUNDO OLIVEIRA MACHADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-EDSON LUIZ DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ELAINE MAXIMIANA DA SILVA CENA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ELAINE XAVIER DE OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ELENILTON DOS SANTOS FRUTEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ELIANE MARIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ELISANGELA COSTA ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-ERICA OLIVEIRA TEIXEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-EURENICE CERQUEIRA M SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-FABIO DA ROCHA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-FABIO GONCALVES MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-FERNANDO AUGUSTO ALMEIDA LOPES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-FERNANDO PINHO DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-FLAVIO RODRIGUES GOMES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-FRANCISCA ROZILANDIA S VIRGENS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-GEOVANA BEATRIZ OLIVEIRA KRIES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-GILBERTO DE CAMARGO SILVA JR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-GILMAR JOSE DE SIQUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-GILVANA PEREIRA SALES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-GRAZIELI ELIZIA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-IEDA PINHEIRO SILVA OLIVEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-IZALTINA JULIA DOS S BARBOZA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JANAINA APARECIDA DE AGUIAR', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JARDEL WERVERTON ALVES SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JOAO VICTOR OLIVEIRA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JONATHAS CATTANIO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JOSE JACKSON BARBOSA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JOYCE CARLA DOS SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JULIANA BATISTA DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-JULIANA SANTOS SOARES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-KETTELYN ARAUJO DE OLIVEIRA DA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-KRYSNA FERREIRA MARTINS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LARISSA MOURA MOISES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LARISSE MARIA O MACHADO CUNTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LETICIA FREITAS PACHECO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LETICIA VIANA LUCIANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LEUDIMAR OLIVEIRA CARVALHO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LOURIVAL BORGES DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LUCILENE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LUCIMARIA SANTANA SANTOS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LUIS RICARDO MAGIONI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-LUIZ CLAUDIO SALVIANO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MARCIA MORENO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MARCO ANTONIO ALVES DO AMARAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MARCO AURELIO ALVES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MARIA DO SOCORRO FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MARIA JOSE M OLIVEIRA FILHA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MARILU SENZIALI FLOR FERREIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MATHEUS BARROS DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MAURICIO TIAGO SANTANA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MAURILIO BERNARDINO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-MONICA MIYASHIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'Conciliação - PIX RECEBIDO - CP :60701190-NAUTIKA COMERCIAL DE ARTIGOS P', 'juridica', NULL, True, NOW(), NOW());
