INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'F D I BAZAR LTDA MME', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F D I BAZAR LTDA: Descartáveis para festas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F M DE MORAES DRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F. D. I. BAZAR LTDA: Copos descartáveis (água e café) > Mike Rodrigues Gomes > PIX: (11) 9 4588-8760 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'F.D.I. BAZAR LTDA: Itens para loja', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FACEBOOK - DLOCAL E SERVIÇO DE FACEBOOK SERVIÇOS ONLINE DO BRASIL LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FARMACIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FARMÁCIA - LENTE DE CONTATO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FARMÁCIA - ULTRAFARMA POPULAR: MAMADEIRA, NINHO FORT+ E ST JOHNSON BABY (DOAÇÃO)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA (ref. gravação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 1/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 1/18 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 1/22 (compra da loja + rescisão Karina)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 1/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 1/3: Juros/Multas', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 1/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 10/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 2/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 2/18 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 2/22 (compra da loja + rescisão Karina)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 2/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 2/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 3/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 3/18 > PIX: fastnegocios@outlook.com (e-mail) - Tablet 1', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 3/22 (compra da loja + rescisão Karina)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 3/3', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 3/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 4/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 4/18 > PIX: fastnegocios@outlook.com (e-mail) - Tablet 2', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 4/22 (compra da loja + rescisão Karina) - AR CONDICIONADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 4/4', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 5/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 5/22 (compra da loja + rescisão Karina) - ref. Lensômetro Digital VIsion - mod.: GV7000', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 6/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 6/22 (compra da loja + rescisão Karina) - LENSOMETRO PERUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 7/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 7/22 (compra da loja + rescisão Karina)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 8/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 8/22 (compra da loja + rescisão Karina)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 9/10 > PIX: fastnegocios@outlook.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAST COMPANY ARMAÇÕES E LENTES LTDA - Parcela 9/22 (compra da loja + rescisão Karina)', 'juridica', NULL, True, NOW(), NOW())
ON CONFLICT DO NOTHING;


-- Lote 8/13 (1000 registros)

INSERT INTO fornecedores (id, nome, tipo_pessoa, documento, ativo, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'FATURA CARTÃO DE CRÉDITO - BANCO DO BRASIL: CARTÃO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FATURA CARTÃO DE CRÉDITO - BANCO INTER: CARTÃO DE CRÉDITO - LOJA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FATURA CARTÃO DE CRÉDITO - BB ADMINISTRADORA DE CARTOES', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAXA GRILL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FAZENDA REI DO GADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FELIPE ROGER MIRANDA: Pagamento de Consulta Optometrista', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FERNANDO SILVA DE ALMEIDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FESTA: Maria Cristina de Jesus', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FESTIPEL EMBAGLAGENS LTDA: FIO DE NYLON 100M', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FESTIPEL EMBALAGENS LTDA: Interfolha', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FESTIPEL EMBALAGENS LTDA: Papel interfolha e sacola', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FESTIPEL EMBALAGENS LTDA: Sacola vazada', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FGTS: SAMUEL HENRIQUE DA SILVA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (COMPETÊNCIA 04/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (COMPETÊNCIA 05/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (COMPETÊNCIA 07/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (COMPETÊNCIA 08/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (COMPETÊNCIA 09/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (COMPETÊNCIA 12/2021)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA DO TEMPO DE SERVIÇO: JUROS/MULTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FGTS - FUNDO DE GARANTIA POR TEMPO DE SERVIÇO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FIGUEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FILIAL BK DRIVE F', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FILIAL MARGINAL T', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FINAMIX', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FINAMIX: BUCHA E PARAFUSO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FISCAL', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FLAVIO MATOS DA S', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FOCO OPTOMETRIA > PIX: 46.081.461/0001-37 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FOLHAS DE SULFITE', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FONE GIOVANNA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FONTE DE ENERGIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRAMARI', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - ACERTO FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - CHEQUE COMPENSADO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - FRANQUIA: FILIPE LANCASTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - FRANQUIA: GIL LANCASTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - FRANQUIA: MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - MÊS DE FEVEREIRO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - PAGAMENTO: ACERTO LANCASTER', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - PAGTO FRANQUIA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - PAGTO FRANQUIA - DIFERENÇA VENDA E ENTRADA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - PARTE FRANQUIA - ACERTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 1/2 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 1/3 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 1/5 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 1/6 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 2/2 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 2/3 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 2/5 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 2/6 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 3/3 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 3/5 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 3/6 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 4/5 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 4/6 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 5/5 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 5/6 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA - parcela 6/6 > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular) - MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular) - SUZANO I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular) - SÃO MATEUS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular) - moedas do escritório', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular) ~ MAUÁ', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: (11) 9 8117-7178 (celular) ~ SUZANO I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 39.406.028/0001-69 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 39.406.028/0001-69 (CNPJ) - Nubank Junior', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 39.406.028/0001-69 (CNPJ) - Nubank Taty', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 39.406.028/0001-69 (CNPJ) - valor errado', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 52.597.549/0001-09 (CNPJ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 52.597.549/0001-09 (CNPJ) - (MAUÁ)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 52.597.549/0001-09 (CNPJ) - (SUZANO I)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRANQUIA > PIX: 52.597.549/0001-09 (CNPJ) - SUZANO I', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Alessandra Barbosa Leme (divulgação)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Alexandra da Paixão (ref. 20/12 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Ariani Dias Fernandes Líbano (ref. ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Ariani Dias Fernandes Líbano (ref. 24/03 e ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Ariani Dias Fernandes Líbano (ref. 28/03 e ) > PIX: 487.287.868-07 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Aurineide Maria da Conceição (ref. ) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Carlos (ref. ) > PIX: 245.665.728-46 (CPF - Ângela Cristina dos Santos)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Esther Barbosa (ref. ) > PIX: (11) 9 8018-0836 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Esther Barbosa (ref. ) > PIX: (54) 9 5766-8817 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Francielly Ribeiro de Freitas (ref. 12/04 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Julia Mendes da Costa (ref. ) > PIX: vanessamendys151619@gmail.com (e-mail)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Michael Batista (telemarketing - ref. a três dias trabalhados 25/10 a 27/10)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Mike Rodrigues Gomes (ref. ) > PIX: 413.050.558-02 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Nathalia Carolina Cardoso Ribeiro Faustino (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Paulo Sérgio Bueno Junior (ref. 05/04 - )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Sarah Beatriz (ref. ) > PIX: (11) 9 8799-3224 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Sibele Vitória Paula Carvalho (ref. ) > PIX: 520.422.598-61 (CPF)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Thayna Kevilyn Corrêa Reis (ref. ) > Larissa Kevilyn Corrêa Zeferino - PIX: 7ba8b20b-6318-4a6e-a978-e18db9a9bef6 (chave aleatória)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Verônica Cardoso da Cruz (ref. ) > PIX: (11) 9 8836 4697 (celular)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FREELANCER: Wesley de Souza Líbano (ref. )', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRETE: GELADEIRA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRETE: Pães', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRIMAR COMERCIO DE A', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FRUTAS', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUKUYA KANEMOTO', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 01/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 01/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 01/2024) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 01/2024) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 01/2025)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 02/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 02/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 02/2024) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 02/2024) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 02/2025)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 03/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 03/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 03/2024) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 03/2025)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 03/2025) - TM COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 03/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2024) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2025) - GIOVANNA COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 04/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2024) - Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2024) - Joana D''arc Elvira Jesus Alves Araújo', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2024) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2025) - GIOVANNA COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 05/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2024) - Eliana Savoia', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2024) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 06/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2023) - Nathalia Carolina Cardoso Ribeiro Faustino', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2024)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2025) - GIOVANNA COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 07/2025) - TMO COMERCIO VAREJISTA DE OTICA LTDA', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 08/2023)', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 08/2023) - Maria da Conceição Ramos de Moura', 'juridica', NULL, True, NOW(), NOW()),
    (gen_random_uuid(), 'FUNDO DE GARANTIA DO TEMPO DE SERVIÇO (competência 08/2023) - Zaine de Lima Siqueira', 'juridica', NULL, True, NOW(), NOW());
